### ISSUE TITLE
Generate sub-auctions when creating an auction

### ISSUE THREAD

**Issue by jessepinho** [penumbra-zone/web#1032]
10m: 4 auctions, 60 blocks long (5m), step_count=60, start heights ~ poisson(lambda = 0.775/min), rel gas = 480x
30m: 12 auctions, 60 blocks long (5m), step_count=60, start heights ~ poisson(lambda = 0.607/min), rel gas = 1440x
1h: 12 auctions, 120 blocks long (10m), step_count=60, start heights ~ poisson(lambda = 0.303/min), rel gas = 1440x
2h: 24 auctions, 120 blocks long (10m), step_count=60, start heights ~ poisson(lambda = 0.272/min), rel gas = 2880x
6h: 36 auctions, 240 blocks long (20m), step_count=60, start heights ~ poisson(lambda = 0.129/min), rel gas = 4320x
12h: 36 auctions, 480 blocks long (40m), step_count=60, start heights ~ poisson(lambda = 0.064/min), rel gas = 4320x
24h: 48 auctions, 720 blocks long (1h), step_count=60, start heights ~ poisson(lambda = 0.042/min), rel gas = 5760x
48h: 48 auctions, 1440 blocks long (2h), step_count=60, start heights ~ poisson(lambda = 0.021/min), rel gas = 5760x

Source: [Discord](https://discord.com/channels/824484045370818580/938328380917559326/1235723630965686363)

**Comment by hdevalence** [comment]
Let's wait to implement this, we'll be adding support to `pcli` and testing it end-to-end there, and then the Rust code in pcli can be translated over to the web.

**Comment by jessepinho** [comment]
Closing as dupe of #981
