### ISSUE TITLE
Consider adding password requirements or recommendations

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#1037]
Some very basic password requirements were removed previously in https://github.com/penumbra-zone/web/commit/63b56e346e6cff8132edb738da22a62a39e81ed6

There was some reasoning that the user is ultimately responsible for the password, and should be free to choose. All users ought to already understand the benefits of a good password, and enforcing requirements may be inconvenient or counterproductive. Another point being the browser extension is intended for hot wallet use only, and should not contain significant tokens.

There was also a strong motivation for developer convenience. Requirements should be toggled with build configuration, in this case.

We should consider

- restoring password requirements, with a dev-mode toggle
- providing password *recommendations*, requiring user affirmation to set a 'bad' password

**Comment by turbocrime** [comment]
one complicating factor is that browser-based password managers don't reliably work within extension ui

**Comment by hdevalence** [comment]
I'm happy to have warnings but I don't think we should have hard requirements for the same reasons as before. I don't think an extra setting that adds a new mode is desirable.

**Comment by TalDerei** [comment]
closing as not planned
