### ISSUE TITLE
minifront footer plugin generates bad git commit URL

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#1046]
https://github.com/penumbra-zone/web/blob/9db3989190f22b72545644a4b92a2c2286657ea0/apps/minifront/src/utils/commit-info-vite-plugin.ts#L9-L12

this may create a url like `https://localhost:5173/git@github.com:penumbra-zone/web/commits/ceafe995e08db5f9f6fdaaa84c484706ea188251`

**Comment by grod220** [comment]
We haven't encountered this I suppose because `actions/checkout@v4` does not use ssh to pull down. Regardless, we can improve this plugin to guard against that possible case.

**Comment by TalDerei** [comment]
closing since we haven't encountered this
