### ISSUE TITLE
Blogpost about web wallet on penumbra.zone written & communicated

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#105]

**Comment by conorsch** [comment]
From planning: there are likely two (2) blog posts in here, only one of which we want and/or need for Rhea 63:

1. Intro to explaining how interfaces (https://github.com/penumbra-zone/penumbra/issues/1775) map to decentralization goals of the project.
2. Deeper discussion about the technical details of innovative message passing (by way of @turbocrime), service workers as gRPC services, router logic as discrete package to aid external devs.

The drafting will likely fall to @hdevalence and @grod220. We hope to focus on 1 for 63.
