### ISSUE TITLE
IBC-in address selection

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1051]
At the moment, for IBC-in, we are making deposits into Account #0 for users:

<img width="532" alt="Screenshot 2024-05-07 at 4 51 37 PM" src="https://github.com/penumbra-zone/web/assets/16624263/218b40c1-cec0-4552-b762-8d774057d966">

https://github.com/penumbra-zone/web/blob/bf28b67ed2b974fa4c513c7f0182d343a763f721/apps/minifront/src/components/ibc/ibc-in/destination-addr.tsx#L11-L16

We should A) evaluate this flow in general and B) consider giving users the choice of which account to deposit into.

====

1. Give users an account selector widget (do not show the addresses)
2. Instruct users to validate their address in the keplr popup in the extension (assumption this is built).

===

Update: account selector component is able to split up to just get the account input and not display the address. Should try to re-use this.

**Comment by jessepinho** [comment]
Why do we not want to show the user their addresses? Was this for educational reasons — i.e., to get them in the habit of copying the address in the approval window into the Penumbra wallet screen, for security reasons?

**Comment by grod220** [comment]
This came up in a web weekly a while ago. The idea was that the address we are displaying there cannot be trusted because the javascript could be deceiving them (given a malicious frontend). The only address they can trust is the one that pops up in the keplr/leap dialog box which they need to validate in the address validation box within the extension.
