### ISSUE TITLE
Swap claims not being detected

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1054]
Can validate this with the [testnet whale](https://rustdoc.penumbra.zone/main/penumbra_keys/test_keys/constant.SEED_PHRASE.html) given it currently has a number of unclaimed swaps.

Can successfully build, but will hang indefinitely as it waits for it to be detected on chain.

After refreshing after a bit, it does seem to be removed from the unclaimed swaps list, however it's not found in tx details page.

**Comment by erwanor** [comment]
@TalDerei might provide more color there but my understanding is that in https://github.com/penumbra-zone/penumbra/pull/4312 we learned that the current wasm planner cannot balance `SwapClaim`s, this was fixed in the PR, improved on in [#4319](https://github.com/penumbra-zone/penumbra/pull/4319/files#diff-6481346b149ffc0125b29fda68ef35a6d92e876b2cedfeca2385c437ebaa3192R78), and needs to be backported/refactored via https://github.com/penumbra-zone/penumbra/issues/4332

**Comment by erwanor** [comment]
Flagging this because I think the detection issue could be a surprising symptom of tx planning not working

**Comment by Valentine1898** [comment]
Could be related to https://github.com/penumbra-zone/web/issues/1003

After many attempts to debug #1003 I came up with nothing. It's like tendermint sometimes gives wrong transaction list for a block, but if you request transaction list for the same block after some time, everything is fine. 

I'll try to provide more details, maybe it will be useful for this issue

**Comment by erwanor** [comment]
Could it be that depending on where they are emitted from, the prepaid fee is different, causing the balancing problem in some cases and not others?

**Comment by TalDerei** [comment]
> Could it be that depending on where they are emitted from, the prepaid fee is different, causing the balancing problem in some cases and not others?

but fees aren't currently enabled in the web, and it's still operating under a zero fees structure. Wouldn't the prepaid fee balance in that case?

**Comment by erwanor** [comment]
Hmm good point, it looks hardcoded to zero in minifront, and computed from the on-chain gas prices in pcli (which should be zero)

**Comment by TalDerei** [comment]
@erwanor if you look at this list, you'll notice some swap are followed by a swap claim and some are not. The swaps that succeed and are followed by the swap claim have zero fees, while the swaps that succeed and are _not_ followed by the swap claim have non-zero fees. It's a fee balancing bug, and push on https://github.com/penumbra-zone/penumbra/issues/4332 and https://github.com/penumbra-zone/web/issues/876.

<img width="1728" alt="Screenshot 2024-05-07 at 8 59 45 AM" src="https://github.com/penumbra-zone/web/assets/70081547/f5bd3479-3c30-4235-99b1-7fe908e12a17">

**Comment by erwanor** [comment]
Makes sense! nice sleuthing

**Comment by TalDerei** [comment]
tagging as `on-hold` until the changes in #4332 land in `0.74.0` upgrade release, at which point we can update our rust deps and modify the web planner accordingly.  

cc @grod220 @conorsch

**Comment by TalDerei** [comment]
unblocked by https://github.com/penumbra-zone/penumbra/releases/tag/v0.74.0

**Comment by TalDerei** [comment]
closing -- fixed in #1095
