### ISSUE TITLE
display raw json of opaque fields in transaction view 

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1065]
display a limited form of the [raw JSON](https://discord.com/channels/824484045370818580/1044457038886998137/1237424897513230406) (opaque fields) in the public view of the completed transaction view.

**Comment by hdevalence** [comment]
I don't think we should do this -- action views should either be complete, or not rendered at all ("Unimplemented Action"). We don't ever want to be exposing raw JSON or any other unformatted content in the transaction view components. They should have a semantically meaningful representation.
