### ISSUE TITLE
high cpu from svg animation

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#1067]
<img width="1018" alt="Screenshot 2024-05-07 at 16 18 58" src="https://github.com/penumbra-zone/web/assets/134443988/c8b168a7-2855-4e4c-b1b0-a5c8144508c9">

my m3 pro is dropping most frames, so i think it's safe to consider this too heavy.

currently, the animation calculates a new path, and mutates the path attribute every frame, causing a rerender.

the animation is a loop so paths could be cached. some components of the animation could easily be a css animation, such as the constant rotation.

options

1. substantially reduce the framerate
3. calculate all paths once, render the frames, and animate that
4. calculate all paths once, and use them as keyframes for an animated svg path
5. use the same path logic to render paths on a canvas, instead of in svg
6. use canvas and gpu-rendered geometry

(3) will be the simplest but ime real svg animation still results in high cpu and may not be worth it

**Comment by TalDerei** [comment]
I experienced this as well, massive frame drops on my M3 Pro that slowed down my machine

**Comment by grod220** [comment]
That's too bad. Let's swap for static logo svg for now. Going to loop back in the original animator to see what optimization they can do.

**Comment by TalDerei** [comment]
@grod220 what's the current status of this?
