### ISSUE TITLE
Support swapping `max` in swap form

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1069]
_Idea from @erwanor_ 

For Dexes, it's quite common to want to swap an entire balance of a token. Either there is a dedicated max button or the wallet balance is clickable. See Sushi:

https://github.com/penumbra-zone/web/assets/16624263/38632456-50eb-43c3-892b-aa15b1d56583

This feature is particularly helpful in cases there there are many digits (e.g. `324.979884960959`). 

In our case, is seems easy enough to make this clickable to insert the max balance:

<img width="194" alt="Screenshot 2024-05-08 at 10 58 57 AM" src="https://github.com/penumbra-zone/web/assets/16624263/aeb911c2-9b93-4fcc-b7a1-7fca80ae29da">

**Comment by Valentine1898** [comment]
It might make sense to do all the DEX ui improvements together https://github.com/penumbra-zone/web/issues/972
