### ISSUE TITLE
You will not be able to click on "Send" in menubar when you are on IBC page 

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#1080]
Watch the screen recording here: https://jam.dev/c/64bdfeae-b924-48be-b3e8-ebe01c752b8e

-------------------------------------

**Website URL:**
[https://localhost:5173/#/ibc](https://localhost:5173/#/ibc)

**Device and browser info:**
Chrome 124.0.6367.94 (2304x1209) | Mac OS (arm) 10.15.7

**Date and time:**
May 9th 2024 | 3:49pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/64bdfeae-b924-48be-b3e8-ebe01c752b8e](https://jam.dev/c/64bdfeae-b924-48be-b3e8-ebe01c752b8e)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by turbocrime** [comment]
seems this only happens on widest layout

<img width="2056" alt="Screenshot 2024-05-09 at 10 58 56" src="https://github.com/penumbra-zone/web/assets/134443988/f9691a95-b85c-465f-a630-1366e3583e47">

**Comment by Valentine1898** [comment]
No longer reproduced, looks like Jesse unintentionally fixed it in https://github.com/penumbra-zone/web/pull/1167

**Comment by turbocrime** [comment]
this is still happening, it's dependent on the medium width layout
