### ISSUE TITLE
unpublish dead npm packages

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#1082]
- [x] `@penumbra-zone/bufbuild-protobuf`
- [x] `@penumbra-zone/constants`
- [x] `@penumbra-zone/polyfills`
- [x] `@penumbra-zone/test-package`
- [x] `@penumbra-zone/test-publish`
- [x] `@penumbra-zone/tsconfig`
- [x] `@penumbra-zone/wasm-bundler`
- [x] `@penumbra-zone/wasm-nodejs`
- [x] `@penumbra-zone/wasm-web`
- [x] `@penumbra-zone/services-context`
- [x] ~`@penumbra-zone/ui`~ (continuing to use)
- [x] `@penumbra-zone/tailwind-config`
- [x] ~`@penumbra-zone/eslint-config`~ (may use)
- [x] `@penumbra-zone/eslint-config-custom`
- [x] `@penumbra-zone/test-publish`
- [x] `@penumbra-zone/test-package`

**Comment by turbocrime** [comment]
possibly more lol

**Comment by turbocrime** [comment]
as packaging has settled it makes sense to work on this

iirc @grod220 is the only one who can take action

i think `@penumbra-zone/query` will also disappear shortly, but for now it hosts the block processor

**Comment by TalDerei** [comment]
what's the status of this npm task?

**Comment by turbocrime** [comment]
afaik only @grod220 can do it

**Comment by grod220** [comment]
It was only allowed to deprecate these:
- @penumbra-zone/constants
- @penumbra-zone/polyfills

These I kept as we will want to use these for the future:
- @penumbra-zone/eslint-config
- @penumbra-zone/ui

The rest have been deleted
