### ISSUE TITLE
minifront may improperly show 'genesis state syncing'

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#1084]
<img width="1018" alt="Screenshot 2024-05-09 at 11 01 21" src="https://github.com/penumbra-zone/web/assets/134443988/71f796f8-cae5-4906-9ec6-df0da7710c95">

i believe this is related to

1. a querier that asserts a possible undefined https://github.com/penumbra-zone/web/blob/4208c5074ce1c87a759af0150e9adac1ef29f54c/packages/query/src/queriers/tendermint.ts#L15-L18
3. the sync status component treating undefined the same as 0n

this mainly occurs when the tendermint endpoint is unavailable.

i already have some work on this that happened related to #998 that could resolve this

**Comment by TalDerei** [comment]
<img width="1727" alt="Screenshot 2024-05-13 at 10 44 43 AM" src="https://github.com/penumbra-zone/web/assets/70081547/29259847-eb21-4d39-bcf2-3b4d50d24aca">
 
flagging related bug
