### ISSUE TITLE
ui: view transaction history

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1102]
for new users, clicking on the penumbra text on the top-left side is not the most intuitive UI for viewing their transaction history. I think these pages should have an additional option that's more obvious. 

<img width="1723" alt="Screenshot 2024-05-10 at 12 49 57 PM" src="https://github.com/penumbra-zone/web/assets/70081547/9a9cc9f9-5c5d-4771-b04d-5178f079595a">

**Comment by TalDerei** [comment]
cc @grod220 thoughts?

**Comment by grod220** [comment]
Before we had a `Dashboard` tab that basically highlighted that you were on the homepage. If I recall right, some other folks thought it was unnecessary given clicking on the logo was intuitive. But perhaps not!

For something like this, think I'd lean on an opinion from Sam. Any thoughts on this @smmhrdmn?

**Comment by smmhrdmn** [comment]
I agree that the logo being the only "homepage" button is not intuitive. I would definitely add an additional tab, more precisely labeled than not. Dashboard is too generic imo, and hints at something that the transaction history page doesn't necessarily offer. I also think there's a case to be made for making another page the homepage, perhaps shielding.
