### ISSUE TITLE
ui: improve design of IBC page 

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1103]
@jessepinho I think we can make some simple changes to make this look nicer, eg. change color of light grey screen box for shielding funds, removing the arrows and moving inbound / outbound boxes around, etc. 

<img width="1728" alt="Screenshot 2024-05-10 at 12 54 28 PM" src="https://github.com/penumbra-zone/web/assets/70081547/20a9f06d-76a4-4f8f-bf8e-2b20c08664ce">

**Comment by grod220** [comment]
There's been a good deal of discussion regarding design of this page: https://github.com/penumbra-zone/web/pull/808. Think we've come to the end of what the eng team is reasonably able to contribute on this front. If there are specific things to immediately improve, we can certainly consider it. However, this page's design generally (along with the rest of minifront) should lean on Sam's expertise when he is ramped up.

**Comment by TalDerei** [comment]
closing in favor of a more detailed UX design process for IBC page
