### ISSUE TITLE
broken asset in cosmos asset registry

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1104]
**usdlr** asset in cosmos chain registry broken https://github.com/cosmos/chain-registry/blob/master/testnets/nobletestnet/assetlist.json#L84. don't have all the context here

**Comment by grod220** [comment]
Waiting for maintainer to approve: https://github.com/cosmos/chain-registry/pull/4626

**Comment by grod220** [comment]
Fixed 👍
