### ISSUE TITLE
Do not display zero balances 

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#1112]
Most zero balances result from an unfilled swap that generates zero notes. 
We need to filter out null balances, either at the rpc layer (I assume this is better) or at the UI layer

**Comment by hdevalence** [comment]
Zero-valued notes shouldn't need to be filtered out at the RPC or UI layers, because we should eliminate them at the scanning layer -- when we detect a note, we should skip recording it if it's zero-valued.

**Comment by Valentine1898** [comment]
> Zero-valued notes shouldn't need to be filtered out at the RPC or UI layers, because we should eliminate them at the scanning layer -- when we detect a note, we should skip recording it if it's zero-valued.

The thing is that rust view service doesn't filter zero notes during the scanning process 
1. it saves zero notes in DB 
<img width="900" alt="image" src="https://github.com/penumbra-zone/web/assets/25391690/0afdcd71-356d-426e-a9e6-ce7b20daaa28">

2. it filters them at the moment of reading from DB (basically at the RPC layer). 
https://github.com/penumbra-zone/penumbra/blob/abfd764954819a19b923c268d143f55a11e26ae0/crates/view/src/storage.rs#L927-L929

I suspect that null notes can affect SCT and transaction detection, so I'm not sure that filtering out null notes in the scanning phase is completely safe
