### ISSUE TITLE
Better rendering display of assets

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1120]
Currently, it's a bit confusing the manner in which we display assets of the same type...we should group by account or asset type. 

<img width="1728" alt="Screenshot 2024-05-15 at 4 29 10 PM" src="https://github.com/penumbra-zone/web/assets/70081547/8e08d379-a318-4729-ada8-867baa5a3fd8">

**Comment by TalDerei** [comment]
@VanishMax, was this completed? we should also add a minifront v2 task for asset rendering.

**Comment by VanishMax** [comment]
@TalDerei no, it isn't completed yet. We sorted the assets by account index in the dashboard but the asset selectors
