### ISSUE TITLE
Dutch Auction Schedule transaction failed:  input amount MUST be less than 52 bits wide

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#1124]
When trying to create a Dutch auction with TestUSD asset you will get an error 
```
Dutch Auction Schedule transaction failed
Error: [unknown] Tendermint error 1: failed to deliver transaction: check_stateless failed: input amount MUST be less than 52 bits wide
``` 
<img width="1343" alt="image" src="https://github.com/penumbra-zone/web/assets/25391690/485acb72-957f-455a-bbc4-c21dced92b24">

**Comment by erwanor** [comment]
Good catch, that's correct, we won't support assets with large denom unit amounts

**Comment by grod220** [comment]
Is something we'll reasonably run into at mainnet or just an issue with testnet `gn`?

**Comment by hdevalence** [comment]
It's a problem with our `test_usd` asset that has 18 decimals, the USDC asset has 6 decimals, which is why we decided to make this restriction, so we wouldn't have to think about it
