### ISSUE TITLE
Tx approval should put contents on one line for info density

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#1129]
<img width="372" alt="Screenshot 2024-05-16 at 10 33 50 PM" src="https://github.com/penumbra-zone/web/assets/44879/eae07024-b8ab-4212-88b6-1b14c295cad7">

Each Spend, Output should have one line of content, possibly with smaller text if necessary. There is too much scrolling to be able to see the transaction at a glance.

**Comment by hdevalence** [comment]
We'd like to do an overhaul of the tx approval UI (cc @smmhrdmn), and maybe this should be done according to those wireframes once they exist?

**Comment by smmhrdmn** [comment]
Noted! Will work on pushing this forward

**Comment by jessepinho** [comment]
(I'm currently kicking this down the road a little in hopes that I can wait to work on it until we have some primitives/etc. in Figma.)
