### ISSUE TITLE
Split up AuthorizeAndBuild

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#113]
Currently, the grpc method for building requires authorization beforehand: https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.view.v1alpha1#penumbra.view.v1alpha1.ViewProtocolService.AuthorizeAndBuild.

This is an issue as building can be done at the same time the user is viewing/signing their transaction. This will reduce the _percieved_ building time. The rust code already supports this (TransactionPlan::build returns the UnauthTransaction). 

WitnessAndBuild may need to be altered as well: https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.view.v1alpha1#penumbra.view.v1alpha1.ViewProtocolService.WitnessAndBuild.

**Comment by Valentine1898** [comment]
Additionally, it makes sense to add `UnauthTransaction` to proto 
Since there is supposed to be a wasm function that should return `UnauthTransaction`

**Comment by TalDerei** [comment]
This is a consideration further down the line, but it may be prudent to start thinking about potential DoS attack vectors? For instance, can a user can open many connections that preemptively start building the transaction proofs -- without ever completing the signing phase of the transaction. Regardless, this optimistic proving approach seems promising from a UX perspective.

**Comment by grod220** [comment]
> potential DoS attack vectors

This work is always client-side though. So wouldn't that be the user DoS'ing themselves?

**Comment by grod220** [comment]
Superseded by [#324](https://github.com/penumbra-zone/web/issues/324)
