### ISSUE TITLE
Dynamic precision for the Amount field

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#1139]
If you enter, in the Amount field, more digits after the dot than the denom exponent, it will cause an error that will not be displayed to the user 
<img width="350" alt="image" src="https://github.com/penumbra-zone/web/assets/25391690/f5a7d4dd-0cee-4e33-83d0-a88874847d44">
<img width="400" alt="image" src="https://github.com/penumbra-zone/web/assets/25391690/75bcb453-e07c-4836-a1ab-c80653c548ed">

For some assets, users can only enter integer values (e.g. `CUBE` or any unknown asset) 
<img width="350" alt="image" src="https://github.com/penumbra-zone/web/assets/25391690/c3d302d6-f032-4a80-94f7-44f73daa7725">
<img width="400" alt="image" src="https://github.com/penumbra-zone/web/assets/25391690/d8f8b8d1-efec-4724-bd4e-ccb71cf73aa8">

**Comment by Valentine1898** [comment]
> We should allow the user to enter any value, but communicate the validation error like we do in the other cases (red text above input with error message)

Or alternatively, we can use a solution as in 1inch and uniswap, if user has entered the maximum number of decimals, they cannot enter any more

**Comment by grod220** [comment]
In general, I'd be in more favor of communicating versus inferring. However, in this case, it may still be intuitive to just disallow the keypress if too long. I'm open to either way 🤷
