### ISSUE TITLE
Assets table ordering

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1149]
After https://github.com/penumbra-zone/penumbra/pull/4441 is deployed, the rpcs will have an ability to assign priority scores before returning metadata to the frontend. This is something that the dashboard view can use. At the moment the ordering is a bit arbitrary:

<img width="1444" alt="Screenshot 2024-05-23 at 1 19 37 PM" src="https://github.com/penumbra-zone/web/assets/16624263/8fd4b80f-43ab-4223-ad44-ac5e8ccbc5ac">

We can consider adding scores like so:

| Asset          | Priority Score |
|----------------|-------|
| UM             | 0     |
| Normal denoms  | 10    |
| Auctions       | 20    |
| Delegations    | 30    |
| Unbonding      | 40    |
| Unknown assets | 50    |

That way, the frontend can simply sort on priority score

====

Alternatively, the registry can manually add priority scores for each asset: https://github.com/prax-wallet/registry/blob/main/registry/penumbra-testnet-deimos-8.json

**Comment by hdevalence** [comment]
I think the ordering should be reversed, so that it would be possible to have priority = market cap in the future

**Comment by TalDerei** [comment]
this looks unblocked, and tagging https://github.com/penumbra-zone/web/issues/1120 as relevant scope cc @VanishMax
