### ISSUE TITLE
 multi-asset fees support in minifront

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1165]
We have multi-asset fee support at the protocol level, and the web planner implementation has achieved parity with core. There are supplemental UX changes that need to be implemented to fully realize this. 

Logic:
- if the user has UM, use that for fees
- otherwise, use the first alt fee token that they have balance of
  - tx approval warns about non-native fees as a privacy risk and recommends using native token
- otherwise, error that they have no available fee tokens

**Comment by grod220** [comment]
Updated the description a bit. The Fee denom gets set to staking token in the default() initialization: https://github.com/penumbra-zone/web/blob/5b80e7cf988475fcbace89c62643d42f3a58135a/packages/wasm/crate/src/planner.rs#L205

It looks like, before this, we need to check for balances of UM. If none, initialize ActionList with the alt denom and I believe the methods below should work as is (?). Definitely needs testing out. Also, `transaction_parameters` needs likewise updating.

**Comment by TalDerei** [comment]
folding in https://github.com/penumbra-zone/web/issues/1265 as relevant scope
