### ISSUE TITLE
Add a "claim all" button to the auctions list to claim all unclaimed reserves of ended auctions

### ISSUE THREAD

**Issue by jessepinho** [penumbra-zone/web#1166]
Currently, there's no way to end or withdraw all auctions when using Minifront. This causes problems as a user can create one transaction that requires nearly 100 manual steps to clean up. Instead, Minifront should provide close-all / end-all functionality.

At the top of this tablular layout, there should be a row with 0 or 1 buttons:

![image](https://github.com/user-attachments/assets/a68281b3-ba91-4eb1-bad8-d2475ff5df87)

- [ ] If any auctions in the list are open, the button should be labeled "End All". Clicking the button should plan and sign a transaction that ends every open auction.
- [ ] Otherwise, if no auctions are open but some auctions are ended, the button should be labeled "Withdraw all". Clicking the button should plan and sign a transaction that withdraws every ended auction.
- [ ] Otherwise, all auctions are withdrawn, and there should be no button.

**Comment by hdevalence** [comment]
user feedback: https://x.com/Rarma_/status/1818847396983718366

will edit the issue description with what i think the behavior should be

**Comment by Valentine1898** [comment]
I'm not sure we only need one button to make the user experience better  

If we do as in pcli, we should have two buttons 
- end all auctions (including those that have not started yet and those that are currently active)
- withdraw all auctions 

If you do it all with one button, that means you can't withdraw auctions if you have at least one auction you don't want to end 

Also, it is worth noting that the user will not be able to end only auctions that have already passed

Ideally, it would be cool to have three options 
- close only past auctions 
- сlose all auctions (past, active, and future)
- withdraw all auctions

@hdevalence What's your vision for this?

**Comment by Valentine1898** [comment]
I experimented a bit with pcli and found some interesting things to consider in this PR 
1. If you try to create a transaction with more than 300 actions, you will get a planner error 
```
failed to plan transaction after 100 iterations
``` 
2. If you have between 200 and 300 actions, the planner will most likely be able to build the transaction, then you won't be able to broadcast it to the network because of its size 
```
 status: Unavailable, message: "error broadcasting tx: Status
  {   code: Unavailable,
   message: error broadcasting tx sync: response error
  Caused by: Internal error: Tx too large. Max size is 98304, but got 110583 (code: -32603)
  
```

**Comment by Valentine1898** [comment]
Given that each auction end requires 2 actions, and each auction withdrawal requires either 2 or 3 actions (depending on the auction result)
Then we can guarantee to close a maximum of 100 auctions in a single transaction and withdraw a maximum of 66 auctions

Another point is that pcli closes auctions and outputs them for each account separately, while in minifront we have one list for all accounts (and that's bad).

**Comment by Valentine1898** [comment]
Okay, I'm wrong somewhere, because in practice it requires 146 actions to complete 48 auctions (while 48 auctions can be created with just 1 transaction)

**Comment by hdevalence** [comment]
> If you do it all with one button, that means you can't withdraw auctions if you have at least one auction you don't want to end

I don't think this is important to prioritize, what we should focus on is the common case. I think the behavior in the original description is good

**Comment by jessepinho** [comment]
@Valentine1898 
> Given that each auction end requires 2 actions, and each auction withdrawal requires either 2 or 3 actions (depending on the auction result)

Not sure I understand this. Ending an auction is a single action (`ActionDutchAuctionEnd`), and withdrawing is a single action (`ActionDutchAuctionWithdraw`). Where are you getting these numbers?

**Comment by Valentine1898** [comment]
@jessepinho 
In order to end the auction you need to take the following actions 
1. Spend a note for fee
2. Spend auction_nft_0
3. Get auction_nft_1
4. Get balance of fee note 
5. ActionDutchAuctionEnd

Theoretically, fee may require more than one note (but this is rare) 
Also theoretically, you may not have a remainder after spending a fee note (almost impossible case).
Basic case - you need 5 actions to close the auction

<img width="1480" alt="image" src="https://github.com/user-attachments/assets/813a7914-11da-4e7c-b4f4-f14294290394">

**Comment by hdevalence** [comment]
How about doing at most 48 at a time, and if there are more, display an alert to the user that only the first 48 auctions were ended. 48 is the max number that we create at once. This also minimizes the proving time per tx in the web context.

**Comment by Valentine1898** [comment]
> Another point is that pcli closes auctions and outputs them for each account separately, while in minifront we have one list for all accounts (and that's bad).

This creates more problems than I originally thought because we can't create sourceless transactions 
This means that we need to change the auctions interface so that the auctions are separated by account 

fiy @grod220 @jessepinho

**Comment by Valentine1898** [comment]
> How about doing at most 48 at a time, and if there are more, display an alert to the user that only the first 48 auctions were ended. 48 is the max number that we create at once. This also minimizes the proving time per tx in the web context.

It's definitely a good idea
