### ISSUE TITLE
auction ui: unknown assets errors

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1172]
Unknown assets should be properly handled and filtered out, otherwise it can throw an error in the extension.

https://github.com/penumbra-zone/web/assets/70081547/3b8cc09a-7695-4705-b615-0eb64f8a420b

<img width="1728" alt="Screenshot 2024-05-25 at 10 43 16 AM" src="https://github.com/penumbra-zone/web/assets/70081547/58210c6f-11bb-4453-9f85-584e2a8885ce">

@jessepinho

**Comment by Valentine1898** [comment]
https://github.com/penumbra-zone/web/blob/e86448e295a7fe4aeaee3d0e6d3d9478e41933ac/apps/minifront/src/components/swap/helpers.ts#L39-L44

`getSwappableBalancesResponses` takes this into account and should not return unknown assets, but it seems that once swap and auction are merged, `getSwappableBalancesResponses` is not always used
I'll pick up

**Comment by Valentine1898** [comment]
How do you create unknown assets?  @TalDerei

**Comment by Valentine1898** [comment]
https://github.com/penumbra-zone/web/blob/e86448e295a7fe4aeaee3d0e6d3d9478e41933ac/packages/ui/components/ui/tx/view/value/index.tsx#L31
Ah, in fact, all of these assets are known 
They just don't have a symbol defined, so they show up as unknown

**Comment by Valentine1898** [comment]
It's a real unknown asset: 
<img width="250" alt="image" src="https://github.com/penumbra-zone/web/assets/25391690/cb4c7a7e-2fbb-4344-8013-2951314eba78">
and this is an unknown asset decoy
<img width="250" alt="image" src="https://github.com/penumbra-zone/web/assets/25391690/52b43eed-92b8-427e-ba84-f24b6758fe90">
