### ISSUE TITLE
state issues in auction row rendering

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#1181]
<img width="858" alt="Screenshot 2024-05-27 at 7 45 50 PM" src="https://github.com/penumbra-zone/web/assets/44879/30c0b57c-c86b-4a4f-95d1-eb8d49e86b1c">

Some issues/papercuts I wanted to note to make sure they were tracked (feel free to deduplicate):

- [x] The first active auction is shown as having "25s of 5m remaining", but it already closed at price 1.000, the UI was never informed about this
- [x] The last auction is already canceled (hence "withdraw"), but this is not reflected in the UI. Probably we want to have a red ⊗ symbol (maybe literally `\U+2297`, idk?) that indicates that the auction was cancelled. (We can distinguish the two "completed" states by whether or not there is any of the input asset in the reserves, if so, it's the failure case, if there is none, it's the success case)
- [x] The expanded details should put "block" next to the block number so that it's more clear what the number means
- [x] The expanded details should have a line showing the auction ID with a copy paste button (for xref'ing on explorers)

**Comment by jessepinho** [comment]
@hdevalence:
> We can distinguish the two "completed" states by whether or not there is any of the input asset in the reserves

Wouldn't there also be input asset in the reserves if there isn't enough liquidity to cover all the input assets? (Just like in a swap?)

**Comment by hdevalence** [comment]
Yes, but from the user's perspective, that's a (soft) "failure" because their intent was to sell all of their input tokens.

I think we want to have:

- Green checkmark if the auction ended with complete fill (no input asset remaining)
- Red X if the auction ended with incomplete fill (input asset remaining)

This maps onto whether or not the auction successfully sold all the input tokens. When the user sees a green checkmark they know they did the trade. When they see a red X they know it didn't completely execute (which could be ebceuase they cancelled or because no liquidity or... in any event it's not what they originally wanted when scheduling the auction).
