### ISSUE TITLE
Graz wallet interface support

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1190]
[Ibc.fun](https://ibc.fun/) has become one of the canonical ways that cosmos users do multi-chain asset transfers. It even extends into Solana and Base. Under the hood, it uses [Graz](https://graz.sh/) to manage wallet connections. The library acts as a kind of aggregator for wallets to unify the API for web frontends and expose react-hooks for easy consumption.

While the [Graz wallet interface](https://github.com/graz-sh/graz/blob/498692939b5f5ba257cac0711efebd2f8cc04fd9/packages/graz/src/types/wallet.ts#L22-L54) does not match our protocol, we can put Prax-specific implementations behind those calls. This will allow Ibc.fun to integrate with Prax.

While signatures are not relevant, we should prioritize implementing:
- Wallet connection requests
- Wallet disconnect requests
- Get address
- Wallet state

This may require implementing https://github.com/penumbra-zone/web/issues/1093 first.

**Comment by TalDerei** [comment]
closing as implemented in https://github.com/penumbra-zone/web/pull/1943
