### ISSUE TITLE
Install Prax bug

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1191]
In an incognito window visit https://app.testnet.penumbra.zone/. The web app is not able to detect install status of the extension and requests to connect instead:

<img width="1238" alt="Screenshot 2024-05-28 at 5 36 33 PM" src="https://github.com/penumbra-zone/web/assets/16624263/1020dc95-6761-4a24-bde6-1517484319a1">

The UI should instead display a link to go to the chrome store to download the app.

**Comment by Valentine1898** [comment]
<img width="847" alt="image" src="https://github.com/penumbra-zone/web/assets/25391690/4f95dfe9-ee20-4496-9fde-ab7e24116e91">
By default all extensions are inaccessible in incognito mode, but you can enable this in the settings

**Comment by grod220** [comment]
@Valentine1898, added some clarification to the description. The incognito window is just an example way to get a UI that should prompt the user to _install_ the extension (link to chrome store) and not _connect_.

**Comment by Valentine1898** [comment]
> @Valentine1898, added some clarification to the description. The incognito window is just an example way to get a UI that should prompt the user to _install_ the extension (link to chrome store) and not _connect_.

Ah, okay, I misunderstood
