### ISSUE TITLE
Auction withdraw infinite pending 🐛 

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1212]
Reported by @plaidfinch

> the "withdraw" action for auctions spins pending for an indefinite period of time, but when you retry it, this happens
> the button to withdraw the auction remains in the interface, despite it seemingly have been withdrawn on chain?
it seems like this button should become inaccessible once the auction has been withdrawn

<img width="789" alt="Screenshot 2024-05-30 at 2 26 17 PM" src="https://github.com/penumbra-zone/web/assets/16624263/f685d19c-db41-448d-88c2-9d8972629bf8">

**Comment by Valentine1898** [comment]
I tried to reproduce it, but couldn't. 
I did many withdraw attempts, all of them were successful, and after that for withdrawn auctions no withdraw button was displayed

**Comment by jessepinho** [comment]
This _may_ be related to #1285, where we're showing a "Withdraw" button for auctions after the user clicks the "Query latest state" button — even if the user hasn't yet exchanged their seq 0 token for a seq 1 token. I'll get on that soon. It looked like that was causing a different error message than Finch got, though, so I'm not sure #1285 willi fix this.

**Comment by jessepinho** [comment]
@plaidfinch is this still happening for you?

**Comment by jessepinho** [comment]
Moving this to Blocked until we know whether it's still happening/is reproducible.
