### ISSUE TITLE
Sub-auction scaled input/output amount math fails

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#1223]
it seems like the bignumber division logic in get-sub-auctions does not always successfully create round numbers, throwing the `BigInt` conversion calls

https://github.com/penumbra-zone/web/blob/4f8c150f0f4471567dc9418758d495d8bc9313bf/apps/minifront/src/state/swap/dutch-auction/get-sub-auctions.ts#L68-L90

It looks pretty straightforward, but by breaking down the steps and logging to console i was able to see that the `decimalPlaces 0` call really does return a `BigNumber` that still contains decimal places.

===

TODO:
- Write a test that intentionally fails until bug is patched

**Comment by jessepinho** [comment]
do you have steps to reproduce this? exact values to enter, etc.?

**Comment by jessepinho** [comment]
Moving to blocked until we have steps to reproduce

**Comment by turbocrime** [comment]
i think this was just reproduced with a GDA using TestUsd, which iirc has a large exponent, that may be related

**Comment by grod220** [comment]
Can re-open this if the error is discovered again
