### ISSUE TITLE
Available assets should be displayed under asset selectors

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#1226]
**Is your feature request related to a problem? Please describe.**

It would be good to show both input and output balances in the trade selector.

**Describe the solution you'd like**

<img width="810" alt="Screenshot 2024-05-30 at 11 56 56 PM" src="https://github.com/penumbra-zone/web/assets/44879/155617bf-a7cf-4184-9aa2-67b3497ed808">

Move the wallet balance display under the input asset selector and add a new balance selector for the output asset.

**Comment by VanishMax** [comment]
@grod220 @hdevalence When displaying the balance of the output asset, do you expect it to be a sum of this asset from all accounts?

**Comment by grod220** [comment]
@VanishMax Our account model is a bit tricky when it comes to aspects of these input fields. However, in the past we've treated that wallet icon+amount to be the aggregate of all the accounts. Think that's ok to continue here.

**Comment by hdevalence** [comment]
We want to keep segmentation per account (so that users are always operating from a single account at a time). So the balance should be from the account the user is using.

**Comment by grod220** [comment]
In that case, @VanishMax, think it's best to open the first PR to convert all usages of that wallet+balance in minifront (ibc page, send, swap) into account-specific balances.
