### ISSUE TITLE
Onboarding numeraire selection

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1231]
The [Prax registry](https://github.com/prax-wallet/registry/blob/main/tools/compiler/src/parser.rs#L18) currently provides default numeraires. These values are important given the block processor will be referencing these as it saves swaps to the PRICING tables in indexeddb.

At the moment, there is no way for users to change these.

### Proposal

In onboarding, we add a numeraire selection step. It will be populated by choices (can select multiple) from the Prax registry. It also should not communicated as "Choose your numeraire", but use text that clearly associates this selection with the pricing their see in minifront. Something like: "In which token denomination would you prefer to price assets?"

This selection should also be featured in the extension's settings to allow them to change it. Making a change should likely require restarting the block processor (or ext services) so it pulls in the latest values and saves those to the DB. We should also likely invalidate entries in the PRICING table related to the numeraire we removed.

**Comment by Valentine1898** [comment]
We need to be careful that our onboarding flow doesn't become too complicated and lengthy
Configuring numeraire has also been discussed here https://github.com/penumbra-zone/web/issues/1063
