### ISSUE TITLE
Stop using loader functions

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#1243]
We use loaders to obtain initial data on some pages, both in minifront and in prax.

It's difficult to manage ordered/dependent execution of loaders, and loaders block page execution, which has lead to several issues, particularly in minifront where connection success is not guaranteed.

Currently, we call a function at the beginning of minifront loaders that will throw if the loader is expected to time out. This is not a good pattern.

We should examine using either a sustained zustand slice that keeps necessary data ready, or, using connect-query as intended by connectrpc.

https://connectrpc.com/docs/web/query/getting-started/

**Comment by grod220** [comment]
The outcome of https://github.com/penumbra-zone/web/issues/965 should inform how these get replaced

**Comment by vacekj** [comment]
@jessepinho I noticed Shield page is slow to load (~2 secs) - any chance this was not implemented for that specific page?

**Comment by jessepinho** [comment]
@vacekj Correct! I'm working on a branch for that now
