### ISSUE TITLE
Tx details & approval code de-dupe

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1251]
We have two areas in the codebase rendering UI from transaction views:

## 1. Tx approval dialog

<img width="395" alt="Screenshot 2024-06-04 at 2 12 11 PM" src="https://github.com/penumbra-zone/web/assets/16624263/e553aff3-d9b1-4667-a01f-1185fa20114f">

https://github.com/penumbra-zone/web/blob/c8e8d15ce1896f625452412b2d567790b0993646/apps/extension/src/state/tx-approval.ts#L84-L91

## 2. Tx details page

<img width="931" alt="Screenshot 2024-06-04 at 2 14 19 PM" src="https://github.com/penumbra-zone/web/assets/16624263/9c8ee37a-8471-40cf-9e2b-4ecd6a5dd45d">

https://github.com/penumbra-zone/web/blob/c8e8d15ce1896f625452412b2d567790b0993646/apps/minifront/src/components/tx-details/index.tsx#L32-L40

=====

They both use `TransactionViewComponent`, however, there are areas of code redundancy that can be de-duped:
- Tab usage. Both have different logic on how they handle tab selection.
- Differing views. Only the tx approval dialog has "Receiver View". This should also be available in the tx-details page.
- Utilities. `asPublicTransactionView` vs `viewFromEmptyPerspective` usage covering the same use cases.

Having one component that covers both use-cases and handle its own internal state will make this more maintainable.

**Comment by hdevalence** [comment]
I don't think we want to deduplicate these views. In fact I think it's the opposite, the approval dialog should have its own separate view component distinct from the regular transaction view, because it's security critical and may want to have different rendering.

What I suggested deduplicating was the methods for attenuating the view, but this is already tracked by an existing issue.

**Comment by TalDerei** [comment]
> but this is already tracked by an existing issue

can you link the relevant issue?

**Comment by hdevalence** [comment]
Yup, sorry, I didn't have it handy when I wrote that comment, but here it is: https://github.com/penumbra-zone/web/issues/483

**Comment by TalDerei** [comment]
> * Differing views. Only the tx approval dialog has "Receiver View". This should also be available in the tx-details page.

this is turning out to be specifically tricky because of the synchronicity of the `TxViewer` component, and our translators are asynchronous. I'm experimenting with a custom hook design.
