### ISSUE TITLE
asset selection drop down menu

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1281]
the asset drop down menu in the second screenshot should be shorter and not take up the whole screen. 

<img width="1728" alt="Screenshot 2024-06-12 at 12 57 37 AM" src="https://github.com/penumbra-zone/web/assets/70081547/e457e446-1af2-4813-8536-8c5c1002222c">

<img width="1728" alt="Screenshot 2024-06-12 at 12 57 40 AM" src="https://github.com/penumbra-zone/web/assets/70081547/d656b6e9-dc33-4ec1-8571-1cb4337fbe92">

**Comment by jessepinho** [comment]
Closing as completed

**Comment by TalDerei** [comment]
> Closing as completed

which pr was this completed in?

**Comment by jessepinho** [comment]
#1337 ([here](https://github.com/penumbra-zone/web/pull/1337/files#diff-721eda0f269d2e709e4127b52b75dd7dff4895a289b600835dafee1126cfdba3L121) and [here](https://github.com/penumbra-zone/web/pull/1337/files#diff-408444f6ef72c434d09b36f29c024b9dcd09b51e3d16facb0e444957ce55e437R75))
