### ISSUE TITLE
fix animation related to privacy warning message

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1290]
fix the height for the gas calculation, so only one jump happens

https://github.com/penumbra-zone/web/assets/70081547/d19e4b8a-135e-4a20-bee8-e8c40d3a99b5

**Comment by vacekj** [comment]
I see three simple ways to resolve this. 
A) Set a fixed height on the Fee tier section - this looks odd to me with the empty space
B) Move the fee value next to the fee tier switch, and remove the gas icon, as we're not calling it gas anyway (at least for now).
C) Always display the value, but default to zero when we don't know the fee yet.


![Image](https://github.com/penumbra-zone/web/assets/10381200/a8c9db89-ba80-4f14-91aa-e34a34fa0fd0)



![Image](https://github.com/penumbra-zone/web/assets/10381200/9f3cabb5-67b8-4584-9064-17dc875b0303)



![Image](https://github.com/penumbra-zone/web/assets/10381200/9eb69580-9081-4fb6-b227-13e026fa76d7)




I included screenshots for all cases. My personal preference is B, C, A in this order.

Curious to hear your thoughts @penumbra-zone/web-reviewers

**Comment by vacekj** [comment]
after more info from Tal, the right way to proceed is to make both of the dialogs appear at the same time, instead of changing the height of the fee part directly.

**Comment by TalDerei** [comment]
@VanishMax can you sanity-check the issue accurately captures the original intention for the suggestion you made?

**Comment by VanishMax** [comment]
@vacekj thanks for the ideas with detailed screenshots. I believe the C options suits our needs – displaying the empty value for a fraction of a second is, in my opinion, better than having multiple jumps and worsening the cumulative layout shift (CLS). The option B looks goon on the screenshot but in many cases would not fit into the view

**Comment by vacekj** [comment]
Going for option C here, debugging why Fee doesn't also contain the asssetId.

**Comment by TalDerei** [comment]
> debugging why Fee doesn't also contain the asssetId.

can you elaborate?

**Comment by vacekj** [comment]
@TalDerei I'm going with option C, which displays a zero value before the actual fee is loaded, avoiding any CLS in the fee dialog. While implementing this, I realized that the `fee` param in GasFee (`gas-fee.tsx:29`) doesn't contain the assetId, just the amount. This leads to the fee display always defaulting to the stakingToken, in our case UM, and not the token that the fee is paid in (afaik after diggind deep into this with @grod220 ).

**Comment by TalDerei** [comment]
thanks for taking this on!
