### ISSUE TITLE
use fewer distinct build processes

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#1301]
we currently publish packages with six different build processes

1. no build
2. tsc
3. vite lib mode with dts plugin
4. vite lib mode plus tsc
5. tsup
6. wasm-pack plus tsc

we should reduce this number

**Comment by turbocrime** [comment]
not building typescript seems to create issues with consumers. this might improve if our tsconfigs did not ship broken

**Comment by turbocrime** [comment]
#1305 aligns builds to tsup, except the wasm package

**Comment by vacekj** [comment]
Big up for this PR, reducing complexity is vitally important in a large project like this.
