### ISSUE TITLE
Confirm additional tx commitments 

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1308]
There is a todo in the block processor:

https://github.com/penumbra-zone/web/blob/1ee18e0e6642766a788835bdc3d685e21bfe3d52/packages/query/src/block-processor.ts#L351

Confirm whether output, swap, & swapClaim are the only actions with commitments. If there are more, add to the switch case. Else, if this is it, create a PR to remove the todo.

**Comment by TalDerei** [comment]
referencing https://github.com/penumbra-zone/web/pull/1041/files, these are the only actions with state commitments. We can remove the comment
