### ISSUE TITLE
fix broken "max" button 

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1313]
References https://github.com/penumbra-zone/web/pull/1268#issuecomment-2164609477. Currently, the "max" functionality implemented in https://github.com/penumbra-zone/web/pull/1151 is broken in the context of non-zero gas fees. During transaction creation, the planner specifies outputs and fills in spends to balance the transaction, subtracting fees from the _input_. If the user attempts to spend their _entire_ balance, they don't have any additional funds to pay for fees. Instead, we want to modify the planner request to spend all the available notes, and instead subtract fees from the _output_. 

https://github.com/penumbra-zone/penumbra/pull/4615 was a necessary proto change towards that. 

cc @grod220

**Comment by grod220** [comment]
This is only an issue if the user is trying to spend their max amount of UM and they have no other token right?

**Comment by TalDerei** [comment]
![Screenshot 2024-06-13 at 12 37 10 PM](https://github.com/penumbra-zone/web/assets/70081547/f6677d73-1ff9-40d9-855c-98835fb83daf)

**Comment by Valentine1898** [comment]
> This is only an issue if the user is trying to spend their max amount of UM
Not just UM, but other tokens as well if used as an alternative fee token

> and they have no other token
It doesn't matter, if the user has UM, then the alternative fee token will not be used

**Comment by hdevalence** [comment]
We want to avoid a situation where a user has to manually decrease the amount slightly to leave a bit left over for gas, like on ethereum, we have the technology to deliver a better UX here so we should try to do so. It will require tracking some extra state in the send dialog (since we effectively want to secretly track an `isSendingMax` bool and branch on it).

**Comment by conorsch** [comment]
The related Planner changes in https://github.com/penumbra-zone/penumbra/pull/4615 shipped as part of `v0.77.4`, so this work should now be unblocked.

**Comment by TalDerei** [comment]
are we intending to extend the max functionality to swaps and delegations as well?
