### ISSUE TITLE
IBC out from UI: Part 1

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#132]
The wasm crate now supports building an IBC transaction. This task is implementing the IBC out in the UI + service worker.

Should re-enable IBC tab on /send page

**Comment by conorsch** [comment]
We're working on a point release of ibc-types later this week to unblock the integration. 

Also, be aware that we just merged https://github.com/penumbra-zone/penumbra/pull/3284 which renames some IBC proto fields. These changes will be live on preview momentarily, and land on testnet as of 64.
