### ISSUE TITLE
ES module warnings

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1323]
<img width="1481" alt="Screenshot 2024-06-18 at 1 36 40 AM" src="https://github.com/penumbra-zone/web/assets/70081547/7809fa5a-6b00-4031-8d86-9b3e8d3ac3d1">

**Comment by turbocrime** [comment]
this is an upstream eslint issue, may be a plugin issue. seems to have no effect. closing as i expect it to resolve as plugins update
