### ISSUE TITLE
fix packing packages

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1324]
If you execute `pnpm install` and `sh pack-public.sh`, it will fail to pack all the packages

<img width="1404" alt="Screenshot 2024-06-18 at 1 38 42 AM" src="https://github.com/penumbra-zone/web/assets/70081547/cab3a6f0-3022-43a8-8db8-4ce3c6a6e1bc">
 
Only running `pnpm all-check` and then `sh pack-public.sh` works. 

<img width="803" alt="Screenshot 2024-06-18 at 1 40 44 AM" src="https://github.com/penumbra-zone/web/assets/70081547/a481f783-c926-4841-b198-a3efeff69ba7">

**Comment by turbocrime** [comment]
this is because it hasn't been compiled. this is fine, the pack-public script isn't intended to be part of a normal workflow.
