### ISSUE TITLE
Max/Min input design

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1327]
At the moment, it's not clear that these are editable fields:

<img width="518" alt="Screenshot 2024-06-18 at 12 01 42 PM" src="https://github.com/penumbra-zone/web/assets/16624263/c9b571da-78c2-4186-a239-39b3679dc21a">

We should enclose them in a box (that stands out a bit from the background), so it's clearer for users.

**Comment by TalDerei** [comment]
duplicate of https://github.com/penumbra-zone/web/issues/1164

**Comment by grod220** [comment]
Ah! Cool cool
