### ISSUE TITLE
Add coin icons to assets

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#133]
<img width="200" alt="Screenshot 2023-10-25 at 9 24 09 PM" src="https://github.com/penumbra-zone/web/assets/16624263/1976c45f-726a-41ec-93ec-a546ecfa9115">

At the moment, it is not showing any asset icons.

**Comment by zpoken** [comment]
https://github.com/penumbra-zone/web/pull/238#discussion_r1395690530

**Comment by grod220** [comment]
Can pull from official chain registry. We probably don't need to download them to our repo and can just reference the github links.

https://github.com/cosmos/chain-registry/tree/master/osmosis/images

**Comment by Vadim121197** [comment]
![Image](https://github.com/penumbra-zone/web/assets/52686175/a8bffade-1f24-4afb-9c1a-48e864681fa4)


@grod220

**Comment by Vadim121197** [comment]
![Image](https://github.com/penumbra-zone/web/assets/52686175/f6de2f16-8992-4daa-8df8-4b70bfbb1a14)

**Comment by grod220** [comment]
A few things:
- Those colors are not quite the correct color palette to the Penumbra brand. They should be less saturated and more muted.
- How are those being generated? Are you using a hash-to-color algorithm? 
- What is the font of the character? Is that a penumbra font?
- Test usd should have the usdc logo from the registry
- Penumbra should have the same logo as the favicon

**Comment by Vadim121197** [comment]
2. I use tinycolor2 
3. yes
4. link from regisrty include network icon
<img width="944" alt="Знімок екрана 2023-11-27 о 11 01 17" src="https://github.com/penumbra-zone/web/assets/52686175/189eb27d-9167-43b3-b075-f6dc8b1da451">

**Comment by grod220** [comment]
Looks good to me 👍

**Comment by grod220** [comment]
The way @Valentine1898 does it. You fork this repo, make changes to a branch and open the PR from the fork to this repo.

**Comment by Valentine1898** [comment]
In web repo I can push directly because I was added to the penumbra organization. Only in penumbra repo I push through the fork

**Comment by Vadim121197** [comment]
I cann`t add Reviewers
![Image](https://github.com/penumbra-zone/web/assets/52686175/34a7ee68-b175-4eae-a3f6-b9abc478d401)

**Comment by grod220** [comment]
I reviewed
