### ISSUE TITLE
needs idb version bump

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#1332]
idb schema changes require an idb version bump

https://github.com/penumbra-zone/web/pull/1268

https://github.com/penumbra-zone/web/blame/f5c511e08b5fbf614def6fa499a14c37e769c2e8/packages/storage/src/indexed-db/index.ts#L105-L109

probably need to start writing migrations as well

**Comment by Valentine1898** [comment]
https://github.com/penumbra-zone/web/blob/733d62ac7020dc99bb0b7618870593e5d1884fa8/packages/storage/src/indexed-db/config.ts#L1-L5
@TalDerei moved `IDB_VERSION` to storage package, which seems correct.  But the issue is that the value passed from extension is still used
