### ISSUE TITLE
Minifront sometimes fails to show frontend onboarding page

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#1344]
if the transactions path is navigated to on an unconnected minifront, instead of showing an onboarding page to the user, minifront shows a broken page, and eventually a transport timeout

https://localhost:5173/#/dashboard/transactions

<img width="1280" alt="Screen Shot 2024-06-21 at 17 55 08" src="https://github.com/penumbra-zone/web/assets/134443988/74d19ee0-0562-4159-a0b1-03533d70f1f2">

i believe this is related to loader work @jessepinho because that's where connection checks were performed

**Comment by TalDerei** [comment]
can confirm I've been noticing this multiple times as well
