### ISSUE TITLE
Block sync error

### ISSUE THREAD

**Issue by grepsuzette** [penumbra-zone/web#1350]
**Describe the bug**

Synchronization appears to fail here. Repeatedly for 10 or so attemps.
It's a rather slow connection behind a socks5 proxy. Brave browser, Linux.

After it syncs for a minute or so (`Loading sync state...`, `Syncing blocks... 7 minutes, 2 seconds...`), 

then it fails with `Block sync error: DataCloneError: An object could not be cloned.`

Or, sometimes, with `Block sync error: ConnectError: [unknown] Failed to fetch`. 

At least the previous blocks appear to be kept in memory.
Strangely I don't see an associated error in the browser console.

Anyway just letting you know.

![penumbra](https://github.com/penumbra-zone/web/assets/350354/2aa260f8-1461-40c9-a260-4971fdb5fccf)

**Comment by grod220** [comment]
Thanks for this report! We've noticed some issues with https://grpc.testnet.penumbra.zone/ recently. Any chance you could try resyncing with https://testnet.penumbra.rpc.starlingcyber.net/ (can change your rpc in the settings and reset the cache there as well) and see if you run into the same error?

**Comment by jessepinho** [comment]
cc @turbocrime

**Comment by grepsuzette** [comment]
it works for me now, btw. Guess can close.
