### ISSUE TITLE
Sync modal 

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1377]
Sync status is critical to the user's experience with Penumbra & minifront. When the sync is not current, their balances could be incorrect & there could be problems issuing a transaction. Minifront should implement a full-screen modal to communicate sync status in a more in-your-face way. Details:

- If sync is up-to-date, show the UI as expected
- If sync is not up-to-date, have a full-screen modal (blur background?), that gives messaging for current status.
  - Should be dismissible to allow user to continue if they choose
  - Should have messaging for what syncing is doing
  - Should give a % status, "50.2% synced" w/ blockheight
  - Should re-use airdrop network+computer graphics to communicate data is flowing. Ask @smmhrdmn (Sam) for this asset.

**Comment by smmhrdmn** [comment]
Here is the [file](https://www.figma.com/design/H5TPKVz1Um7TzVefwYent4/Mini-Front----Miscellaneous?node-id=201-1914&t=Lhrgc4tDtCfKRAnb-1), [prototype](https://www.figma.com/proto/H5TPKVz1Um7TzVefwYent4/Mini-Front----Miscellaneous?page-id=201%3A1914&node-id=4002-1035&viewport=-18123%2C-27973%2C0.64&t=st1RXeLcnZO5uuEQ-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=4002%3A1035&show-proto-sidebar=1), and [animation](https://app.lottiefiles.com/share/2cef754c-3fdc-421a-b8eb-406eaecff5d0)! Lmk if you have any comments or suggestions for copy.
