### ISSUE TITLE
Silent error w/ precision

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1389]
On the send page, if you attempt to send `.0000001 penumbra`, nothing will happen. There will not be a toast, modal, or any kind of UI response. The UI is apparently swallowing the error. This transaction should not be possible given .0000001 penumbra = .1 upenumbra, which is not valid given the highest precision denom is not divisible.

We should see what is swallowing the error and the UI should give some kind of indication when their amount selection is erroneous.

<img width="515" alt="Screenshot 2024-07-01 at 3 46 05 PM" src="https://github.com/penumbra-zone/web/assets/16624263/cf1056f3-fa8d-427e-b1ad-f58154d4d927">

**Comment by Valentine1898** [comment]
duplicates https://github.com/penumbra-zone/web/issues/1139

**Comment by grod220** [comment]
Ah, you frequently beat me to it @Valentine1898  😅
