### ISSUE TITLE
multi-asset fee bug

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1397]
for swaps / auctions, figure out why the multi-asset fees (enabled when the user does not have native **UM** tokens) sometimes works for swapping one asset into another, but not vice versa

https://github.com/penumbra-zone/web/assets/70081547/eef7ed41-ec24-4e31-8df7-7cb1f2164358

https://github.com/penumbra-zone/web/assets/70081547/32428704-5aaf-443a-a780-d0d20b7a8a2b

**Comment by Valentine1898** [comment]
related to https://github.com/penumbra-zone/web/issues/1310 
The native token's gas prices are used each time, so for exponent tokens with an exponent less than UM (e.g. CUBE or PIZZA), the planner attempts to spend a large amount as a fee

**Comment by TalDerei** [comment]
closing in favor of #1413
