### ISSUE TITLE
more multi-asset fee bugs 

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1404]
- [ ] investigate why sending some tokens (for instance pizza) display insufficient note balance. 

<img width="736" alt="Screenshot 2024-07-02 at 2 46 44 PM" src="https://github.com/penumbra-zone/web/assets/70081547/a69bb321-b2be-4ed9-bc0a-c436a3f58852">

-----------------------------------------------------------------------------------------------------------------------------------

- [ ] investigate why testUSD shows a zero fee balance when other fee tokens display a non-zero fee amount

<img width="1728" alt="Screenshot 2024-07-02 at 2 44 37 PM" src="https://github.com/penumbra-zone/web/assets/70081547/31dd5411-be00-4e33-8c2a-a247c68fe032">

-----------------------------------------------------------------------------------------------------------------------------------

- [ ] handle cases where some tokens (delegation tokens) have no asset metadata attached to them, which breaks the extension

<img width="512" alt="You can provide a way better UX than this when your app throws" src="https://github.com/penumbra-zone/web/assets/70081547/44794dd1-e34b-4c42-8f45-a44ec5917506">

**Comment by Valentine1898** [comment]
https://github.com/penumbra-zone/web/issues/1397#issuecomment-2207117214

**Comment by TalDerei** [comment]
closing in favor of #1413
