### ISSUE TITLE
long confirmation times and failing to populate transaction list

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1418]
I've noticed some strange behavior during long confirmation times. A transaction will randomly silently pass (transfers funds between addresses) but will not display success or appear in the transactions list. This seems somewhat concerning. cc @grod220 @Valentine1898 have you noticed this before?

https://github.com/penumbra-zone/web/assets/70081547/ccc04ac3-4fc0-40fb-9abb-80b10582712f

**Comment by Valentine1898** [comment]
Is this the result of unstable RPC? For example, `TransactionsByHeight` may fail to return a result or return it for a very long time (infinitely pending)

**Comment by Valentine1898** [comment]
I have not encountered this problem specifically, but I have observed that when RPC is unstable, some requests hang forever during sync

**Comment by TalDerei** [comment]
> Is this the result of unstable RPC

this was observed last night when the rpc was stable https://grafana.testnet.penumbra.zone/d/Uq0N5097k/client-info?orgId=1&from=now-12h&to=now

**Comment by TalDerei** [comment]
My intuition also suggests this issue is RPC-related, as it seems to work fine on another less used RPC node. I'll keep this issue open as a record.

**Comment by TalDerei** [comment]
can't replicate, closing for now
