### ISSUE TITLE
swap and auction estimations fail

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1423]
I've been getting this estimation error when trying to perform swaps / auctions.

<img width="1728" alt="Screenshot 2024-07-04 at 10 11 31 PM" src="https://github.com/penumbra-zone/web/assets/70081547/914962cd-1bd6-463e-88b9-83a55f6604f2">

**Comment by jessepinho** [comment]
Hm, I'm actually getting HTTP 412s (Precondition Failed). @TalDerei , which RPC are you using?

**Comment by TalDerei** [comment]
@jessepinho I don't recall, but it could be related to the fact that the RPC _might not_ support simulation. In this context, it may not be clear to the user how much they are swapping if they need to manually inspect the transaction approval dialogue for that information.

**Comment by turbocrime** [comment]
412 precondition failed likely means no price data is available to create an estimation. this will succeed if you make at least one trade.

408 unimplemented likely means the node operator has not run `pd` with `--enable-expensive-rpc`

**Comment by turbocrime** [comment]
i encountered both of these today and i believe they were visible in console, will take another look at error propagation soon

**Comment by jessepinho** [comment]
> 408 unimplemented likely means the node operator has not run `pd` with `--enable-expensive-rpc`

Ah — can production RPC nodes run `pd` _without_ that flag? If so, sounds like we need to handle that case.

**Comment by hdevalence** [comment]
The released version of `pd` makes that flag a no-op, but yeah, error handling would be good.

**Comment by TalDerei** [comment]
> Ah — can production RPC nodes run `pd` _without_ that flag? If so, sounds like we need to handle that case.

<img width="1728" alt="Screenshot 2024-07-17 at 6 17 23 AM" src="https://github.com/user-attachments/assets/27977d53-b26c-4449-afe4-d30929d98fc6">

<img width="710" alt="Screenshot 2024-07-17 at 6 18 56 AM" src="https://github.com/user-attachments/assets/a89cec9c-799a-448a-8f34-bbc88f47286f">

**Comment by TalDerei** [comment]
closing as outdated per discussion during the weekly sync.
