### ISSUE TITLE
transaction table blocked by sync process

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1428]
Noticing that sync prevents users from viewing their **partial** transaction graph for an unusually long time into the syncing process. Investigate what might be causing this delay.

<img width="1728" alt="Screenshot 2024-07-05 at 7 50 29 AM" src="https://github.com/penumbra-zone/web/assets/70081547/c85612b1-9e77-449d-b400-fabd9023480a">

**Comment by Valentine1898** [comment]
I can't reproduce this, I see a list of transactions as they are detected during sync (if I refresh the page)

**Comment by TalDerei** [comment]
> I can't reproduce this, I see a list of transactions as they are detected during sync (if I refresh the page)

this was reproducible when the chain state was longer with more transaction history.

**Comment by Valentine1898** [comment]
The bug is not reproduced on a longer state chain and with more transactions
Transactions are displayed correctly during sync


https://github.com/user-attachments/assets/d64f9f5d-5347-461a-b549-493d1aad4992
