### ISSUE TITLE
HTML Page titles

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#143]
Each route should have these

**Comment by zpoken** [comment]
what is the title format? Penumbra | Send for example

**Comment by grod220** [comment]
Yes, that's fine

**Comment by zpoken** [comment]
+ description - `For use in interacting with the Penumbra blockchain`

**Comment by grod220** [comment]
No, every page should have a description of what the page is about

**Comment by zpoken** [comment]
![Image](https://github.com/penumbra-zone/web/assets/82594516/336c7e02-ae50-497c-bcfa-c0b865ef08a1)


use this?

**Comment by grod220** [comment]
Sure

**Comment by zpoken** [comment]
Can I combine small issues into 1 PR?

**Comment by grod220** [comment]
No, they should be separate PRs
