### ISSUE TITLE
penumbra logo glitching during sync

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1438]
syncing causes the penumbra graphics logo in the top left to glitch

https://github.com/penumbra-zone/web/assets/70081547/117e2eeb-b645-4c76-b0c8-04c9e463d1e5

**Comment by turbocrime** [comment]
this is probably related to z-layering again. it might be worth defining a clip path for the logo. is the issue. still present when the testnet banner is absent?

**Comment by TalDerei** [comment]
> this is probably related to z-layering again. it might be worth defining a clip path for the logo. is the issue. still present when the testnet banner is absent?

issue is still present without the testnet banner

**Comment by TalDerei** [comment]
@VanishMax, are we expecting the logo to still appear in minifront v2?

**Comment by VanishMax** [comment]
@TalDerei no, in v2 the only logo we'll display is "PENUMBRA" without the circles
