### ISSUE TITLE
Implement offscreen API method [web workers]

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#146]
We need a way to spawn web workers in the service worker. This requires using the offscreen api to open a separate window, sending it messages, and that window spawning web workers.

See https://github.com/penumbra-zone/web/tree/offscreen-web-worker for an example.

This will allow us to be able to use multi-threading (for building/proving) in the extension context.

**Comment by TalDerei** [comment]
1. Get WASM build + proving key methods to work in current service worker. 
2. Get the web-worker to work in a service worker context (launching invisible windows). 
3. Get the build methods to work in the web-worker.
