### ISSUE TITLE
Tabs should be routes

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#149]
Currently there are tabs on `/dashboard` (assets/transactions) and `/send` (send/receive). When you click on them, the URL route does not change. 

For instance, when you click on the `assets` tab, the url should show: `/dashboard/assets`. Each one of these tabs should be represented in this kind of way.

**Comment by zpoken** [comment]
should be `/send`, `/receive/`, `/dashboard/assets `and `/dashboard/transactions`?

**Comment by zpoken** [comment]
maybe it better - /?tab=send?

**Comment by zpoken** [comment]
because if we follow your suggestion, we need to create new pages

**Comment by grod220** [comment]
what's wrong with creating new pages?

**Comment by zpoken** [comment]
It's okay, it's just that my solution is suitable for our code, and yours requires rewriting the code

**Comment by grod220** [comment]
We should do what's best and not what's the easiest. Please proceed with creating new pages.

**Comment by zpoken** [comment]
then I'm interested to know why this solution is better) it's for myself, because I don't see any difference now

**Comment by grod220** [comment]
The content is best represented as a page and not as a url query param. It looks better when users share this link.

**Comment by zpoken** [comment]
we added tabs to the design of the page, and it would be correct to create /send/send and /send/receive (or my solution) instead of /send and /receive! or delete tabs and create another link at header

**Comment by grod220** [comment]
I don't understand your solution, please rephrase for clarity

**Comment by zpoken** [comment]
guided by our design, the tabs should not take us to another page, they should leave us on the same page, where only the content will change, if we do it on separate pages, then all the content will be re-rendered! and now instead of 2 pages we will have 4, in the future it will grow depending on the number of tabs (see there - https://wallet.keplr.app/?tab=overview)

**Comment by grod220** [comment]
Not sure what you mean about content being re-rendered. Nextjs hydrates as a single page app. When React takes over, it intelligently does diffs and only re-renders new content on the page.

Data fetching on the other hand would be re-fetched. However, this isn't an issue with the page, but how we are currently handling data fetching in hooks versus an intelligent cache-aware data store.

The example you provided is a good example where their link is worse than `https://wallet.keplr.app/overview`.

**Comment by zpoken** [comment]
then / should redirect us /asset
