### ISSUE TITLE
create faq pages

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1556]
drawing inspiration from the [Payy Network](https://docs.payy.network/), they currently provide dedicated FAQs for both the [wallet](https://docs.payy.network/support/payy-wallet-faq) and the [network](https://docs.payy.network/support/payy-network-faq). The wallet settings include a direct link to the FAQ, a telegram link to ask questions, and importantly, a feature to share diagnostics with the development team.

we plan to create dedicated FAQs for both the prax wallet and the network. These FAQs will be written in simple language for easy understanding and added to our [Nextra guide](https://guide.penumbra.zone/).

<img width="695" alt="Screenshot 2024-07-23 at 8 00 31 AM" src="https://github.com/user-attachments/assets/017466c0-58b3-47ee-87fd-bc1b428507fe">

<img width="693" alt="Screenshot 2024-07-23 at 8 00 37 AM" src="https://github.com/user-attachments/assets/34958daa-1080-4129-a7da-9bf97f5d363a">

<img width="542" alt="Screenshot 2024-07-23 at 8 00 04 AM" src="https://github.com/user-attachments/assets/ef1d8674-322a-470c-9a5b-97a1249444f9">

<img width="545" alt="Screenshot 2024-07-23 at 8 00 15 AM" src="https://github.com/user-attachments/assets/64e82b7d-555e-4891-8984-e631b471f0a7">

**Comment by grod220** [comment]
This should exist in https://github.com/penumbra-zone/guide no?

**Comment by TalDerei** [comment]
> This should exist in https://github.com/penumbra-zone/guide no?

good point, will move 👍
