### ISSUE TITLE
clarify privacy properties of the protocol

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1557]
As an extension of https://github.com/penumbra-zone/web/issues/1548, we should aim to _transparently_ and _concisely_ communicate the privacy features we currently support (and plan to support in the future). The privacy properties of the protocol can be confusing since they're not immediately clear. Besides refactoring our [guide](https://guide.penumbra.zone/), it’s not entirely clear what the best way to communicate this is. See https://github.com/penumbra-zone/penumbra/pull/4695 for relevant scope.

-----------------------------------------------------------------------------------------------------------------------------------

**1. Sealed-Bid Batch Swaps:** currently, batch swaps execute all intents within a block and the assets being swapped are public. "Sealed-bid" batch swaps would protect the privacy of the input assets by not revealing them publicly.

**2. Flow Encryption:** Swap amounts are currently public. "Flow encryption" would hide these values and offer front-running protection by encrypting individual swap amounts. Validators aggregate these encrypted values, decrypt the batch totals, and reveal them publicly. This ensures that individual swap amounts remain private.

In V2, these features would allow only the batch totals to be publicly revealed while keeping the individual assets and values in a swap private.

cc @grod220

**Comment by grod220** [comment]
Yes, please. Does this more properly belong in https://github.com/penumbra-zone/guide though?

**Comment by TalDerei** [comment]
> Yes, please. Does this more properly belong in https://github.com/penumbra-zone/guide though?

good point, will move 👍
