### ISSUE TITLE
tx view visibility settings are incorrectly ordered

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#1564]
**Describe the bug**

<img width="718" alt="Screenshot 2024-07-25 at 1 47 07 PM" src="https://github.com/user-attachments/assets/030bbd8e-0ea5-46a6-a02b-2c09d3f206ff">

should go from most visibility to least visibility: "your view" / "rx view" / "public view"

**Comment by TalDerei** [comment]
closed as previously resolved
