### ISSUE TITLE
Error when trying to spend max and alternative fees

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#1592]
**Describe the bug**
You will get an error if you try to spend the maximum balance using an alternative fee asset
At the same time using native fee asset you can spend all your native tokens

**Expected behavior**
It is expected that the user can max spend when using alternative fee asset 

**Screenshots**
<img width="1354" alt="image" src="https://github.com/user-attachments/assets/48ae2102-8cbc-4c06-9ade-64ee52a73b01">

Additional context
The error “ConnectError: [unknown] Failed to retrieve or ran out of notes for asset” is not meaningful to users

**Comment by TalDerei** [comment]
https://github.com/user-attachments/assets/55cec997-045f-4d8c-9f41-c9d817ff191d
