### ISSUE TITLE
Accounts on the assets page are not ordered

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#1593]
**Describe the bug**
Accounts on the assets page are not ordered
For some reason Account #8 is higher than Accounts #2, #6, #7

**Expected behavior**
Accounts should be sorted in ascending order of their address indexes 

**Screenshots**

<img width="823" alt="image" src="https://github.com/user-attachments/assets/61214bd4-baf4-4db5-b6b4-7d72c80f55c6">

**Comment by turbocrime** [comment]
it appears they are in lexical order of address
