### ISSUE TITLE
The NonNativeFeeWarning  is never displayed 

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#1598]
**Describe the bug**
The [NonNativeFeeWarning](https://github.com/penumbra-zone/web/blob/6171ff97bc69262ae7a7e19c1c00ff36df6a0eef/apps/minifront/src/components/shared/non-native-fee-warning.tsx#L33)  is never displayed 

**Screenshots**
<img width="422" alt="image" src="https://github.com/user-attachments/assets/1c39dc7e-3471-4449-8097-667e6e692526">

**Comment by TalDerei** [comment]
think this may be a non-issue? mainnet is properly displaying the warning

https://github.com/user-attachments/assets/55235788-cad4-4a53-af85-21a42c3e0b3f

**Comment by TalDerei** [comment]
although we’re simulating alternative gas fees with `extractAltFee`, we still have a UM balance that the frontend is detecting.

**Comment by Valentine1898** [comment]
> think this may be a non-issue? mainnet is properly displaying the warning
> 
>  Screen.Recording.2024-07-30.at.2.35.58.PM.mov

I think it's still an issue. This condition doesn't consider source and checks for a native token on all accounts

https://github.com/penumbra-zone/web/blob/6171ff97bc69262ae7a7e19c1c00ff36df6a0eef/apps/minifront/src/components/shared/non-native-fee-warning.tsx#L20-L22

**Comment by TalDerei** [comment]
> I think it's still an issue. This condition doesn't consider source and checks for a native token on all accounts

noticed this when logging `balancesResponses`
