### ISSUE TITLE
Wasm planner throws on undefined gas fees

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#1602]
**Describe the bug**
Wasm planner throws undefined gas fees as an error

https://github.com/penumbra-zone/web/blob/d18f2d0cfbe8977dece1db5babe0b5616dc6eb9c/packages/wasm/crate/src/planner.rs#L204-L208

**To Reproduce**

1. Use a chain with no gas fees
2. Plan a transaction with wasm that executes plan_transaction_inner
3. Wasm throws because gas prices are not available

**Expected behavior**
Undefined means zero. Wasm should use the default gas fee (zero) and successfully plan the transaction.

**Comment by turbocrime** [comment]
### action item

refactor wasm planner to require a parameter for this information, rather than performing independent idb access

**Comment by grod220** [comment]
What's the issue with wasm grabbing the gas prices versus typescript grabbing them and passing them to wasm?
