### ISSUE TITLE
hasTokenBalance should ignore randomizer and use index only 

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#1604]
**Describe the bug**
IBC assets at the default ephemeral address, and when trying to create a transaction c IBC will be passed the source that contains the randomizer

<img width="1333" alt="image" src="https://github.com/user-attachments/assets/e50888b0-a83b-47a9-a5e3-2295080bb74a">

**Comment by grod220** [comment]
Jumping on this asap

**Comment by Valentine1898** [comment]
@grod220 @TalDerei 
we can fix this in either extension or minifront (just don't pass the randomizer to TPR) 
Do I understand correctly that we can deliver the fix in minifront faster?
