### ISSUE TITLE
Fill in Receive UI in "Send" page

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#162]
The `/send` page has a toggle between "send" and "receive".  The Receive side isn't filled in yet.

I think the best way to do it is to reuse some components from the extension popup and from the send tab, combining these two elements:

<img width="383" alt="Screen Shot 2023-10-28 at 1 24 14 PM" src="https://github.com/penumbra-zone/web/assets/44879/9f84c1a4-1e76-4548-9491-831fd2792321">
<img width="382" alt="Screen Shot 2023-10-28 at 1 24 39 PM" src="https://github.com/penumbra-zone/web/assets/44879/d40e9c6e-c27d-4804-97a5-1d797c065d26">

The behavior of the toggle should be as follows:

- When the toggle is switched to "off", the displayed address should be set to the default address for the selected account, using [`AddressByIndex`](https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.view.v1alpha1#penumbra.view.v1alpha1.ViewProtocolService.AddressByIndex).
- When the toggle is switched to "on", the displayed address should be set to a fresh ephemeral address for the selected account, using [`EphemeralAddress`](https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.view.v1alpha1#penumbra.view.v1alpha1.ViewProtocolService.EphemeralAddress)

This means that a user can generate fresh ephemeral addresses by flipping the toggle on and off repeatedly, so we don't have to have a separate UI for that.

Along the way, we'll probably want to extract the address picker into a common UI component. One thing to consider when doing that is whether there's a way to allow users to input a numeric account (so they don't have to click through left and right buttons a zillion times), but without blowing up the complexity of the UI.  One idea in that regard could be to have the "Address #X" text secretly be an input field, so that clicking on it allows editing and typing in a number directly. This way we retain the simplicity of clicking through a few accounts while allowing users to specify arbitrary account indexes.

**Comment by hdevalence** [comment]
dupe of #142

**Comment by turbocrime** [comment]
confirmed in meeting:

send form address selection component indicates address index of the transaction's funding source. the ui may need to use this address index to query available funds.

this selected address index becomes the `source` field of `TransactionPlannerRequest`. fee change return address will match the address indicated by this index, in our implementation.

the `sender` field of `MemoPlaintext` provided to `TransactionPlannerRequest` in our implementation will match the address indicated by this index, or be an ephemeral address generated from the source index.

**Comment by turbocrime** [comment]
#180 was obsoleted and work needs to restart on this

should involve address selection component #217 and effective address selection is blocked by penumbra-zone/penumbra#3333

**Comment by Valentine1898** [comment]
unblocked, penumbra-zone/penumbra#3333 merged 

Basically all changes here are made to the webapp package, and this can be done in parallel with https://github.com/penumbra-zone/web/issues/243
