### ISSUE TITLE
stream assets during sync

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1628]
suitable follow-up work referencing https://github.com/penumbra-zone/web/pull/1625#issuecomment-2265456799

**Comment by TalDerei** [comment]
> Member

oh it's not a streaming rpc?

**Comment by TalDerei** [comment]
> Is that possible? It seems to me that balance RPC cannot stream balance updates

oh it's not a streaming rpc?

**Comment by Valentine1898** [comment]
> > Is that possible? It seems to me that balance RPC cannot stream balance updates
> 
> oh it's not a streaming rpc?

It is a streaming rpc, but it does not implement streaming updates, only streaming the state that was at the time of the request
