### ISSUE TITLE
Block processor fails to set gas prices from a compact block

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#1636]
https://github.com/penumbra-zone/web/blob/69b083755e83a5d9dc5465345df7981293fb0b1b/packages/query/src/block-processor.ts#L171-L178

When the `assetId` in `compactBlock.gasPrices` is set to `undefined` (not absent, but a present value of undefined), spreading it after attaching an `assetId` to the object will clobber the `assetId` which was just set.

But, the idb table requires an asset id for the keypath. So this `setGasPrices` call will throw an error and prevent sync from progressing.

<img width="1049" alt="Screenshot 2024-08-02 at 17 14 06" src="https://github.com/user-attachments/assets/f307ae73-d8cf-442f-9523-3c28ad2c0755">

I believe this is at the root of some of the 'long sync time' issues reported by users.

**Comment by grod220** [comment]
Yep worth adjusting the logic. However, no user should be encountering this as all blocks that contain new gas prices have included an assetId.

**Comment by TalDerei** [comment]
still unclear if this can be closed
