### ISSUE TITLE
Display a warning if the minifront is outdated

### ISSUE THREAD

**Issue by VanishMax** [penumbra-zone/web#1645]
**Is your feature request related to a problem? Please describe.**

Users should know if the minifront version they are using is up-to-date. This could happen if a deployer stops updating the minifront. In this case, users should be prompted to select another frontend or message the deployer asking to update the version.

**Describe the solution you'd like**

1. Communicate with the design team to sketch a warning dialog and probably the footer updates
3. Use Vite to bundle the minifront version from `package.json` as an environment variable
4. On initial load, the frontend should query github to get the latest releases published for minifront
5. If the latest release is a one major version higher than bundled & the current frontend is > 1 week since the update, the frontend shows a banner alert to use a more fresh frontend from the registry
6. Update the registry package to handle this logic for consumers

**Comment by hdevalence** [comment]
This is already accomplished by the version field in the footer, which provides a way for users to understand which version they are using. Old versions should continue to work.
