### ISSUE TITLE
Re-enable spend max feature 

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1660]
### **Context**

https://github.com/penumbra-zone/web/pull/1612 and https://github.com/penumbra-zone/web/pull/1611 resulted in a feature regression that should be re-enabled and properly implemented. Below is a high-level product plan for achieving this.

###  **Updates required to enable send max**
- check user flows
   - test a set of user flows associated with the feature to ensure all use cases are covered
- enable the feature in the transaction planner request within minifront
- fix the feature in the wasm planner
   - ensure that the remaining balance from the fee note is returned to the originating address of the transaction
   
cc @grod220

**Comment by TalDerei** [comment]
Currently, we leverage our multi-fee system to support maximum sends in certain scenarios. Consider the following cases:

----------------------------------------------------------------------------------------------------------------------------
## **Active Functionality**:

These are constructed using an `output` transaction planner request.

**1. Sending an alternative asset (GM) while paying fees with the native asset (UM).**

<img width="531" alt="Screenshot 2024-08-14 at 8 47 55 AM" src="https://github.com/user-attachments/assets/1dcd2729-2a7b-47ff-9b81-c5a81009f272">
<img width="1728" alt="Screenshot 2024-08-14 at 8 48 38 AM" src="https://github.com/user-attachments/assets/3531e058-8626-4842-ab2a-baacee8da8d1">

**2. Sending an alternative asset (Pizza) while paying fees with another alternative asset (GN).**

<img width="1728" alt="Screenshot 2024-08-14 at 8 48 19 AM" src="https://github.com/user-attachments/assets/34c80882-525f-479c-b520-35b54f6a3594">

----------------------------------------------------------------------------------------------------------------------------
## **Inactive Functionality**:

**3. Sending the maximum amount of the native asset (UM).**
**4. Sending the maximum amount of an alternative asset (GM) without any native asset (UM) balance, and paying the fee with the same alternative asset (GM).**

----------------------------------------------------------------------------------------------------------------------------
## **Proposals**:

Invariants (3) and (4) fundamentally both rely on the presence of UM. In the transaction planner service implementation, we need to handle these cases by checking the following conditions:

- If the user sends the maximum amount of the native asset (UM):
  - craft a spend action.
- If the user sends max alternative asset (GM), and UM is _absent_:
  - craft a spend action.
- If the user sends the maximum amount of an alternative asset (GM) and the native asset (UM) is _not_ absent:
  - fall back to the multi-fee model and craft an output action to ensure the fees are handled correctly.

Alternatively, the spend transaction planner request (TPR) can be reserved exclusively for the native asset (UM). For all other alternative assets, when sending the maximum amount, the output TPR can be used, leveraging our multi-fee system to handle the transaction efficiently.

cc @Valentine1898

**Comment by Valentine1898** [comment]
@TalDerei I believe your proposed solution will work
 
But to me the important point is that the planner should reject TPR that contains spend actions in these cases: 
1. If `spend.asset_id != fee.asset_id`
2. If spend amount is not equal to the maximum amount 
This also leads to a secondary constraint: 
3. the TPR cannot contain more than one spend action

I believe that these restrictions should be added specifically to the planner so that client-side mistakes don't create unexpected `TransactionPlans`

**Comment by TalDerei** [comment]
> But to me the important point is that the planner should reject TPR that contains spend actions in these cases:

Just to clarify, are you leaning towards checking the aforementioned conditions on the frontend, or do you prefer only supporting max sends for UM? The former is more flexible.

**Comment by Valentine1898** [comment]
> > But to me the important point is that the planner should reject TPR that contains spend actions in these cases:
> 
> Just to clarify, are you leaning towards checking the aforementioned conditions on the frontend, or do you prefer only supporting max sends for UM? The former is more flexible.

I think we should support MAX send not only for UM, but for alt_fee tokens as well. 
But my argument is that we should also change the code of our RPC planner and add these conditions, not just change the TPR construction logic on the frontend

**Comment by TalDerei** [comment]
It's unclear to me how to support max spends for _alternative_ fee tokens, like `GM`/ `GN`. Consider bullet points 2 and 3 in the proposal. I don't think there's a way to distinguish what is a valid alternative fee token, compared to a non-valid fee token like TestUSD, in the frontend?

**Comment by TalDerei** [comment]
> But my argument is that we should also change the code of our RPC planner and add these conditions, not just change the TPR construction logic on the frontend

Agreed. On another note, it's unclear to me how to support max spends for _alternative_ fee tokens, like `GM`/ `GN`. Consider bullet points 2 and 3 in the proposal. I don't think there's a way to distinguish what is a valid alternative fee token, compared to a non-valid fee token like TestUSD, in the frontend? Typically, we rely on querying the database for this information.

**Comment by Valentine1898** [comment]
> I don't think there's a way to distinguish what is a valid alternative fee token, compared to a non-valid fee token like TestUSD, in the frontend? Typically, we rely on querying the database for this information.

The frontend can query gas prices RPC and get a list of alt fee tokens 
We already do this to display alt fee warning correctly, see https://github.com/penumbra-zone/web/pull/1614.

**Comment by TalDerei** [comment]
> But to me the important point is that the planner should reject TPR that contains spend actions in these cases:

since we can't query the actions contained within the `ActionList` as it's not a public field, an alternative approach would be to add checks in the transaction planner service implementation before [returning](https://github.com/penumbra-zone/web/blob/main/packages/services/src/view-service/transaction-planner/index.ts#L53) the `TransactionPlan`. In this context, although the planner can possibly have planned an invalid transaction, it wouldn't be returned to the frontend.
