### ISSUE TITLE
Recognize UM when no registry listing

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1677]
When doing an IBC-in, we display a list of balances the user has on that specific chain:

<img width="552" alt="Screenshot 2024-08-09 at 1 52 50 PM" src="https://github.com/user-attachments/assets/04693370-f1eb-4ec7-b1a1-6ef4e8728bf7">

In that example above, the IBC asset is actually UM. The reason it may not show is because UM does not have an entry on that particular chain's directory in the [cosmos chain registry](https://github.com/cosmos/chain-registry). For this specific case, it's because it's osmosis testnet. However, on mainnet, UM does not exist in the noble and cosmos hub registry. In theory, as we add chains, it'll become harder to keep up with. 

Because these ibc denoms are simply hashes of the channel+denom name, we can identify UM programmatically. We've done this in the past:
https://github.com/penumbra-zone/web/blob/8fc6c85a184c5d7d95c2372c703ece780ce8f440/apps/minifront/src/components/ibc/ibc-in/hooks.ts#L128-L138

**Task**: If we see an entry in the balance that we identify as UM by its hash, we don't need to rely upon the cosmos chain registry, we should just show the UM icon. This way, users will always be able to recognize it.

**Comment by TalDerei** [comment]
closed by https://github.com/penumbra-zone/web/pull/1737?

**Comment by grod220** [comment]
Yep 👍
