### ISSUE TITLE
Integrate Prax into cosmos-kit

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1680]
Frontends in cosmos frequently use wallet aggregators like [cosmos-kit](https://cosmology.zone/products/cosmos-kit) to get quick integrations with a broad set of wallets. Minifront in fact uses cosmos-kit itself.

While Prax does not sign transactions like a normal cosmos wallet, getting an integration into this library will allow frontends to easily allow Prax connections which would support cases like auto-address filling.

Here's a guide in the cosmoskit docs: https://docs.cosmology.zone/cosmos-kit/integrating-wallets/adding-new-wallets

After this is complete, we should flag the skip folks that they can now use cosmos-kit for https://go.skip.build/ instead of a custom integration.

**Comment by VanishMax** [comment]
The PR implementing this issue: https://github.com/cosmology-tech/cosmos-kit/pull/499

**Comment by VanishMax** [comment]
Implemented by https://github.com/cosmology-tech/cosmos-kit/pull/504 and https://github.com/cosmology-tech/cosmos-kit/pull/499
