### ISSUE TITLE
Void.vote client package updates

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1681]
After https://github.com/penumbra-zone/web/pull/1648 is merged and deployed & react package revised, we should work with Starling Cybernetics on updating the client packages in https://void.vote/ to ensure they are using the latest patterns for connecting with Prax.

**Comment by VanishMax** [comment]
Tracking the progress here: https://github.com/starlingcyber/void.vote/pull/2

**Comment by VanishMax** [comment]
Implemented in https://github.com/starlingcyber/void.vote/pull/4
