### ISSUE TITLE
syncing breaks in the presence of an undefined asset id

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1694]
It seems like https://github.com/penumbra-zone/web/pull/1637 doesn't resolve the issue introduced in https://github.com/penumbra-zone/web/commit/60d0c2e0ea9ec1d6fed0e092ef159922b7cde462, which is still breaks syncing for me? I think we may need to implement this [additional check](https://github.com/penumbra-zone/web/pull/1637#discussion_r1702633180) to fully address the issue.

Unless, 
```
const undefinedAssetId = new AssetId({
     inner: undefined,
});
 ```    
 is somehow an impossible condition?

cc @grod220 @turbocrime

**Comment by grod220** [comment]
Can you add more detail about the specific environment you are running this with. It's local pd right?

**Comment by TalDerei** [comment]
doesn't seem to be possible, so closing this out
