### ISSUE TITLE
initClientError on IBC page

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1700]
not sure if these are actionable error messages, but I was noticing them in the console. 

<img width="1728" alt="Screenshot 2024-08-15 at 7 51 26 AM" src="https://github.com/user-attachments/assets/67fa2d37-814d-4373-abf7-d779d79fcb2b">

**Comment by grod220** [comment]
Yeah, I've noticed this too, quite noisy. I'll check in with the cosmos-kit team on this one.

**Comment by grod220** [comment]
From the team:
```
there's the logLevel  prop in <ChainProvider /> Values can be: 'TRACE' | 'DEBUG' | 'INFO' | 'WARN' | 'ERROR' | 'NONE'; 'NONE' should make them silent
```
