### ISSUE TITLE
IDB contains block processing logic

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#1719]
**Describe the bug**
IDB contains block processing logic such as epoch genesis.

**To Reproduce**

1. Initialize indexed-db. Do not initialize a block processor.
2. See that idb already contains a 0th epoch

**Expected behavior**
IDB should not arbitrarily create chain state without external input

**Comment by TalDerei** [comment]
not sure how broad you're intending the scope to be, but we should also check for other instances of divergence where IDB may be performing tasks that should be handled by the block processor.

**Comment by grod220** [comment]
It's not super clear to me why the database can't be responsible for its own initialization+default values logic.

https://github.com/penumbra-zone/web/blob/75ef4f5bb7bb07c4ea0478bee360beba12220f28/packages/storage/src/indexed-db/index.ts#L174-L180

This is basically saying, on initialization see if default value has been set. If not, set it.

**Comment by grod220** [comment]
Ah, I see there's a draft PR, will take a look at that to see if there's something I'm missing
