### ISSUE TITLE
Use feature detection for incompatibility warning, not an allowlist

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#1723]
**Describe the bug**
'Incompatible' banner is displayed to users running compatible software.

**To Reproduce**

1. Use a non-Chrome browser based on Chromium v119 or later
2. Install some Penumbra provider
3. Visit minifront
4. See annoying 'Incompatible' banner

**Expected behavior**

Minifront should not warn the user about incompatible software, when they are using compatible software. Feature detection should be used to identify incompatibility, not a simple allowlist.

**Comment by s0uk4** [comment]
Heya, I had this issue myself. I was running Brave Browser on version 1.68.37, and got this big red banner at the top.

<img width="614" alt="Screenshot 2024-08-21 at 3 11 48 PM" src="https://github.com/user-attachments/assets/9a57b266-05de-4552-aafc-1b88445fa821">
