### ISSUE TITLE
wallet address copy button not visible

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1764]
what happened to the visibility of the copy button?

https://github.com/user-attachments/assets/a4ce78da-5ac1-4ff8-8b6d-0d1f029ee569

**Comment by grod220** [comment]
This copy button has proven to be quite stubborn with its regressions 😅 . It must be related to UIv2 stuff. From within the transaction details page:
<img width="239" alt="Screenshot 2024-09-04 at 10 37 26 AM" src="https://github.com/user-attachments/assets/7625c3d4-77b9-49fc-a893-408dd1e6220c">
<img width="220" alt="Screenshot 2024-09-04 at 10 37 29 AM" src="https://github.com/user-attachments/assets/1faa0a48-5f82-4bd9-bc89-19fb44943e27">
