### ISSUE TITLE
rethink segmented pickers

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1778]
references https://github.com/penumbra-zone/web/pull/1734#pullrequestreview-2267839802

I personally find the use of segmented pickers specifically for text a bit jarring, but I'm opening this issue as a reminder that we should reach a consensus before publishing a production build of minifront v2. cc @VanishMax

**Comment by TalDerei** [comment]
related to https://github.com/penumbra-zone/web/issues/1302

**Comment by VanishMax** [comment]
With the updated v2 design, the animations are going to be simplified, so closing as not planned
