### ISSUE TITLE
Minifront & connecting to non-prax wallets

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1811]
There is a [BETA version](https://chromewebstore.google.com/detail/prax-wallet-beta/ejpfkiblcablembkdhcofhokccbbppnc?authuser=0&hl=en) of the Prax wallet that allows external folks to test out new versions before the prod version is released.

At the moment, it cannot connect to minifront as it hard-codes Prax as an exclusive wallet:
https://github.com/penumbra-zone/web/blob/2381922e7abd706057cf2e5235d71f545a2ac28a/apps/minifront/src/prax.ts#L5

We should change this file's assert methods to automatically detect _any_ Penumbra wallet and connect to it (likely the first one listed in the `Record<string, PenumbraProvider>` of `getProviders()`. This way, both the prod and beta extensions can be used to connect to minifront.

**Comment by VanishMax** [comment]
@grod220 are we going to let users choose the provider? Let's say users have two extensions installed: Prax and Prax Beta. What should the click to "connect button" do?

I'd propose creating a dialog with all options of injected providers to let users select one. If only one is available, no need for showing the dialog

**Comment by grod220** [comment]
> I'd propose creating a dialog with all options of injected providers to let users select one. If only one is available, no need for showing the dialog

This sounds good to me 👍
