### ISSUE TITLE
Get and order by priority from registry

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1829]
At the moment, minifront displays assets in arbitrary order:

<img width="687" alt="Screenshot 2024-10-04 at 12 34 11 PM" src="https://github.com/user-attachments/assets/88a9b439-e27a-442d-b17c-db44b1ce5b82">

The issue is that not all of these assets are equally important. Ideally, the most relevant ibc assets get shown on top.

For that, minifront needs to rely upon [Metadata priority score](https://buf.build/penumbra-zone/penumbra/docs/430d52207ecc47dbacae84b596bc99db:penumbra.core.asset.v1#penumbra.core.asset.v1.Metadata) which it gets when it requests from the rpc (in `BalancesRequest` and `AssetsRequest`).

Task:
- Add priority scores to registry for assets: https://github.com/prax-wallet/registry
- Update rpc methods that return denom metadata to reference registry priority scores
- Update minifront to utilize priority score for ordering in assets selector

**Comment by TalDerei** [comment]
closed by https://github.com/prax-wallet/registry/pull/96?

**Comment by grod220** [comment]
That's only part 1, we need to implement it into minifront & use in rpc. In progress: https://github.com/penumbra-zone/web/pull/1860
