### ISSUE TITLE
UI Components are a bit broken with a light color scheme?

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/web#1850]
c.f. https://insights-2.penumbra.zone/ https://github.com/penumbra-zone/p3numb3rs/blob/2e7a6c34b1fb304cbbbc98e317b521b5066a8ef3/app/routes/_index.tsx

This is a simple site using the components as is, and with a dark color scheme (I assume that the CSS prefers-color-scheme selector is used somewhere), you get a readable result:
![image](https://github.com/user-attachments/assets/f5bddf93-a929-4976-a856-0bc03f97e62d)
But, if you have a light color scheme as a preference, you get:
![image](https://github.com/user-attachments/assets/11f0d822-d2c1-4c72-9fa8-bd8e42f80d8f)
with all the text colors being broken.

**Comment by grod220** [comment]
cc @smmhrdmn

I don't think our UI components support light mode

**Comment by smmhrdmn** [comment]
@grod220 @cronokirby nope, we don't have a light mode, although one could be made. the light mode for cuiloa for instance was a one off design since it's not using the ui lib

**Comment by cronokirby** [comment]
To clarify, the issue arises when `prefers-color-scheme: light` is set, but works fine if it's unset, or set to `dark`.

In Chrome, you can manually emulate this setting for testing:
https://stackoverflow.com/questions/57606960/how-can-i-emulate-prefers-color-scheme-media-query-in-chrome

**Comment by cronokirby** [comment]
Oh, seems like this was just a bug in the app using the components (setting a white background for a light color scheme) nevermind :grimacing:

**Comment by conorsch** [comment]
> seems like this was just a bug in the app using the components (setting a white background for a light color scheme) 

https://github.com/penumbra-zone/p3numb3rs/pull/2/files
