### ISSUE TITLE
async/await routing 

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#186]
The service worker needs the ability to "pause" and await the result of an entire separate system (e.g. popup ui). It requires some fundamental architecture thinking of routing messages and building support for async/await. These systems do not share the same event loop. Perhaps it can have some kind of storage that keeps track of pending requests and fulfills them when they receive an event from the popup. Essentially re-creating what @turbocrime's grpc wrapper does. The clients should think they are using async/await, but under the hood it should be using the chrome extension native listeners + post messages of these different systems.

 There are three features that require this more advanced routing feature in the extension:
- AuthAndBuild proto message
- Connect button: https://github.com/penumbra-zone/web/issues/73
- Transaction confirmations

**Comment by hdevalence** [comment]
Another behavior we need to be able to support is request proxying: https://github.com/penumbra-zone/web/issues/222

In particular, this means that the GRPC router in the extension must be generic over the service definition, since we have many different requests we need to be able to proxy.

**Comment by turbocrime** [comment]
dependent on #240 and will be implemented in that work

**Comment by grod220** [comment]
@turbocrime to create a draft PR

**Comment by grod220** [comment]
Book time on Monday for pairing 🍐
