### ISSUE TITLE
Incorrect asset balance reporting on the send page

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1870]
a bug was identified on the **send** page where the wallet balance is incorrectly displayed as the USDC-equivalent value of all assets combined. The wallet should only display the correct balance of the _selected_ asset (eg. USDC) when initiating a transaction.

**Comment by TalDerei** [comment]
@hdevalence strangely wasn't able to reproduce?

**Comment by hdevalence** [comment]
Huh, could have been my misreading I guess. If we can't repro we should close until it reoccurs

**Comment by TalDerei** [comment]
> Huh, could have been my misreading I guess. If we can't repro we should close until it reoccurs

clearly looked like a bug to me, can you try reproducing?

**Comment by TalDerei** [comment]
closing until issue reappears
