### ISSUE TITLE
frontend design aspirations

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1880]
It feels like there’s a lot we can learn from **Coinbase’s** frontend interface, as it’s intuitive and user-friendly. Here's a few examples. Specifically, a notification system might be something worth considering. 

------------------------

<img width="428" alt="9 94USD" src="https://github.com/user-attachments/assets/240fae37-dc99-4ea2-b35e-9a54c22b3dba">

<img width="419" alt="Send $9 95 in USDC" src="https://github.com/user-attachments/assets/eebc1c41-5e00-474c-ad67-b803fd3f3511">

<img width="926" alt="Transactions" src="https://github.com/user-attachments/assets/a35f2642-2de7-47d6-a102-ea25e456aa64">

<img width="314" alt="Notifications" src="https://github.com/user-attachments/assets/0be56dba-50d8-4252-b64c-48bf64e5e430">

**Comment by hdevalence** [comment]
@TalDerei do you have access to the Figma file with the V2 designs? would be useful to leave comments there

**Comment by TalDerei** [comment]
> @TalDerei do you have access to the Figma file with the V2 designs? would be useful to leave comments there

I have access, will leave all frontend related comments there going forward
