### ISSUE TITLE
encourage decentralization in minifront’s staking page

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1892]
Currently, staking is managed through Minifront. If a user tries to delegate to a validator with over 5% voting power, the staking page should display a prompt suggesting they select a different validator:

`"The validator you’re delegating to has more than 5% of the current voting power. To promote decentralization, it’s recommended to choose a smaller validator"`. 

`[Delegate Anyways - greyed/minimized] [OK - default/highlight]`

If they click `OK`, it cancels and takes them back to the staking page to choose a different validator. If they click `Delegate Anyways`, it proceeds with their action – users get to choose who they want to delegate to. The staking page could also sort the validators that are over threshold to the bottom of the list.

This is intended to gradually improve stake distribution and promote staking decentralization as the network grows.

**Comment by grod220** [comment]
Proposal: https://forum.penumbra.zone/t/encourage-decentralization-in-minifronts-staking-page/109/2
