### ISSUE TITLE
canonicalize font selection 

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1921]
I think there's low hanging fruit for enhancing the design by using better fonts in certain areas and being more intentional with the typography styles we want to express. 

-----------

<img width="746" alt="Screenshot 2024-11-21 at 7 50 41 PM" src="https://github.com/user-attachments/assets/b6a6d455-c3c1-48f7-a08c-b79aa1551544">

**Comment by grod220** [comment]
This is in the realm of designer responsibility. 

At the moment, the new UI library has fonts that will resolve this issue. But in terms of numbers it's still TBD if we can use font with `font-variant-numeric: tabular-nums;` or we just use a monospaced font for numbers.

**Comment by TalDerei** [comment]
> This is in the realm of designer responsibility.

I'll leave all frontend related comments there going forward! I checked out the typography section in the Figma, and it looks great.
