### ISSUE TITLE
Helper method that promotes a `Transaction` to a `TransactionView`

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#1947]
**Is your feature request related to a problem? Please describe.**

There should be a helper method that promotes a `Transaction` to a `TransactionView`. (Maybe this already exists). All actions with opaque data would be treated as the opaque variant of the transaction view. 

This ensures that anyone building a block explorer or other tooling can write their transaction rendering to operate on a `TransactionView`, which (1) means it can share components with other tooling (2) means it's forward compatible with a future where they have a transaction view that actually views data (e.g., by querying Prax).

**Describe the solution you'd like**

Have a helper method that takes a `Transaction` and returns a `TransactionView`, or a link to the method if it already exists.

**Comment by TalDerei** [comment]
https://github.com/penumbra-zone/web/blob/main/packages/wasm/crate/src/tx.rs#L126-L133
