### ISSUE TITLE
Minifront IBC Deposit and Withdrawal failed with type registry error

### ISSUE THREAD

**Issue by chairulakmal** [penumbra-zone/web#1957]
**Describe the bug**
IBC Deposit/Withdrawal failed on minifront with protobuf type registry error. This occurs not only when sending from/to Noble, but also other IBC chains.

**To Reproduce**
Use IBC Deposit/Withdrawal feature on the latest minifront deployed by Starling Cybernetics or ZecHub: [commit 9ebe4a7](https://github.com/penumbra-zone/web/commits/9ebe4a7582bdf3f828308b7f2e7f87af5f0df0b4).

**Screenshots**
![Screenshot from 2024-12-23 17-03-00](https://github.com/user-attachments/assets/3df7bdbe-19bf-4b73-b7b3-d5c2d81785ce)

**Comment by erwanor** [comment]
Thanks for the excellent bug report @chairulakmal, this is fixed by @VanishMax's #1958
