### ISSUE TITLE
Store swap/swap-claim pairs

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#198]
Should complete indexedb storage of swap data. It's a migration of: https://github.com/penumbra-zone/wallet/blob/7ab6107c30f35fc795042b0579e44311aff9650f/src/utils/WasmViewConnector.ts#L473-L485

**Comment by Valentine1898** [comment]
This issue will require minimal changes to the `indexed-db` structure, so we should preferably solve https://github.com/penumbra-zone/web/issues/252.
