### ISSUE TITLE
NotesRequest

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#200]

**Comment by grod220** [comment]
Yes, indeed we want to implement those filters

**Comment by Vadim121197** [comment]
@grod220 
```
const initializeProto = (noteRecord: SpendableNoteRecord): NotesResponse => {
  if (!noteRecord.addressIndex?.randomizer) throw new Error('missing addressIndex.randomizer');
  if (!noteRecord.note?.value?.assetId) throw new Error('Missing note asset id');

  return new NotesResponse().fromJsonString(
    JSON.stringify({
      noteRecord: noteRecord,
    }),
  );
};
```

is good solution do it from string?
```
new NotesResponse().fromJsonString(
    JSON.stringify({
      noteRecord: noteRecord,
    }),
  ); 
```

**Comment by Vadim121197** [comment]
sorry, it works fine
```
new NotesResponse({
      noteRecord: note,
    });
```

**Comment by Vadim121197** [comment]
IndexedDB doesn`t  save wallet_id 

![Image](https://github.com/penumbra-zone/web/assets/52686175/b70b8d28-8679-4577-b4e0-29f9e0163b7b)

**Comment by grod220** [comment]
> IndexedDB doesn`t save wallet_id

On the Rust side, if someone passes a wallet_id, the service will check to ensure that the currently active wallet id matches the one they passed. If not, it will throw an error. Let's copy that implementation.
