### ISSUE TITLE
IndexByAddressRequest

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#205]

**Comment by Vadim121197** [comment]
what is the task? do we only need to implement on the extension and webapp sides? @grod220

**Comment by grod220** [comment]
We need to implement all the of the view service methods. Here's this one:

https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.view.v1alpha1#penumbra.view.v1alpha1.ViewProtocolService.IndexByAddress

**Comment by Vadim121197** [comment]
```
export const getIndexByAddress = async (address: string): Promise<number> => {
  const req = new IndexByAddressRequest();
  req.address = new Address({
    inner: bech32ToUint8Array(address),
  });
  const res = await viewClient.indexByAddress(req);

  return res.addressIndex?.account ?? 0;
};
```

I'll leave it here to check if the request works
