### ISSUE TITLE
Manual account #

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#214]
At the moment, you can only select an account by clicking the right/left arrows:

<img width="387" alt="Screenshot 2023-11-02 at 1 41 43 PM" src="https://github.com/penumbra-zone/web/assets/16624263/bcd45613-1522-4430-95c3-4f5311e8315e">

A user needs to be able to select say account #234252352 without having to click that many times.

Should be able to simply click the number and type a custom index #.

**Comment by zpoken** [comment]
@grod220 do we have max value?

**Comment by grod220** [comment]
Yes, that's right
