### ISSUE TITLE
Standardize address component

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#217]
All displays of the address should use the `AddressViewComponent`. We may need to strip down the styles inside of that component and accept a classname so consumers can customize it.

<img width="372" alt="Screenshot 2023-11-03 at 10 35 16 AM" src="https://github.com/penumbra-zone/web/assets/16624263/82e43b23-98d0-434c-aa46-e996987e7b10">

**Comment by Vadim121197** [comment]
What exactly should we display at AddressViewComponent?
1. Account
2. Identicon
3. Address
4. Copy

**Comment by grod220** [comment]
Yes. The objective is to ensure we re-use UI components between different parts of the repo. At the moment, it's duplicated code.

**Comment by Vadim121197** [comment]
![Image](https://github.com/penumbra-zone/web/assets/52686175/8133cd1b-0bfa-4983-a843-efa9825e68a6)



![Image](https://github.com/penumbra-zone/web/assets/52686175/9a8438af-3dcc-45f4-af65-8bf7f8c281f9)



![Image](https://github.com/penumbra-zone/web/assets/52686175/9a503759-1ab4-4430-9b13-06f01635ad7a)



![Image](https://github.com/penumbra-zone/web/assets/52686175/5c26d9b5-e90c-4e7f-84fd-5022e9f63fc1)

@grod220 do we need to put 4 different displays with different designs into 1 component?

**Comment by grod220** [comment]
If two places are using the same design (like in the extension and send tab), they should be sharing the same component.

For those others, the design should not be shared, but a component should be written so that the shortening and copy is shared between it. Something like:

```typescript
<ComponentA>
   <AddressView />
   <CopyIcon />
</ComponentA>

<ComponentB>
   <AddressView />
   <CopyIcon />
</ComponentB>
```

**Comment by grod220** [comment]
@Vadim121197, did you start this? Please drag to in progress if so.
