### ISSUE TITLE
Extension should support GRPC proxying

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#222]
Penumbra users should be able to configure their own RPC endpoints. This is important for two reasons:

- **Decentralization**: If users cannot configure their own RPC endpoints, they're locked into using the RPC hardcoded into the frontend. This adds a single point of failure.
- **Privacy**: Users should be able to run their own nodes, or send requests only to trusted nodes. Longer-term, we should solve network privacy for FE requests, but this is a harder problem.

Both the extension and the FE website require RPC access. Users should only have to make one configuration setting, and have that RPC endpoint be used for all of their requests.  To accomplish this, we should have the extension proxy GRPC requests to the RPC endpoint it uses for scanning, similar to the architecture for `pclientd`:

```
   ┌────────┐  ┌─────────────────┐  ┌────────┐
   │  Client│  │         pclientd│  │Penumbra│
   │Software│◀─┼─┐             ┌─┼─▶│Fullnode│
   └────────┘  │ │             │ │  └────────┘
            ╭  │ │ ┌───────┐   │ │
     public │  │ │ │grpc   │   │ │
 chain data │  │ ├▶│proxy  │◀──┤ │
            ╰  │ │ └───────┘   │ │
               │ │             │ │
            ╭  │ │ ┌───────┐   │ │
    private │  │ │ │view   │   │ │
  user data │  │ ├▶│service│◀──┘ │
            ╰  │ │ └───────┘     │
               │ │               │
            ╭  │ │ ┌ ─ ─ ─ ┐     │
   spending │  │ │  custody      │
 capability │  │ └▶│service│     │
 (optional) ╰  │    ─ ─ ─ ─      │
               └─────────────────┘
```

**Comment by grod220** [comment]
What would that look like design wise? Would it just be a checkbox in the current RPC settings page in the extension for `[x] proxy all traffic`?

Also, can you clarify how this is different than our existing RPC settings page where a user can choose another RPC provider url?

**Comment by hdevalence** [comment]
> What would that look like design wise? Would it just be a checkbox in the current RPC settings page in the extension for `[x] proxy all traffic`?

Assuming by design you mean UX design, there would be no explicit design. The extension already has a setting for the RPC endpoint, and we'd leave that unchanged.

Software-design-wise, we need the GRPC router in the extension to be generic, and route requests based on the GRPC service name -- view service requests go to the view server, custody service requests go to the custody server (which triggers a popup, etc), and query requests are proxied to the configured RPC endpoint.

> Also, can you clarify how this is different than our existing RPC settings page where a user can choose another RPC provider url?

The difference is that the RPC settings would apply to the extension _and all connected frontends_, since we would encourage frontends to use the extension for all RPC requests, and it will be easier for them to do so than to add their own RPC configuration.

**Comment by grod220** [comment]
In https://github.com/penumbra-zone/web/pull/249, discovered a specific requirement folks should be aware of.

- The extension needs to serialize responses to JSON
- `google.protobuf.Any` is a potential field in the response (e.g. `ibc.core.client.v1.QueryClientStatesRequest`)
- In order to [serialize an Any](https://github.com/bufbuild/protobuf-es/blob/main/docs/runtime_api.md#serializing-messages), a [type registry](https://github.com/penumbra-zone/web/blob/main/packages/types/src/registry.ts#L7) is required enumerating the types that the any could potentially be.

This means, that we can't indiscriminately proxy requests, but need to keep a registry of types that may need serializing when the response is sent back to the consumer.

**Comment by turbocrime** [comment]
in #282, i am easily able to use any PromiseClient to provide a service to extension channel clients by simply designating it as the fallback to an empty service implementation

https://github.com/penumbra-zone/web/blob/cd678c54c5ec62d1fcc14a25512808a950cb52c4/apps/extension/src/service-worker.ts#L24-L47

**Comment by turbocrime** [comment]
proxying of unknown services should also be possible. service descriptions can be supplied at runtime, as demonstrated in many connectrpc tests. 

see here they have a service description in a test as an object literal.

https://github.com/connectrpc/connect-es/blob/431dcb66f76f0a449ea829c3d2fc9e81c2b358f9/packages/connect/src/promise-client.spec.ts#L29-L57

this type of descriptor could be created from a json representation.

or, bufbuild seems to have some serialization/deserialization tools

https://github.com/bufbuild/protobuf-es/blob/2e010703437ade8fe72fede89e5952c11495ee82/packages/protobuf/src/create-registry-from-desc.ts#L95

we could accept descriptors from the client, or grab them from the web, and generate types at runtime that way.

once we have the servicetype/messagetypes we can use them in a registry for deserializing Anys or whatever.

it probably isn't possible to create completely custom handlers for responding to requests entirely within the extension, but we could provide some basic things like interactive approval by detecting certain field names, partial messages missing specific field names, maybe reference to types defined within our services, or some other kind of documented annotation.

contextvalues and headers are powerful here, we could possibly provide dynamically loaded services with indirect access to things within the extension via context. there's also no reason this couldn't be bidirectional. a page could provide a service interface that the extension talks to

**Comment by turbocrime** [comment]
status: extension is capable of proxying any service for which we have a describing ServiceType and a promiseClient

immediate next: hardcode a set of proxies for these services from penumbra repo https://github.com/penumbra-zone/penumbra/blob/main/crates/bin/pclientd/src/lib.rs#L305-L314

later: dynamic service proxy. implement a service-generic transport

**Comment by turbocrime** [comment]
part of #475
