### ISSUE TITLE
Errors are being clipped in the toast

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#231]
<img width="481" alt="Screenshot 2023-11-09 at 4 30 28 PM" src="https://github.com/penumbra-zone/web/assets/16624263/14d62ab6-44bd-4ce5-a788-0555629e8d32">

It should be able to fit fully in box

**Comment by grod220** [comment]
Also, is there a way that errors can be formatted if it's json?

**Comment by Vadim121197** [comment]
Can I get more information, please?

**Comment by Vadim121197** [comment]
`"[internal] ConnectError: [unknown] {"type":"PENUMBRA_DAPP_GRPC_RESPONSE","sequence":14,"requestTypeName":"penumbra.view.v1alpha1.TransactionPlannerRequest","serviceTypeName":"penumbra.view.v1alpha1.ViewProtocolService","error":"Error: invalid length"}"` it is not json

**Comment by Vadim121197** [comment]
but i can get error and show it
`JSON.parse(e.rawMessage.slice(e.rawMessage.indexOf('{'), e.rawMessage.indexOf('}') + 1));`

**Comment by Vadim121197** [comment]
<img width="424" alt="Знімок екрана 2023-11-28 о 14 52 39" src="https://github.com/penumbra-zone/web/assets/52686175/8ebe0625-0fe6-4153-8ce7-9e1cf12abf8a">

format json like this?

**Comment by grod220** [comment]
> Can I get more information, please?

If you look at the image, not all of the message is inside the box. There is a css issue.

> format json like this?

This is tricky because we cannot guarantee the output will be json. It could another format. I'd say forget that requirement. Let's stick to just showing the raw error. Just ensure it fits in the box.

**Comment by Vadim121197** [comment]
![Image](https://github.com/penumbra-zone/web/assets/52686175/903136aa-0dc6-4c4d-8425-5ec1f45dcfac)

@grod220

**Comment by grod220** [comment]
Yes, that looks like it fixed the bug 👍
