### ISSUE TITLE
Implement real sync detection

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#233]
At the moment, it's a fake sleep timer: https://github.com/penumbra-zone/web/blob/efbed4a417606a9e92f134b981d1f955e7ef287e/packages/router/src/grpc/view-protocol-server/broadcast.ts#L22-L23

It should be waiting until it is scanned in a block

**Comment by Valentine1898** [comment]
https://github.com/penumbra-zone/web/blob/02d7a61afa04bb596ce25d799749b37caab266a4/packages/router/src/grpc/view-protocol-server/note-by-commitment.ts#L19
we should add await_detection handling for NoteByCommitmentRequest after resolving this issue
