### ISSUE TITLE
eliminate types package from repo

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#237]
the "types" package should be eliminated. removing types from their
relevant contexts to collect and re-export is not useful and adds complexity.

many types exported by the types package:

* have a name in conflict with proto types, and should be renamed
* are used to type a public interface, and should be exported by the implementor
* are used privately in one package, and should *not* exported
* serve a specific purpose, but central availability makes that unclear

the types package also exports many things that are not types, mostly utility
functions, converters, and validators. these should be eliminated or moved to
appropriate locations.

**Comment by TalDerei** [comment]
closing as not planned
