### ISSUE TITLE
Need to clear indexed-db during version migration  

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#252]
https://github.com/penumbra-zone/web/blob/2fffe0f76a2cf1d5a0405d9fe27023832221254f/packages/storage/src/indexed-db/index.ts#L44
If we increase the `indexed-db` version, the upgrade function will try to create new object stores, but all of them already exist and we will get an error 
```typescript
Uncaught DOMException: Failed to execute 'createObjectStore' on 'IDBDatabase': An object store with the specified name already exists.
``` 
I think we need to run `clearCache()` before creating new object stores

In the future it makes sense to do custom `indexed-db` version migrations that will preserve existing data, but for testnet we can just delete and re-create the tables

**Comment by grod220** [comment]
I thought if we bump the dbVersion, it needs to re-create those tables anyway because the structure of them could have changed. Are we not doing the standard way?

**Comment by Valentine1898** [comment]
The problem is that we are not deleting tables, but trying to recreate them

**Comment by Valentine1898** [comment]
UPD: we don't need clearCache()

**Comment by Valentine1898** [comment]
```typescript
for (const objectStoreName of db.objectStoreNames) {
						db.deleteObjectStore(objectStoreName)
					}
``` 
We should be doing something like this

**Comment by grod220** [comment]
But why isn't that in any of the upgrade examples in the documentation? https://github.com/jakearchibald/idb#readme

They all seem to be creating tables in the upgrade function without deleting any

**Comment by Valentine1898** [comment]
Probably because in most cases these are examples of creating indexed-db tables, not migrating them. 
Besides, the case of migration when we delete all data and recreate it is quite rare in practice, more often there is a need to save data during migrations.

**Comment by Valentine1898** [comment]
At least right now migration doesn't work for us, you can try increasing the indexed-db version and updating the existing extension to get errors
