### ISSUE TITLE
error after update website

### ISSUE THREAD

**Issue by Vadim121197** [penumbra-zone/web#258]
<img width="890" alt="Знімок екрана 2023-11-28 о 13 51 20" src="https://github.com/penumbra-zone/web/assets/52686175/d9803908-0052-4d78-84a7-e28494a9ee44">

**Comment by Vadim121197** [comment]
Close browser => open browser => open http://localhost:5173/dashboard

**Comment by grod220** [comment]
With the new connection manager, this is not a relevant issue anymore
