### ISSUE TITLE
Vite updates

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#271]
We should update to the latest vite, vitest, & @vitest/browser versions. Looks like there are breaking changes.

Steps:
1. Do `pnpm up -r --latest`
2. Run pnpm test
3. See errors and make config changes to support new versions

Looks like there is a new warning that we need to add `type: "module"` to some of our packages. There are also changes to our vitest browser that need to be made.

**Comment by Vadim121197** [comment]
do you mean this warning - `The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.`?

**Comment by Vadim121197** [comment]
conflicts with buffer library occur when updating vite! I tried to find an analog of the buffer library,(buffer was updated 3 years ago!) https://www.npmjs.com/package/buffer-lite tried to use this library and everything works! maybe you know another library?
