### ISSUE TITLE
Implement and use ExportFullViewingKey

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#274]
Currently, the view service reaches directly into localExtStorage to get the full viewing key. We should replace every use of that to calling the Custody service's ExportFullViewingKey endpoint (needs implementing).

**Comment by Vadim121197** [comment]
@grod220  should be implemented like there - https://github.com/penumbra-zone/web/blob/main/packages/query/src/queriers/app.ts?

**Comment by grod220** [comment]
No should be a method added to custody service: https://github.com/penumbra-zone/web/blob/main/packages/router/src/grpc/custody/router.ts#L24

and then it should be used in the view service wherever we are using local storage to get the key.
