### ISSUE TITLE
View transaction details bug

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#281]
I can't view the transaction history, and the asset balance's aren't decrementing after sending a transaction? The blocks are synced to the latest state and the `dapp / extension` aren't displaying any visible errors in the console. This seems to be an issue on both `https://grpc.testnet.penumbra.zone/` and `https://grpc.testnet-preview.penumbra.zone/` rpc urls.

**Comment by turbocrime** [comment]
this has been broken for several days

https://github.com/penumbra-zone/web/blob/6d3ee0a303b64335f56df6d806d8281ec9699560/packages/router/src/grpc/view-protocol-server/tx-info-by-hash.ts#L20

this line is returning undefined for incoming hashes

**Comment by TalDerei** [comment]
@turbocrime I verified that the formatting of`NoteSource` wasn't the source of the issue. Instead it seems like the syncing-related functionality (`syncAndStore` and `saveSyncProgress`) associated with detecting new updates in compact blocks was returning empty blocks. In turn, that meant the `storeNewTransactions` calls weren't being reached, and the database wasn't being updated with the recent transactions. 

#260 made the web repo dependent on the `testnet-preview` rpc url, and main is using the wrong [config](https://github.com/penumbra-zone/web/blob/main/packages/constants/config.ts#L10) which explains this behavior. Modifying the rpc to `https://grpc.testnet-preview.penumbra.zone/` seems to fix the transaction view bug.

**Comment by grod220** [comment]
We just got to remember to change this back when the new testnet goes live this week, before we deploy a release of the extension

**Comment by TalDerei** [comment]
> We just got to remember to change this back when the new testnet goes live this week, before we deploy a release of the extension

yeah I just wanted to make sure the source of the bug wasn't a deeper, more fundamental issue
