### ISSUE TITLE
On onboarding, internal error

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#293]
To replicate, install the extension fresh and go to web app. Without having gone through the onboarding phase, the web app does not load and offers unclear error.

<img width="799" alt="Screenshot 2023-12-11 at 3 54 16 PM" src="https://github.com/penumbra-zone/web/assets/16624263/d4511bee-71b0-48e4-a889-403e7e42abf3">

**Comment by turbocrime** [comment]
there is a behavior in place now in #295 that delays requests until connection is certain

https://github.com/penumbra-zone/web/blob/a846fabaddbabca25e315348dfcb8bb584358b0b/packages/transport/src/create.ts#L100

additionally, errors from the services now transmit through the client, and surface in the page

<img width="624" alt="Screenshot 2023-12-12 at 19 13 42" src="https://github.com/penumbra-zone/web/assets/134443988/694606fe-243e-47d9-a927-7d346a6957c7">

i think that's "fixed" for the purposes of this issue but the webapp still does not understand the situation of "extension is present but i can't talk to it yet"
