### ISSUE TITLE
dashboard/transactions should display syncing status

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#305]
transactions view is limited by available sync. the transactions view should prominently indicate if syncing is not complete.

**Comment by hdevalence** [comment]
it would be cool to have the progress bar at the top of the dashboard. there is probably also a typescript library for doing EWMA estimation of speed and time remaining. the progress bar in pcli uses `indicatif`, which has an EWMA-based estimator of how much time will be left that seems reasonably accurate.
