### ISSUE TITLE
Support fees in Penumbra Web

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/web#308]
Prior to mainnet, the web extension will need to support including transaction fees, paid in terms of the staking token (`penumbra`) and based on the current gas prices retrieved from a fullnode.

This is already implemented in the `Planner`. Examples can be seen in the `pcli` code, for example see https://github.com/penumbra-zone/penumbra/blob/37b1eab/crates/bin/pcli/src/command/tx.rs#L262-L271: 

```rust
        let gas_prices = app
            .view
            .as_mut()
            .context("view service must be initialized")?
            .gas_prices(GasPricesRequest {})
            .await?
            .into_inner()
            .gas_prices
            .expect("gas prices must be available")
            .try_into()?;
  
            // ...
            let mut planner = Planner::new(OsRng);
            planner.set_gas_prices(gas_prices);
```

When `Planner::plan` is called, the required gas will automatically be added to the transaction plan. After the plan has been finalized, the included fee can be retrieved with the `TransactionPlan`'s `fee` property.

After this initial implementation is complete, we should add support for fee _tiers_: https://github.com/penumbra-zone/penumbra/issues/3153 however this requires some small changes to the planner.

## Steps:

- [x] Fetch the current gas prices from the view service (`GasPricesRequest`)
- [x] Supply the current gas prices to the planner (`Planner::set_gas_prices`)
- [x] Display the transaction fees in the UI

Linked issue in main repo: https://github.com/penumbra-zone/penumbra/issues/3370

**Comment by Valentine1898** [comment]
blocked by https://github.com/penumbra-zone/web/issues/203

**Comment by jessepinho** [comment]
@Valentine1898 thanks for flagging that — I was working on this ticket, so I'll pull in #203 as part of my work.

**Comment by jessepinho** [comment]
@Valentine1898 scratch that — just saw that you already grabbed it!

**Comment by Valentine1898** [comment]
Yeah, I'm already working on #203, I think I can finish it today

**Comment by aubrika** [comment]
Currently blocked on fee support in core protocol work
