### ISSUE TITLE
Stream large idb queries, avoid querying entire tables

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#312]
our `IndexedDb` wrapper class provide methods for things like getting "all transactions", "all swaps", etc

https://github.com/penumbra-zone/web/blob/83b95344315146c11a61be2aed46ff29bff37a58/packages/storage/src/indexed-db/index.ts#L159-L161

these query wrappers are used by service methods and elsewhere, which may await the return to load the entire table into memory, perform their own synchronous in-memory filtering, and return a faux "streaming" response

https://github.com/penumbra-zone/web/blob/83b95344315146c11a61be2aed46ff29bff37a58/packages/router/src/grpc/view-protocol-server/tx-info.ts#L13-L24

tables could eventually be large, so these should be real streaming queries. we are using idbp which [provides very nice cursor and asynciterator features](https://github.com/jakearchibald/idb#idbcursor-enhancements) for this purpose, so that change is minimal.

but more broadly, queriers should make specific queries. we should possibly remove "getAll" methods from `IndexedDb`.

**Comment by grod220** [comment]
Oh for sure we should do this. Planning wise, normally we should keep things in the backlog until our planning meeting where we can prioritize the next sprint's Todos. But given we are in a kind of free form holiday season, think it's fine to drag in if you want.

**Comment by grod220** [comment]
Applies to this filtering as well: https://github.com/penumbra-zone/web/pull/332
