### ISSUE TITLE
Icon in transaction list suggests external links

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#313]
<img width="664" alt="Screenshot 2023-12-19 at 12 40 42 AM" src="https://github.com/penumbra-zone/web/assets/44879/928f3f2a-f55e-4830-bfdf-422c3629afa4">

This icon is generally used for links to external websites, suggesting to users they are about to navigate out of the app. But the link stays within the app. Users might not want to click a link to an external explorer for privacy reasons.

**Comment by grod220** [comment]
How about https://www.flaticon.com/free-icon/file_1150592 or https://www.flaticon.com/free-icon/info_471713?

**Comment by hdevalence** [comment]
Either seems fine! I think the first one is better as a "zoom into the details" icon
