### ISSUE TITLE
send dialog and plumbing does not handle over-long memos

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#323]
1. generate a 512-byte memo plaintext, this is longer than the limit (the address and the text together are 512 bytes)
```
Python 3.9.6 (default, Nov 10 2023, 13:38:27)
[Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 'aaaaaaa ' * (512//8)
```
2. paste into memo field in send dialog
3. tx approval popup appears, click approve
4. tx build fails with inscrutable error message
<img width="387" alt="Screenshot 2023-12-28 at 2 30 58 PM" src="https://github.com/penumbra-zone/web/assets/44879/790f5517-db52-43c8-af66-c7b0413c725f">

two problems here:

1. form should be doing input validation on memo length
2. errors should be propagated back to user

**Comment by turbocrime** [comment]
after some investigation, 'unreachable' is fully accurate: the wasm call throws a RuntimeError.unreachable. so as far as we can handle, propagation is correct.

we can wrap every impl's wasm calls in try/catch to add more detail, but it might be more correct to throw meaningful errors from wasm, either in wasm-ts, wasm-bundler, or from wasm itself

**Comment by turbocrime** [comment]
it's worth considering that errors may contain potentially sensitive information

connectrpc has chosen deliberately to obfuscate errors in implementations as generic "internal" errors, unless they are thrown specifically as a ConnectError: https://github.com/connectrpc/connect-es/discussions/341

in the course of #295 we took the opposite attitude, but in routing-refactor #282 this behavior of obfuscating internal errors resumes, as we're now 'properly' using connectrpc server tooling

i'm going to add catch/rethrows around every wasm call in routing-refactor, and convert existing throws to ConnectError throws, as those are clearly intended to be explicitly returned

we should identify errors that might leak information

**Comment by hdevalence** [comment]
Huh, that's very surprising. It seems like a very strange policy to me, since if a server is leaking sensitive info in its error messages that's a problem with the server, and censoring errors from one particular client doesn't really fix that.

**Comment by hdevalence** [comment]
> i'm going to add catch/rethrows around every wasm call in routing-refactor, and convert existing throws to ConnectError throws, as those are clearly intended to be explicitly returned

Hmm, maybe we should wait to figure out if there's another solution before we go and add boilerplate code to all of our handlers+

**Comment by turbocrime** [comment]
the choice is made to assist in correct implementation. you can still choose to throw from the service if you'd like, but the default is to obfuscate, and i think that's a good default.

**Comment by grod220** [comment]
> the wasm call throws a RuntimeError.unreachable

Sadly, this likely means that the Rust code panicked. A part of addressing this task should mean finding the part of the Penumbra repo codebase that isn't using the `Result/Err` type (I suspect it's a `.expect()` somewhere) and fixing it.

> so as far as the extension and webapp can handle

When I ran into this before, I had a hard time wrapping this in a try/catch on the javascript side. It's more like the whole process aborts.

> but in routing-refactor https://github.com/penumbra-zone/web/pull/282 this behavior of obfuscating internal errors resumes, as we're now 'properly' using connectrpc server tooling

Obfuscating errors feels like a very painful road to continue on. This makes debugging user errors essentially impossible and turns troubleshooting into 🤷‍♂️ . I don't see why we wouldn't be more expressive in error messages and choose to intentionally throw `ConnectError` so that the web app can give meaningful feedback to users.

**Comment by turbocrime** [comment]
https://github.com/penumbra-zone/web/commit/ae2b7456aa6881046df924f43e78aa2120631471 in #282 catching all wasm calls in impls and logging all errors thrown out of impls

**Comment by turbocrime** [comment]
ae2b745 reverted. current state is:

* landed form validation
* not performing validation in js impl
* impl throws correctly propagate to client
* wasm error messages are not meaningful

**Comment by turbocrime** [comment]
length used in #329 was incorrect. wasm uses an 80-byte address in the memo, not a BECH32 address, so the boundary is 432/433

**Comment by turbocrime** [comment]
#356 correct memo length in form validation

**Comment by turbocrime** [comment]
view service validation merged https://github.com/penumbra-zone/penumbra/pull/3585
