### ISSUE TITLE
Implement filters for StatusStreamRequest

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#334]
https://github.com/penumbra-zone/web/blob/v3.1.0/packages/router/src/grpc/view-protocol-server/status-stream.ts#L13

**Comment by hdevalence** [comment]
I'm not sure we want to do this. I think we should get rid of the wallet parameters entirely and make the view service be modal.

**Comment by grod220** [comment]
Can you elaborate what you mean by "modal"? 😅

**Comment by hdevalence** [comment]
As in, the user specifies their active wallet in the extension, and the extension handles requests using that wallet. The website doesn't make requests for a specific wallet, only one is active at a time.
