### ISSUE TITLE
Improve error message when a user has no wallets

### ISSUE THREAD

**Issue by jessepinho** [penumbra-zone/web#342]
![Image](https://github.com/penumbra-zone/web/assets/1121544/2199c7c7-b363-416a-80b4-2f6efcac5ca3)

![Image](https://github.com/penumbra-zone/web/assets/1121544/184c6fd2-dae2-442f-b108-141969393dbe)

At the moment, users only see these ugly (and not-human-friendly) error messages when they have no wallet connected. These should be human-readable messages.

Long-term, it'd be great to have a set of defined error-state components for the web app and extension, so that we know how things ought to look when there's an error state. But for now, this ticket is just to make the error messages more human-readable.

**Comment by grod220** [comment]
Somewhat related to: https://github.com/penumbra-zone/web/issues/73 (but trying to catch up on that issue would give you a headache).

We have a few different states we've thought through (but not fully implemented yet):

- Wallet extension not installed
  - Top right should have a "connect" button that triggers a popup that directs users to install the extension in the chrome web store
- Installed, but not "connected" (aka proactive approval to share data with the web app)
  - Top right should have a "connect" button that triggers an approval window
- Installed and connected
  - Top right should have a visual indication of connection. At the moment, we display the chain-id.

But beyond this, we haven't put a ton of thought on what it looks like for various components (like the assets tab) that encounter these same states. Should each component have an error state (designed better)? Should those pages do an automatic redirect to a page that encourages them to install the extension? Some pages would require the extension (like the transactions page), but others would not (like viewing governance proposals). There are UX patterns we haven't thought through enough.

**Comment by jessepinho** [comment]
Ah, thanks — since it looks like #73 supersedes this issue, I'll close this one. 

Definitely would love to discuss the UX pattern/error state questions you raised though! If you want any help on the component design front, including working with the design agency, let me know!
