### ISSUE TITLE
Handle Tendermint's `res.log` property if it exists

### ISSUE THREAD

**Issue by jessepinho** [penumbra-zone/web#352]
When we [broadcast a transaction](https://github.com/penumbra-zone/web/blob/main/packages/query/src/queriers/tendermint.ts#L29-L30) via `TendermintQuerier#broadcastTx`, we currently just return the transaction hash (via `res.hash`). That means that all the other properties of `res` are lost — including `res.log`, which may contain a useful error or other message.

This ticket is to log `res.log` to the console if it's truthy, and to throw it if it's a known error message. Per @grod220's proposal below:

```ts
// Should add more errors as we discover them
const knownErrors = [
  "proof did not verify",
  "is not a valid field element",
]

  async broadcastTx(params: Uint8Array) {
    const req = new BroadcastTxSyncRequest({ params });
    const { hash, log } = await this.client.broadcastTxSync(req);

    if (log) {
      if (knownErrors.some(e => log.includes(e)) {
        throw new Error(log)
      } else {
        console.error(log)
      }
    }

    return hash;
  }
```

**Comment by grod220** [comment]
It's sort of a sad behavior that if there is a tendermint error, it shows up as a string in that response log versus raising.

I think we should consider having some kind of logic to help work around this. Otherwise, like in your case with the `output proof did not verify` error, it gets swallowed. Proposal:

```typescript
// Should add more errors as we discover them
const knownErrors = [
  "proof did not verify",
  "is not a valid field element",
]

  async broadcastTx(params: Uint8Array) {
    const req = new BroadcastTxSyncRequest({ params });
    const { hash, log } = await this.client.broadcastTxSync(req);
    if (knownErrors.some(e => log.includes(e)) {
       throw new Error(log)
    }
    return hash;
  }

```

**Comment by jessepinho** [comment]
That sounds perfect. I'll add your proposal to the original ticket description so whoever takes it knows what to do with it.

Is `is not a valid field element` an actual error we might get from Tendermint?

**Comment by grod220** [comment]
I took that error from the source code for the verify step in Rust: https://github.com/penumbra-zone/penumbra/blob/main/crates/core/component/shielded-pool/src/output/proof.rs#L163
