### ISSUE TITLE
Add a request ID for transaction approval requests

### ISSUE THREAD

**Issue by jessepinho** [penumbra-zone/web#377]
Currently, when transactions are being sent to the approval popup, there's no ID attached to them to ensure that wires aren't crossed if multiple requests are being sent to the popup before any approvals. We should add a request ID when sending transactions to the popup.

(@turbocrime, can you please add more detail here on how wires could get crossed? Not sure I understand the vulnerability here.)

Per @turbocrime's [comment](https://github.com/penumbra-zone/web/pull/366#discussion_r1458048719):

> just use crypto.getrandomuuid to make one at the moment the request is sent, and check that the response contains the same uuid.
> in the zustand slice, we should
> 
> 1) never return the uuid as part of a selector
> 2) throw if we are setting request into slice but a uuid is already present
> 3) clear the uuid when resolving the approval

**Comment by turbocrime** [comment]
closed #565
