### ISSUE TITLE
CI builds are failing intermittently for `packages/crypto` and `packages/storage`

### ISSUE THREAD

**Issue by jessepinho** [penumbra-zone/web#379]
If you navigate to [this test run](https://github.com/penumbra-zone/web/actions/runs/7590871408/job/20678594468), then toggle open the "Run all tests" section, then toggle open the `@penumbra-zone/crypto-web:test` section, you'll see the following error:

```
 ⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯
  
  Vitest caught 1 unhandled error during the test run.
  This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.
  
  ⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
  TypeError: Failed to fetch dynamically imported module: http://localhost:5173/@fs/home/runner/work/web/web/node_modules/.pnpm/@vitest+utils@0.34.6/node_modules/@vitest/utils/dist/index.js?v=981845ef
  This error originated in "src/encryption.test.ts" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
  ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
  
   Test Files  no tests
        Tests  no tests
       Errors  1 error
     Start at  01:07:31
     Duration  6.50s (transform 0ms, setup 0ms, collect 0ms, tests 0ms, environment 0ms, prepare 0ms)
  
   ELIFECYCLE  Test failed. See above for more details.
  Error:  command finished with error: command (/home/runner/work/web/web/packages/crypto) /home/runner/setup-pnpm/node_modules/.bin/pnpm run test exited (1)
```

We don't actually use dynamic imports at the moment, so this error likely points at something inside Vite itself. It's worth noting that the `encryption.test.ts` test suite is run using [a special config](https://github.com/penumbra-zone/web/blob/main/packages/crypto/browser.config.ts#L6) for running in a browser environment, which may be causing this issue...?

UPDATE: We're now seeing these [test failures](https://github.com/penumbra-zone/web/actions/runs/7636547510/job/20804167822?pr=387) for `packages/storage` as well.

### Switch to JSDom
I tried switching to JSDom, in case [the chromium/playwright combination we're using](https://github.com/penumbra-zone/web/blob/34be34b8234d83b70ad33b51670faaf138f9733a/packages/crypto/browser.config.ts#L8-L9) is the source of this issue. `window.crypto` [is not implemented in JSDom](https://github.com/jsdom/jsdom/issues/1612#issuecomment-249441408), though. So I tried polyfilling it using the `webcrypto` import from `node:crypto`, per [this suggestion](https://github.com/jsdom/jsdom/issues/1612#issuecomment-1659591074). However, that resulted in a different [test failure](https://github.com/penumbra-zone/web/actions/runs/7591393707/job/20679391388):

```
     ❯ src/encryption.test.ts > encryption > Key > unseal > returns null when the box cannot be decrypted (OperationError)
       → The operation failed for an operation-specific reason
  ⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯
  
  
   FAIL  src/encryption.test.ts > encryption > Key > unseal > returns null when the box cannot be decrypted (OperationError)
  OperationError: The operation failed for an operation-specific reason
  ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
  Serialized Error: { code: +0, INDEX_SIZE_ERR: 1, DOMSTRING_SIZE_ERR: 2, HIERARCHY_REQUEST_ERR: 3, WRONG_DOCUMENT_ERR: 4, INVALID_CHARACTER_ERR: 5, NO_DATA_ALLOWED_ERR: 6, NO_MODIFICATION_ALLOWED_ERR: 7, NOT_FOUND_ERR: 8, NOT_SUPPORTED_ERR: 9, INUSE_ATTRIBUTE_ERR: 10, INVALID_STATE_ERR: 11, SYNTAX_ERR: 12, INVALID_MODIFICATION_ERR: 13, NAMESPACE_ERR: 14, INVALID_ACCESS_ERR: 15, VALIDATION_ERR: 16, TYPE_MISMATCH_ERR: 17, SECURITY_ERR: 18, NETWORK_ERR: 19, ABORT_ERR: 20, URL_MISMATCH_ERR: 21, QUOTA_EXCEEDED_ERR: 22, TIMEOUT_ERR: 23, INVALID_NODE_TYPE_ERR: 24, DATA_CLONE_ERR: 25 }
  Caused by: Error: Cipher job failed
  ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
  
   Test Files  1 failed | 1 passed (2)
        Tests  1 failed | 20 passed (21)
     Start at  02:00:44
     Duration  4.93s (transform 350ms, setup 85ms, collect 429ms, tests 2.04s, environment 2.33s, prepare 930ms)
  
   ELIFECYCLE  Test failed. See above for more details.
  Error:  command finished with error: command (/home/runner/work/web/web/packages/crypto) /home/runner/setup-pnpm/node_modules/.bin/pnpm run test exited (1)
```

**Comment by conorsch** [comment]
Initial report refers to PR https://github.com/penumbra-zone/web/pull/378, but I also see this problem after most recent merge into main (of https://github.com/penumbra-zone/web/pull/357). [First run failed](https://github.com/penumbra-zone/web/actions/runs/7590607525/attempts/1), then a [naive re-run passed](https://github.com/penumbra-zone/web/actions/runs/7590607525/attempts/2).

**Comment by jessepinho** [comment]
Yep, and in fact, @turbocrime and I saw this issue even a day or two before that merge.

**Comment by grod220** [comment]
The tests in the crypto package are quite important. We definitely should not forget to re-enable these.

Given their sensitivity, they also are not a good candidate for a mock environment. We need to get them working reliably in a headless browser.

Related to: https://github.com/penumbra-zone/web/issues/271. Our headless browser tests are running in an old version of vite. Perhaps they will be more reliable when we make those breaking changes.

If in the end vitetest cannot do a good job of doing this (browser mode is in experimental after all), we should just use playwright directly.
