### ISSUE TITLE
New streaming tx build rpcs

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#384]
`witnessAndBuild` and `broadcastTransaction` now are streaming rpcs (not unary anymore). Update to new bufbuild types to see breaking changes. Our UI should support the API with new states:

- Build progress bar
- Broadcast success
- Tx confirmed

**Comment by grod220** [comment]
@TalDerei realizing this may conflict with the work you are in progress with. This new RPC change likely requires us to rethink a lot with our build implementation. `build_parallel` and `offscreenClient` do not give in-progress updates. This means we need to change them into streaming methods as well. Another round of internal messaging re-work...

**Comment by TalDerei** [comment]
Can I fold these changes and new broadcast toast (#327) into #369?

**Comment by grod220** [comment]
Given the new RPC definition, I think you will have to. However, it does increase the scope of the task quite a bit fyi.

**Comment by hdevalence** [comment]
Wait, what's the requirement for the change?

**Comment by grod220** [comment]
Frontend requirements:

Before 
- unary request/response
- Toast on build-in-progress, toast on broadcast, toast on confirmation

After
- streaming request/response
- Probably should not be using toasts anymore and have a table for:
  - build progress bar
  - broadcasting loading
  - tx confirmed


Extension requirements:

Before:
- Unary request flow:
 - frontend —> service worker —> offscreen window —> web worker

After:
- Convert rpc handler to async generator
- Offscreen window needs message streaming capabilities
- Spawn and handle web workers not with Promise.All() but with streaming or generators
- Determine rules on communicating build progress. % of actions built?

**Comment by hdevalence** [comment]
I see, thanks for mapping it out. To start I think it's fine to just change the interfaces and not report progress info (so the bar goes from 0 to 100% directly). Then we have the plumbing in place and can change the reporting in a follow up chunk of work.

**Comment by TalDerei** [comment]
@grod220 The new streaming RPCs don't actually conflict with #369. To limit the scope, let's merge that in. I already started implementing some of the new interface changes separately.

**Comment by turbocrime** [comment]
still needs ui

**Comment by turbocrime** [comment]
ui provided by #327
