### ISSUE TITLE
Swap UI [part 1]

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#390]
- Re-enable frontend tab
- New denom-out UI component (non-editable)
- `planWitnessBuildBroadcast` should be a shared function between send/ibc/swap
- Implement proper Denom Registry. Related: https://github.com/penumbra-zone/web/issues/140
- Add swap/swap commitment to view-protocol-server/transaction-planner.ts

**Comment by turbocrime** [comment]
lpnft asset display names look pretty ugly in the ui right now

**Comment by grod220** [comment]
Can you share a screenshot here? @turbocrime
