### ISSUE TITLE
Add tests for WitnessAndBuildRequest

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#412]

**Comment by Valentine1898** [comment]
I'm stumped on this issue. 
We are using `offscreenClient` to build each action separately, and I couldn't get it to work in a test environment. 
At the same time, if I try to mock `offscreenClient` it results in just not testing anything. 

We already have a test in wasm crate that tests build, and we also have a separate test for `wittness` rpc so the lack of a test for `WitnessAndBuild` doesn't seem very critical. 

If anyone wants to start working on this again, they can continue in the `412-add-tests-for-witnessandbuildrequest` branch or start from scratch.

**Comment by grod220** [comment]
I agree, let's close this issue then 👍
