### ISSUE TITLE
Fix error in main 

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#416]
<img width="1427" alt="Screenshot 2024-01-25 at 11 12 04 PM" src="https://github.com/penumbra-zone/web/assets/70081547/e35269c9-2ac6-4675-b4b5-c4d250625585">

**Comment by turbocrime** [comment]
it looks like i either broke offscreen.ts or wasm-build-action.ts earlier today, but i can't identify what the error is. it seems to be some kind of cors thing.
