### ISSUE TITLE
Estimate swap claim fee requirement

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#422]

**Comment by hdevalence** [comment]
This should be fairly straightforward, we can use the current gas prices to estimate the cost of a "pure" swap claim transaction (which will have ~constant size, we can always overestimate a bit), then multiply by the current fee tier (on the assumption that prices won't change dramatically block to block, which seems reasonable).

**Comment by jessepinho** [comment]
Per @hdevalence in Discord, we'll wait to do this for now since we want to refactor the `WasmPlanner` a bit, and the gas prices are all `0` in testnet-preview anyway.

**Comment by TalDerei** [comment]
outdated as fee logic has changed
