### ISSUE TITLE
Dedicated unclaimed swaps box

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#423]

**Comment by hdevalence** [comment]
I feel somewhat strongly that there shouldn't be UI for this if at all possible. Can we do the right thing automatically?

**Comment by grod220** [comment]
I should have filled out this with more detail (instead of using the tracking issue create shortcut). 99% of the cases should be covered here: https://github.com/penumbra-zone/web/issues/420, where it's automatic.

The intent of this issue was for the user that (for whatever reason) has unclaimed swaps present. If we detect the case, we'd show a box giving the user the ability to continue where they left off. I'm afraid if we don't have this, there will be that odd occasion in discord where a user is requesting to be rescued.

Or would you say this case is so improbable, we should disregard it?
