### ISSUE TITLE
Make tx details page for swap + swap claim nicer

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#424]

**Comment by hdevalence** [comment]
We'll want to augment the protos to support this: https://github.com/penumbra-zone/penumbra/issues/3832

Proposal for rendering of swap actions:
```
[VARIANT A: output NoteViews are present]
Swap
(L) 123.45 UM --> (L) 38.23 USDC { + (L) 12.78 UM [if unfilled inputs]}
{ if claim_tx is set: Claimed in fefe...fefe (link) }

[VARIANT B: output NoteViews are not present]
Swap
(L) 123.45 UM --> (L) USDC
```
Here (L) represents a circular logo. Ideally this would be handled by a single component.

In the component code, we'd probably want to actually have two "rows", one for each direction, with each row displayed conditionally on having nonzero inputs. (At the protocol level, it's technically possible to create a swap that swaps both directions simultaneously, though no software we have would ever do this).

For the swap claim view, we can just show the output note(s).

**Comment by hdevalence** [comment]
Proposed steps:

- [ ] Extend `TransactionPerspective` to include the data that is needed to fill in the fields added in https://github.com/penumbra-zone/penumbra/issues/3832
- [ ] Fill in support in Rust stack for the new fields in the `SwapView` and `TransactionPerspective`: the batch swap output data etc in the `TransactionPerspective` needs to be correctly inserted when using the perspective to generate a `TransactionView`
- [ ] Pull in updated Rust code as a wasm dep, rebuild
- [ ] Change extension typescript code to insert the new additional data into the `TransactionPerspective` it uses to generate the view
- [ ] (Optionally, but seems like a good idea) change extension code to not save the `TransactionView` and instead compute it on-demand from the `Transaction` + `TransactionPerspective`. When we add equivalent prices support we will want the views to be dynamic.

**Comment by hdevalence** [comment]
Similar structure to https://github.com/penumbra-zone/penumbra/issues/3838

Not sure how we want to augment the perspective to have the output notes. Currently we have a general purpose "advice" set, but this only allows looking up notes by commitment and the original `Swap` doesn't have commitments to its eventual outputs. Transactions can have multiple swaps, so maybe we need a mapping from swap commitment => pairs of output notes?

**Comment by jessepinho** [comment]
Moving to blocked for now, as there's quite a bit of work that needs to be done before this ticket can be completed.
