### ISSUE TITLE
Remove password strength requirements

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#442]
The extension forces users to use a "strong enough" password, but it's not clear this improves security, because the key material ends up in the extension memory anyways, and something that's compromised the user's machine can probably get access to that.  It also makes operating on the testnet less convenient.  If there were no strength requirements, users who were comfortable with lower security could set an empty password.

**Comment by grod220** [comment]
This isn't hard to implement, but it feels a bit non-standard no? I've never used a web3 wallet that did not enforce _some_ password requirement. I do not have security experience, but if we got the web wallet audited, wouldn't we be advised to require a password? 

Given the key material is in memory, having a password vs not doesn't always seem the equivalent. For instance, to extract the password from memory would require some technical sophistication. To drain an account with no password would be trivial for someone to walk up to an unlocked computer to do.

**Comment by hdevalence** [comment]
> To drain an account with no password would be trivial for someone to walk up to an unlocked computer to do.

Right, but the point of this change isn't to remove password locking, it's to allow users to opt out of it. Right now, every time I reload the extension during development, I have to open up the password manager and paste in the password.

We can still have users create a password, and also warn them if it doesn't meet strength requirements -- the point is just to allow users who have other security practices (e.g., full-machine locking, disregard for security, whatever) to avoid friction.
