### ISSUE TITLE
Extension view server should be able to view foreign transactions

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#448]
Currently, the extension's view server can only view transactions it's already downloaded and indexed during scanning. This means that when a user navigates to the tx view page for a transaction that's not theirs, there's an error message "are you trying to view a transaction you can't see?".

This is unfortunate, since it's a missed opportunity to highlight the protocol's privacy properties. Viewing _other_ people's transactions is a way for users to understand that their transactions are private too.

The way we handle this in `pcli` is that if the requested transaction isn't in the view server's database, we fetch it from a full node and then view it.

**Comment by grod220** [comment]
This is currently in place. Indexeddb gets called and then tendermint as a fallback. Or was there a view you noticed that error when you should not have gotten it?

<img width="1328" alt="Screenshot 2024-02-06 at 5 38 49 PM" src="https://github.com/penumbra-zone/web/assets/16624263/93234932-9d8d-43cb-9a0a-2e18927cd031">
