### ISSUE TITLE
Deploy new extension for v0.65 testnet

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#456]
- [x] https://github.com/penumbra-zone/web/pull/357
- [x] https://github.com/penumbra-zone/web/pull/426
- [x] https://github.com/penumbra-zone/web/pull/443
- [x] https://github.com/penumbra-zone/web/pull/450
- [x] https://github.com/penumbra-zone/web/pull/455
- [x] https://github.com/penumbra-zone/web/pull/471
- [x] Testnet v0.65 chain goes live
- [x] https://github.com/penumbra-zone/web/pull/479
  - [x] Update to latest dependencies: `pnpm up -r --latest`
  - [x] Manual testing to confirm extension works with main flows
  - [x] Change the default grpc URL from testnet-preview.penumbra.zone to testnet.penumbra.zone
  - [x] Update [manifest version](https://github.com/penumbra-zone/web/blob/main/apps/extension/public/manifest.json#L4) to `4.0.0`
- [x] Create repo release with `v4.0.0` tag. Triggers approval to run chrome extension publishing.
- [x] Run `Deploy Static Site` [github action](https://github.com/penumbra-zone/web/actions/workflows/deploy-firebase-dapp.yml)
- [x] Wait 1-3 days until new extension version is live on [chrome web store](https://chromewebstore.google.com/detail/penumbra-wallet/lkpmkhpnhknhmibgnmmhdhgdilepfghe)
- [x] Make `@channel` announcement to Discord members about re-enabled web experience (and tease swaps coming soon?)

**Comment by hdevalence** [comment]
We are unblocked! Really excited about this.

**Comment by hdevalence** [comment]
I just tested that the extension works with Deimos after doing the pnpm upgrade, changing the RPC url, and sending transactions.

**Comment by grod220** [comment]
Deployed & published ✅
