### ISSUE TITLE
Force a moment's delay of transaction approval

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#457]
It's common for permission dialogs to prevent clickjacking and mitigate dialog desensitization by preventing instant or very fast approval, forcing the user to at least recognize what's happening before interacting with the UI.

We should disable the transaction approval's confirm button when it appears, and enable it after a few seconds.

**Comment by hdevalence** [comment]
If we put a countdown timer ("3,2,1") we have a way to hide proving latency behind security. there's a necessary delay from proving, might as well use it for security.
