### ISSUE TITLE
Don't swallow errors inside the `ViewProtocolServer`

### ISSUE THREAD

**Issue by jessepinho** [penumbra-zone/web#469]
At the moment, any errors thrown inside a `ViewProtocolServer` impl, like this

![Image](https://github.com/penumbra-zone/web/assets/1121544/143e8759-b033-4046-951e-f610862b471a)

...get swallowed and converted into a useless, generic "internal error":

![Image](https://github.com/penumbra-zone/web/assets/1121544/627c377e-057b-40d7-b5a2-bb0be84d790d)

It looks like [`rethrowImplErrors`](https://github.com/penumbra-zone/web/blob/main/apps/extension/src/service-worker.ts#L81-L109) is supposed to handle that, but somehow errors are still getting swallowed. This ticket is to fix that.

**Comment by jessepinho** [comment]
cc @turbocrime — is this a known issue with `rethrowImplErrors`?

**Comment by turbocrime** [comment]
rethrowImplErrors didn't work on streams because streams have their own internal error handling, and now we're hitting that since we're using more streams

**Comment by grod220** [comment]
Think this is a duplicate of: https://github.com/penumbra-zone/web/issues/437

**Comment by jessepinho** [comment]
Good catch — closing this as a duplicate
