### ISSUE TITLE
Use test account on Testnet 66 to drive transaction view improvements.

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#487]
I used the test account (https://rustdoc.penumbra.zone/main/penumbra_keys/test_keys/constant.SEED_PHRASE.html) to perform a bunch of actions on Testnet 66 using `pcli`.

Loading the seed phrase into the web extension highlights gaps in the transaction view component's rendering.

**Comment by grod220** [comment]
Ah yes, the assets table design needs some thought as well

**Comment by grod220** [comment]
Think this is out of date (everyone forgot what this was addressing specifically), going to close
