### ISSUE TITLE
Indexed-db global refactoring

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#488]
Theoretically, there is a way in which we can get rid of Indexed-db global simply by passing all data as parameters to the wasm function. 
1. `view_server.rs` 
View server (aka block scanner) uses `Indexed-db` only to save and read `advices`. 
The solution is that we should add `advices` discovery as one of the conditions for calling `flush_updates()`. Currently we only call `flush_updates()` when we detect new notes and swaps. Also in this case we will need to add advices to `ScanBlockResult` and also pass advices already stored in `indexed-db` when initializing view server. 
My assumptions:
- we won't lose in scanning speed because we won't actually call `flush_updates()` more often than we do now because in blocks where we detect advices we are also guaranteed to detect swaps and call `flush_updates()` anyway
- We will not pass more data during initialization than we do now. We can easily recognize already used `advices` from unused ones. Used `advices` can be ignored and not passed during view server initialization, and considering that swap claim will almost always automatically occur in the next block after swap, in practice advices will be unused for only one block, and will almost never be passed during view server initialization.
2. `tx.rs`
We use reading from `indexed-db` to construct transaction view and transaction perspective. 
The point is that only during the `TxV` and `TxP` generation itself we can determine which `notes` and `assets` data we need. This is the main reason why we have to read data from `indexed-db` directly and we can't prepare it on TS side and pass it as parameter, and passing all `notes` and `swaps` records as parameters seems like a very bad idea.
The solution is to decompose the `transaction_info()` wasm function into several smaller helper wasm functions, and move the TxV and TxP generation itself to the TS. 
- This does not lead to additional code duplication.  We already have 2 different functions for `TxV` and `TxP` generation for wasm and pcli. 
3. `wasm_planner.rs` 
For `swap_claim()`, there is no difficulty to pass `SwapRecord` as a parameter, having previously prepared the data on the TS side. 
For `plan()`, we can move the implementation of this function to the TS side. 
First we call `planner.notes_requests()` and get `NotesRequest` 
then, based on the received `NotesRequest`, we prepare notes data on the TS side.  
And finally call `plan_with_spendable_and_votable_notes()` with already prepared data. 

I think I could quickly test the proposed solution for View server, and if it works, then other steps to get rid of Indexed-db are definitely possible.

**Comment by TalDerei** [comment]
@grod220 should we consider closing this as "not planned"?

**Comment by grod220** [comment]
Yes, with the new Storage generic, think most of my qualms with this are addressed
