### ISSUE TITLE
First load connection issues

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#51]
On first load of the dapp, it is almost guaranteed to get this error in the console:

```
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
```

If you wait a few seconds and reload, this goes away and it loads correctly. This likely means that the [way we are connecting with the extension](https://github.com/penumbra-zone/web/blob/main/apps/extension/src/content-scripts.ts#L7) is not sufficient on that initial connection.

Note how `/wallet` [handles connections](https://github.com/penumbra-zone/wallet/blob/7ab6107c30f35fc795042b0579e44311aff9650f/src/contentscript.ts#L20). It uses Port connections. This may be necessary for this app to start using. This task needs more research though.

**Comment by zpoken** [comment]
although I tried to comment out the sync code, the error is also reproduced
