### ISSUE TITLE
Create standalone static site for node status page

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#513]
As part of https://github.com/penumbra-zone/penumbra/pull/3522 , where we'd like to have the `pd` RPC endpoint serve browser-useful content, it would be useful to have a static landing page we can install as the root content.

This should be a static site with the following content:

- A progress bar for the node's sync status, using [this RPC](https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.util.tendermint_proxy.v1#penumbra.util.tendermint_proxy.v1.TendermintProxyService.GetStatus) to get the [`SyncInfo` data](https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.util.tendermint_proxy.v1#penumbra.util.tendermint_proxy.v1.SyncInfo). (It could update on a timer, say 5s). Since this is intended to be served off the RPC, the client should be aimed at the same HTTP endpoint serving the content.
- Below that, a link labeled "Frontend -->" that goes to `/app/`, where we will have installed minifront.

**Comment by grod220** [comment]
This seems to be a good candidate to use a react "meta-framework". Related: https://github.com/penumbra-zone/web/issues/310#issuecomment-1904608594
