### ISSUE TITLE
Tracking issue: improve error handling

### ISSUE THREAD

**Issue by jessepinho** [penumbra-zone/web#518]
A number of errors get surfaced to the user via our UI that shouldn't be displayed the way they are. This tracking issue is for all the places where errors can be improved. Please add to it as more come to mind.

- [x] #517
- [x] #519
- [x] #520
- [x] #547 
- [x] #571

**Comment by TalDerei** [comment]
Can this tracking issue be closed?

**Comment by jessepinho** [comment]
Yep, done
