### ISSUE TITLE
Show a better UI when the Penumbra Chrome extension is not installed

### ISSUE THREAD

**Issue by jessepinho** [penumbra-zone/web#520]
We currently call [`throwIfExtNotInstalled()`](https://github.com/penumbra-zone/web/blob/main/apps/webapp/src/fetchers/is-connected.ts#L6-L8) in a number of components. This results in rather ugly UIs like this:

![Image](https://github.com/penumbra-zone/web/assets/1121544/e0cff7eb-33c5-4e9f-b96e-e39ef3e79047)

and this:

![Image](https://github.com/penumbra-zone/web/assets/1121544/2f7e4cd7-d665-4c78-a519-4fe928062b25)

This ticket is to improve that UI. Ideally, we could handle this at a top-level component that detects if the extension is not installed, and then disables the _whole_ UI and shows a nicely designed prompt to install the extension.

**Comment by grod220** [comment]
Think this relates to: https://github.com/penumbra-zone/web/pull/475 as well. We want a few user flows supported:
- User has no extension installed -> Splash page, directing to go to chrome web store
- User has extension installed, but is not "connected" (granted permission for extension to give data to web app) -> Similar splash page to above, but with call to action to "connect" (see other defi apps for reference)
- User has extension installed and has approved connection -> Normal UI from route renders
