### ISSUE TITLE
Add max height + scroll to asset selector

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#524]
<img width="884" alt="Screenshot_2024-02-14_at_3 40 18_PM" src="https://github.com/penumbra-zone/web/assets/16624263/d44c03b4-417e-4656-8eeb-61fabeeee64e">

**Comment by jessepinho** [comment]
@grod220 are you sure you weren't seeing this on an old commit? I fixed this a while back. Here's what it looks like for me:



![Image](https://github.com/penumbra-zone/web/assets/1121544/bd51728a-58a7-4c7f-b1f9-26be87cebc6e)

**Comment by jessepinho** [comment]
(moving to blocked for now until that question is resolved)
