### ISSUE TITLE
Price standard assets

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#526]
For standard assets (not delegation or lpnfts), populate ValueView's `equivalentValues` array with pricing data from batch swap output in blocks.

- During block scan, save recent trades to database
- In balances rpc method, read database and pull recent trades of asset and add pricing to `equivalentValues` array
- If trades are old (should be a config set period), do not pass pricing info

**Comment by hdevalence** [comment]
Rather than doing this, we should use the `TransactionPerspective`, as in https://github.com/penumbra-zone/penumbra/issues/3838

Closing this out in favor of an issue that would focus just on having the extension maintain a price table.
