### ISSUE TITLE
Price delegation tokens

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#527]
For delegation tokens, populate ValueView's equivalentValues array with pricing data:

- On asset balances request, if a delegation token is found, query database for exchange rate
- If exchange rate is absent or old (they change each epoch), query full node for latest exchange rates and save to db
- Multiply delegation token by exchange rate for UM token amount to put in equivalentValues array

**Comment by hdevalence** [comment]
Rather than querying the full node on demand, I think it would be better to query during sync (proposed rule: at epoch transitions, and if sync is not catching up) and then always have the latest data.

**Comment by Valentine1898** [comment]
I think we can use `epochDuration` to predict the height of the epoch change (provided we don't have block skips, or they don't affect the height of the epoch change)

**Comment by Valentine1898** [comment]
It might also make sense to make the guaranteed interval for `flushUpdates()` not every 1000 blocks, but also equal to `epochDuration` (719 blocks)
https://github.com/penumbra-zone/web/blob/b619aae8ed83333ae29c17b0a9179f68509651d1/packages/query/src/block-processor.ts#L165

**Comment by hdevalence** [comment]
> How would we detect if we are at the beginning of a new epoch and therefore need to re-query? `epochRoot` field seems to be available in the last block of the epoch. Is it best to set a flag at this block to give an indication to re-query on the next one?

Yes, the presence of `epochRoot` is how the epoch transition is signaled to clients.
