### ISSUE TITLE
Assets table shows equivalent value of all assets

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#529]
Make use of pricing now available.

Design inspiration:

<img width="876" alt="Screenshot_2024-02-14_at_10 30 17_AM" src="https://github.com/penumbra-zone/web/assets/16624263/3b5bced3-86c0-4cea-a211-3d464c8d62c2">

Each asset type requires its own special rendering in `ValueViewComponent`. Will need to ditch table design.

**Comment by hdevalence** [comment]
I think a good first step would be to change the `ValueView` component (even if we aren't currently set up with the plumbing required to track equivalent values).
