### ISSUE TITLE
Should not be able to select same asset in/out

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#533]
User's should not be able to select the same asset for the in/out box. Will involve filtering and a smarter way to initialize the component.

<img width="305" alt="Screenshot 2024-02-15 at 3 00 53 PM" src="https://github.com/penumbra-zone/web/assets/16624263/45621453-ac57-45fb-9568-fe3909c109ea">

This could be part of `assertValidSwaps` in the custody service's `authorize` RPC method. See https://github.com/penumbra-zone/web/pull/821#discussion_r1537044452

**Comment by hdevalence** [comment]
I think we should restructure this UI to have an arrow signifying the swap and only selecting the output token (why do we show the wallet balance of what we're swapping _into_?)

**Comment by grod220** [comment]
Design of the asset out wallet balance basically came from looking as Sushi, but we can remove it if you find it not helpful:

<img width="538" alt="Screenshot 2024-02-16 at 10 23 37 AM" src="https://github.com/penumbra-zone/web/assets/16624263/6b4568fb-0859-453f-a913-2305e566f04c">

They also have a helpful thing where clicking the arrow swaps the asset in/out denoms

**Comment by TalDerei** [comment]
@jessepinho adding comment from https://github.com/penumbra-zone/web/pull/821 to this ticket.

"when trying to swap the same pair, the extension throws **"failed to deliver transaction: check_stateless failed: Trading pair must be distinct"**.

maybe we should have an additional `assertDistinctSwapAssets` assertion check that handles that error with a dedicated toast?"

**Comment by grod220** [comment]
> maybe we should have an additional assertDistinctSwapAssets assertion check that handles that error with a dedicated toast?

In theory, after this issue is addressed, this invalid tx should not be possible to perform right?

**Comment by jessepinho** [comment]
@grod220:

> In theory, after this issue is addressed, this invalid tx should not be possible to perform right?

This assumes people will be using minifront with our extension. But in fact, they could be using a different webapp with our extension, so IMO, both the extension and the UI should check this.
