### ISSUE TITLE
Use proto fields cross-referencing swaps/claims

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#545]
https://github.com/penumbra-zone/penumbra/pull/3809

**Comment by hdevalence** [comment]
xref https://github.com/penumbra-zone/web/issues/424#issuecomment-1947825056
xref https://github.com/penumbra-zone/penumbra/issues/3838

**Comment by grod220** [comment]
Duplicate: https://github.com/penumbra-zone/web/issues/424
