### ISSUE TITLE
Show a helpful toast when the user has not logged into the extension

### ISSUE THREAD

**Issue by jessepinho** [penumbra-zone/web#547]
Right now, when a user has not logged into the extension and tries to e.g., create a send transaction, they get an unhelpful toast:

![Image](https://github.com/penumbra-zone/web/assets/1121544/c7e9b86d-490a-4a8a-9a41-7a3fdd2a037d)

(I believe this used to say something like "User must login to extension" — not sure why that changed.)

Instead, it should show a message like "You must log into the extension first", and without all the `[ConnectError]` cruft.

**Comment by turbocrime** [comment]
there is already logic to handle opening the login popup, instead of using a toast. but the way authorize.ts is written prevents this logic from working

**Comment by jessepinho** [comment]
Ah, this should be closed anyway — it was fixed recently
