### ISSUE TITLE
Simplify `TransactionPlanner` implementation by collapsing unnecessary abstraction

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#609]
Currently, the extension's wasm code has its own fork of the `Planner` code from the Rust view crate, which it uses to handle the `TransactionPlanner` RPC method. This leads to an enormous amount of unnecessary complexity, originally in service of code sharing that wasn't possible anyways.

To fix this, we should collapse the planner implementation into the `TransactionPlanner` RPC implementation, so that that RPC is handled directly and is the only way to plan transactions, and eliminate the `Planner` API which is otherwise unused.

**Comment by jessepinho** [comment]
@hdevalence Just making sure I understand the implications here: does this mean the `transactionPlanner` RPC implementation in the extension could be written entirely in JavaScript? And we'd only need WASM for the actual building of the transaction (+ a few utility functions)?

**Comment by hdevalence** [comment]
@jessepinho See https://github.com/penumbra-zone/web/pull/663 for the resulting implementation. The planner implementation would be entirely written in Rust, but the upside is that the Rust code is much simpler and there's not a need to jump back and forth between Rust and Typescript as in the current code.
