### ISSUE TITLE
Swap animated movie for static image (?)

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#616]
The animated movie looks really nice but it's the single largest part of the frontend payload, which seems inconvenient for cases like bundling it into the RPC. Maybe we should replace it with a static image?

**Comment by grod220** [comment]
Yes, easy enough to swap out. My longest running design request has been getting an animated svg version of this specific thing 😅 . 

Side note: The video is compressed in the webapp/extension, but the penumbra.zone background is uncompressed and is sitting at a whopping 39mb. I honestly don't know how our hosting costs are not absurdly expensive. We should definitely swap that for the compressed version.

**Comment by turbocrime** [comment]
oh, i have a similar svg animation i experimented with late last year around the first part of the summoning ceremony. unfortunately it was cpu-intensive, but maybe it could be simplified.

**Comment by grod220** [comment]
Asked in the #designatives-penumbra slack channel for the original after effects file. There may be a way for us to simply export this as an svg or lottie file. TBD.
