### ISSUE TITLE
Include token metadata for zero-balance `ValueView`s of delegation tokens

### ISSUE THREAD

**Issue by jessepinho** [penumbra-zone/web#617]
Currently, when a user has no delegation tokens for a given validator, we don't show their balance at all:
<img width="1207" alt="image" src="https://github.com/penumbra-zone/web/assets/1121544/795ad8dd-46d6-4585-b704-90c4bd5f831e">

We should show a balance of `0` in the middle of that UI, just like we show a nonzero balance for validators the user _has_ staked:
<img width="1204" alt="image" src="https://github.com/penumbra-zone/web/assets/1121544/31727a9a-3a32-4931-8756-16068de9083b">

The problem is, [we're generating `ValueView`s on the fly](https://github.com/penumbra-zone/web/pull/604/files#diff-9bd971ea2f5dadcc555a9a848d1cea2a0d6df1a0069b9e5e490218058ac5adbcR70-R81) for validators we're not staked in. This means we don't have access to an asset ID for the delegation tokens we're supposed to show a zero balance for, and thus we can't fetch a fully fleshed out metadata object for the delegation tokens.*

## Possible solutions
- Fetch the metadata by a different method than asset ID, such as by display name. (This would likely require a new RPC method. Or, once #612 is done, the extension itself could take care of that more easily by looking for the right metadata in IndexedDB.)

\* Per @aubrika, when I asked if it's possible for a validator to exist when no tokens have been staked:
> https://github.com/penumbra-zone/penumbra/issues/2921 depends on if you are listing "declared" validators, "defined" validators, or both, I suppose. see linked issue for deets

Per @hdevalence:
> how does a validator end up on the chain? someone makes a tx with a ValidatorDefinition action that declares it. at that moment, the validator has been "created" on chain, but there's no delegation tokens yet. i believe that the on chain asset registry actually registers the delegation token at this point
> 
> however to become active, or to appear in a users balances, there must be delegation

**Comment by hdevalence** [comment]
Two points:

1. The asset ID is always computable from the base denom string, since it's a hash of that denom string. However computing that hash may not be possible/easy in typescript (the hashing is provided by our Rust libraries).

2. There is a field in the AssetId proto that exists for this purpose: alt_base_denom https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.core.asset.v1#penumbra.core.asset.v1.AssetId

**Comment by jessepinho** [comment]
@hdevalence Ah, thank you! I was able to use `alt_base_denom` to fetch the metadata 👏🏻
