### ISSUE TITLE
Add link to frontend in popup

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#628]
Users want to be able to easily access a link to a frontend from the extension popup.

A link to the RPC's frontend should be available on the popup index page.

**Comment by hdevalence** [comment]
Rather than doing this, we should link to https://app.testnet.penumbra.zone and have a (buried) setting to change the frontend URL.

**Comment by turbocrime** [comment]
in pairing, we discussed simply using the 'connected sites' list if there is only one member or if it's short enough
