### ISSUE TITLE
Fix misleading rendering in TransactionViewComponent

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#642]
The current transaction view component rendering shows unknown actions as "hidden". This is extremely problematic since it misleads users about what information is actually published by a transaction.

We need to change all of the actions we haven't implemented yet to show an "unimplemented action" text rather than an incognito view.

Later, as we fill in the action views, we should have code comments justifying why information that we don't show is omitted from the view.

**Comment by TalDerei** [comment]
@grod220 is this done? If not, we should mark all bug-related tasks with `mainnet` tag

**Comment by grod220** [comment]
Labeled 👍
