### ISSUE TITLE
DOMException: Only the active worker can claim clients. [error]

### ISSUE THREAD

**Issue by zpoken** [penumbra-zone/web#67]
<img width="447" alt="Знімок екрана 2023-10-03 о 11 44 10" src="https://github.com/penumbra-zone/web/assets/82594516/48aeeb37-e9ea-4546-9f8a-91d34eb8dbfb">

after reload extension catch error -` DOMException: Only the active worker can claim clients. [error]`

**Comment by zpoken** [comment]
i think it there - https://github.com/penumbra-zone/web/blob/main/apps/extension/src/services/index.ts#L36

**Comment by zpoken** [comment]
after login with this error -` Error: Could not establish connection. Receiving end does not exist.`

**Comment by grod220** [comment]
This appears to happen sometimes when a new service worker takes over the old. I'm not quite sure the best approach. We probably should not throw an error at all if this fails.

What do you mean about:
```
after login with this error - Error: Could not establish connection. Receiving end does not exist.
```
Is that a different error, or related to this?

**Comment by zpoken** [comment]
i think it related to previous bug! it cannot be played without a previous error
