### ISSUE TITLE
Mocks should use actual interfaces

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#680]
https://github.com/penumbra-zone/web/blob/main/packages/router/src/grpc/test-utils.ts

Instead of duplicating many interfaces with mock interfaces, and reimplementing mocks multiple times in several files to meet those interfaces, it is preferable to implement a versatile mock once, to meet the real interface, and then import it where used.

**Comment by grod220** [comment]
@Valentine1898 would be great for you to take this one

**Comment by Valentine1898** [comment]
I'm not sure I'm understanding the idea correctly. 
The point is that we most often have to have different mock implementations for different test cases

**Comment by turbocrime** [comment]
https://github.com/penumbra-zone/web/pull/672/files/a1144fe524db25b9eb39a92ff52dfbc5b2611f48#r1521909534
