### ISSUE TITLE
Initial sync unresponsiveness

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#687]
On a fresh install or extension cache clear, we have a moment where the extension goes unresponsive. This causes the web app's app params request to timeout. I think handling the genesis is an expensive operation. We should do some tracing though to figure out where precisely the slow down is and why.

Example user report:

<img width="896" alt="Screenshot 2024-03-06 at 12 49 49 PM" src="https://github.com/penumbra-zone/web/assets/16624263/97285ad2-7ea2-4a26-ada2-c00d54c87e3b">

**Comment by jessepinho** [comment]
Is this still applicable?

**Comment by grod220** [comment]
Should be fixed given the other PR. Closing!
