### ISSUE TITLE
Unhandled context in proxy

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#689]
Attempting to simulate a trade that is too large:

<img width="476" alt="Screenshot 2024-03-06 at 2 31 19 PM" src="https://github.com/penumbra-zone/web/assets/16624263/d55b71aa-3938-4c30-be14-2dcdcb11ba24">

Expecting an error, but it's not responsive.

Extension console reads a console.warn: 

<img width="1203" alt="Screenshot 2024-03-06 at 2 31 33 PM" src="https://github.com/penumbra-zone/web/assets/16624263/760052df-ce5a-4045-ad55-83e17240d08b">

Looks like we may not be bubbling up the error for proxied services

**Comment by TalDerei** [comment]
Is this done?
