### ISSUE TITLE
Clear cache

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#70]

**Comment by zpoken** [comment]
Clear cache steps:

- [ ] stop the sync process
      - [ ]

**Comment by zpoken** [comment]
@grod220  Can you check if these steps are correct? I've already done the 1st and 2nd point; for the 3rd we need a method with wasm; 4 I understand that so far only 1 value we have to change

**Comment by grod220** [comment]
For the viewServer, you should just need to re-initialize that class. I don't think you need a free method. Just throw the old class away. For `networks custom values`, not sure you need to clear anything there.

The rest seems right to me 👍

**Comment by zpoken** [comment]
@grod220 can you check if I'm moving in the right direction-  https://github.com/penumbra-zone/web/compare/main...70-clear-cache

**Comment by grod220** [comment]
Yes, that looks like the right direction to me. If you open a PR, I can give more specific feedback. Does it work?

**Comment by zpoken** [comment]
`Query data cannot be undefined. Please make sure to return a value other than undefined from your query function. Affected query key: ["sync-blocks","https://grpc.testnet.penumbra.zone"]`

```
Error: ["sync-blocks","https://grpc.testnet.penumbra.zone"] data is undefined
    at Object.onSuccess (vendor.js:145256:19)
    at resolve
```
works, but show errors from console this hooks -useSyncProgress
