### ISSUE TITLE
ViewBox should use 'children' prop

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#702]
viewbox uses a custom 'visibleContent' prop instead of just accepting children like a normal component

https://github.com/penumbra-zone/web/blob/873303d2bf9fff5e514c02c6b63bc935d048dd84/packages/ui/components/ui/tx/view/viewbox.tsx#L12-L34

**Comment by TalDerei** [comment]
closing since `ViewBox` is part of our deprecated v1 UI component library.
