### ISSUE TITLE
Standalone asset & chain registry [new repo]

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#703]
It's quite common to create an independent registry ([see cosmos example](https://github.com/cosmos/chain-registry)) which can be used by a number of external contributors.

At the moment, it's somewhat buried in our [constants package](https://github.com/penumbra-zone/web/blob/main/packages/constants/assets/local-asset-registry.json). We also want to expand this to a chain registry for [IBC actions](https://github.com/penumbra-zone/web/issues/343).

Todo: 
- Create new `registry` repo
- Migrate asset registry
- Make placeholder for chain registry
- Setup npm publishing pipeline
- Add new dependency to web monorepo and remove old registry
- RPC registry
- Chain Registry
- Numeraire registry?

**Comment by grod220** [comment]
@hdevalence realizing we should be using the public https://github.com/cosmos/chain-registry instead and not create our own repo

**Comment by hdevalence** [comment]
We need our own repo because we need to transport the token metadata along IBC channels.

**Comment by hdevalence** [comment]
This would involve a script that pulls the cosmos chain registry and a set of channel configurations as a source and then builds a set of Penumbra metadata objects with the denom prefixed by the channel name, the penumbra asset IDs included, etc

**Comment by hdevalence** [comment]
I believe this was discussed in a different issue but I'm not sure where offhand.
