### ISSUE TITLE
Reveal secure data

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#72]
- [x] Recovery passphrase reveal
- [x] Full viewing key reveal
- [x] Spending key reveal

**Comment by zpoken** [comment]
@grod220 is this right way to receive seed?

```
 getSeedPhrase: async () => {
        const passwordKey = get().password.key;
        const key = await Key.fromJson(passwordKey!);

        const encryptedSeedPhrase = get().wallets.all[0]?.custody.encryptedSeedPhrase;
        const unsealeSeedPhrase = await key.unseal(encryptedSeedPhrase!);

        return unsealeSeedPhrase?.split(' ') ?? [];
      },
```

**Comment by zpoken** [comment]
https://github.com/penumbra-zone/web/blob/72-reveal-secure-data/apps/extension/src/state/wallets.ts#L39

**Comment by grod220** [comment]
Yes, I believe so. Please test it out.

**Comment by zpoken** [comment]
key.unseal return null

**Comment by zpoken** [comment]
that's why I'm asking, because it always returns null

**Comment by grod220** [comment]
Please debug and see why it returns null. If you can't figure it out, I can debug tomorrow.

**Comment by zpoken** [comment]
we shuold use this function (https://github.com/penumbra-zone/web/blob/72-reveal-secure-data/apps/extension/src/state/password.ts#L33) instead setPassword when login! setPassword create new instance of key
