### ISSUE TITLE
ui package exports are complex

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#728]

**Comment by TalDerei** [comment]
we've had a bunch of changes with package exports and publishing, is this still relevant?

**Comment by VanishMax** [comment]
the exports were simplified for v2, so users now import the components like this:

```ts
import { Button } from '@penumbra-zone/ui/Button`;
import { Text } from '@penumbra-zone/ui/Text`;
```

we still have to remove the v1 to not even include it in NPM but that might not be the scope if this issue. I'd close it

**Comment by TalDerei** [comment]
> we still have to remove the v1 to not even include it in NPM but that might not be the scope if this issue. I'd close it

can you capture this in another issue and close this?

**Comment by VanishMax** [comment]
Will be followed by #1754
