### ISSUE TITLE
Connected sites

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#73]
User should be able to visit dapp and connect the penumbra wallet. This should trigger a popup to approve.

In the `Connected Sites` settings in the popup, the user should be able to revoke approvals.

**Comment by zpoken** [comment]
Connect wallet steps:
- [ ] User send message to extension from dapp
- [ ] Extension open notification window
- [ ] Accept
          - [ ] asdasd

**Comment by zpoken** [comment]
@grod220 how we will send a request to connect to the extension from webapp?

**Comment by grod220** [comment]
Write a route to handle the request: https://github.com/penumbra-zone/web/tree/main/apps/extension/src/routes/service-worker/extension

**Comment by zpoken** [comment]
we have viewClient to get data, it's only for those requests that are in viewService! what should we use for other requests from dapp to extensions?

**Comment by grod220** [comment]
Work on another task until I can do refactors of the router

**Comment by zpoken** [comment]
1. User firstly open dapp (without connection)  cannot see.
- [ ]  sync progress
- [ ] asset balance
- [ ] wallet id
- [ ] txs
- [ ] chain id
we need additional logic to check if the dapp is added to connected sites and only then return the response from the extension to the dapp! before that, requests should not return anything
2. User click connect
- [ ] open popup with the ability to approve or reject
3. if user click reject
- [ ] close popup
4. if user click approve
- [ ] add origin to connected sites
- [ ] close popup
- [ ] request an extension to receive data from 1 point (implementation is not clear)
5. User reload page
- [ ]  request an extension to receive data from 1 point
6. user logout from extension ???

**Comment by zpoken** [comment]
@grod220

**Comment by grod220** [comment]
> 1. User firstly open dapp (without connection)  cannot see.

There are three scenarios as I see it:

- The extension is not installed. The connect button should have a modal (like in the figma designs) that points to chrome store. All attempts to request balances/sync progress/wallet id, etc---should throw an error if attempted. In fact, the UI should not attempt to make those requests if the extension is not installed.
- The extension is installed, but the URL is not one of the connected sites. The connect button should trigger an accept/reject modal. All requests should throw an error if attempted. It should be the same as above. The UI should not even be attempting to make those requests if it doesn't have permission for that url. The UI should not render those components that make those requests.
- The extension is installed and the URL is whitelisted. All requests go out as normal.

> request an extension to receive data from 1 point (how to do request from dapp to extension without reload page if connect function doesn't return success approve). useQuery has enabled field, we can add connect response there

If following my logic above, this is unnecessary. The approval window should not need to proxy every single call we have. If you make a request and you are not allowed to, that request should throw an error. The UI is responsible to make sure those requests aren't made if you haven't gotten the permission. It's like a normal HTTP request that requires an authenticated cookie.

**Comment by Vadim121197** [comment]
Ok, how Dapp do request to extension immediately after connection?

**Comment by zpoken** [comment]
do we have to write a code that will check if the permissions are available, and it should run every 5 seconds, for example?

**Comment by zpoken** [comment]
How will the dapp know that we are connecting it to the extension?

**Comment by zpoken** [comment]
immediately after connection to redirect the user to /dashboard

**Comment by grod220** [comment]
> do we have to write a code that will check if the permissions are available, and it should run every 5 seconds, for example if the URL has not permission?

No, only when loading the page

> How will the dapp know that we are connecting it to the extension?

You need to write the code in such a way that connection is a request/response

**Comment by zpoken** [comment]
connect function should return response? If so, I'm trying to tell you this

**Comment by grod220** [comment]
> connect function should return response?

In order to do this, you'd have to create a `pending requests` kind of promise handler just like how the grpc event transport works. However, it's probably best if I do this because I have more knowledge on how this works.

In the meanwhile, your statement here:

```
do we have to write a code that will check if the permissions are available, and it should run every 5 seconds, for example if the URL has not permission?
```

would be a fine alternative for now. On the connect page, just check every 500ms if it has permission.

**Comment by zpoken** [comment]
cool) I am glad that we have come to a common opinion

**Comment by zpoken** [comment]
if user doesn`t connect to dapp, he can see only this page - https://www.figma.com/file/iTnIhPxUm4ZleTRKWEn4GM/Penumbra?node-id=3177%3A1201&mode=dev?
@grod220

**Comment by grod220** [comment]
Yes, that's correct.

**Comment by zpoken** [comment]
i try to do `git rebase main` but some of my code is missing!
it my current version
<img width="964" alt="Знімок екрана 2023-10-26 о 15 25 13" src="https://github.com/penumbra-zone/web/assets/82594516/8a792e55-bbe9-4d89-8b89-a3b0b52cb743">
after rebase
<img width="850" alt="Знімок екрана 2023-10-26 о 15 25 35" src="https://github.com/penumbra-zone/web/assets/82594516/ab841bcf-5ff8-4b82-b3c2-05690628d8c8">

**Comment by zpoken** [comment]
connectHandler doesn't exist

**Comment by grod220** [comment]
Your PR has multiple main merge commits throughout its history. At this point, it's probably impossible to rebase. Just do a main merge commit like you have been doing. 

In the future, use this workflow:
- Make commits like normal
- When ready to get the latest updates, rebase your branch on the latest main. This tends to work easiest when you have less commits, so you may want to squash your commits to one before rebasing.
- Never do merge commits

This will make the commit history much more clear and allow reviewers to better understand additional commits after reviews.

**Comment by zpoken** [comment]
<img width="351" alt="Знімок екрана 2023-10-26 о 15 52 19" src="https://github.com/penumbra-zone/web/assets/82594516/10727726-1d04-43b0-bf2e-d103be13c6f9">

i have https://chrome.google.com/webstore/detail/freighter/bcacfldlkkdogcmkkibnjlakofdplcbk?hl=ru and it return error to our dapp after connect click) just for information) @grod220

**Comment by grod220** [comment]
What is the nature of that error? Can you create another github issue with more detail so we can plan to fix that bug?

**Comment by zpoken** [comment]
this error return another extension, not penumbra

**Comment by zpoken** [comment]
https://github.com/penumbra-zone/web/issues/150

**Comment by zpoken** [comment]
@grod220  is there good place to check is site connected - https://github.com/penumbra-zone/web/blob/73-connected-sites/packages/router/src/root-router.ts#L25?

**Comment by zpoken** [comment]
but then https://github.com/penumbra-zone/web/blob/73-connected-sites/packages/router/src/root-router.ts#L23 should be before allowedRequest

**Comment by grod220** [comment]
In allowedRequest, just check if the message is `isViewServerReq(message)` and if so, check if it's a connected site.

**Comment by zpoken** [comment]
+ allowedRequest should be async

**Comment by zpoken** [comment]
I do not like the option when a user who is not connected can see only 1 page, because dapps do not work like that! maybe it makes sense to create a temporary function (until you add a response to the connect function) isConnected() that will be called every 500ms, and pass the value from it to reactQuery! 

<img width="687" alt="Знімок екрана 2023-10-26 о 17 05 27" src="https://github.com/penumbra-zone/web/assets/82594516/7f37b0a9-1427-4e44-9ad8-500a96957910">

and then the user will be able to enjoy our dapp without connecting

**Comment by zpoken** [comment]
or we do like  - https://wallet.keplr.app/

**Comment by zpoken** [comment]
@grod220

**Comment by zpoken** [comment]
although this function will be useful to us later, we will do a check every time the dapp is loaded (we will remove only setInterval)

**Comment by zpoken** [comment]
it would be like this - https://wallet.keplr.app/

**Comment by zpoken** [comment]
https://app.osmosis.zone/?from=ATOM&to=stIBCX

**Comment by zpoken** [comment]
just add connect wallet button instead other buttons! I think you wrote about this to Daria in design

**Comment by grod220** [comment]
Sure that's fine. Why can't `isConnected()` be in `PenumbraStdClient`? That currently handles request/response no?

**Comment by zpoken** [comment]
it will be a part of PenumbraStdClient

**Comment by zpoken** [comment]
I wrote that I will pass the response of this function to useQuery (enabled Options)! useQuery will automatically do request to extension if `isConnected()` returns true

**Comment by zpoken** [comment]
PenumbraStdClient ping doesn't return response. @grod220 can you check ?

**Comment by zpoken** [comment]
https://github.com/penumbra-zone/web/blob/main/packages/transport/src/proxy.ts#L28 res as undefined

**Comment by zpoken** [comment]
but there is result - https://github.com/penumbra-zone/web/blob/main/packages/router/src/std/router.ts#L22

**Comment by zpoken** [comment]
[https://github.com/penumbra-zone/web/issues/73#issuecomment-1781118389](That does not seem to be a good place for that. Think this is better: https://github.com/penumbra-zone/web/blob/73-connected-sites/packages/router/src/root-router.ts#L43-L48) it make penumbraMessageHandler returned function as async! and it break returned values

**Comment by zpoken** [comment]
i found solution! when i check is connected sites there it makes allowedRequest as async and then penumbraMessageHandler shoulb be to async https://github.com/penumbra-zone/web/blob/73-connected-sites/packages/router/src/root-router.ts#L43-L48

**Comment by zpoken** [comment]
@grod220 wgat do you think about it - https://notes.dt.in.th/20210122T221126Z3124

**Comment by grod220** [comment]
Why is that necessary if it's done here? https://github.com/penumbra-zone/web/blob/dd7fcc98ad78f3b39cb2ef23c42562e155c7ad0a/packages/router/src/std/router.ts#L37C1-L38

**Comment by Vadim121197** [comment]
the listener must return true to indicate asynchronous response.

**Comment by Vadim121197** [comment]
I don't understand

**Comment by grod220** [comment]
It already returns true for Std routes. See my link.

**Comment by Vadim121197** [comment]
I see, but now it doesn't work! When I add async callback

**Comment by Vadim121197** [comment]
Always return undefined

**Comment by Vadim121197** [comment]
Before addListener receive async callback, an `return true` was on lower level, with

**Comment by grod220** [comment]
Ok, I understand now. Just leave it as you've done it.

**Comment by Vadim121197** [comment]
what exactly was wrong?

**Comment by zpoken** [comment]
<img width="1103" alt="Знімок екрана 2023-10-27 о 09 54 10" src="https://github.com/pen
<img width="583" alt="Знімок екрана 2023-10-27 о 09 54 20" src="https://github.com/penumbra-zone/web/assets/82594516/6dbbeb7a-354e-420b-b0d2-93cd6467521a">
umbra-zone/web/assets/82594516/83951d58-6651-4a6b-924d-502859fce5e1">

@grod220

**Comment by zpoken** [comment]
it only exist in my branch

**Comment by grod220** [comment]
That is another bug that needs investigating. It only happens in local dev though. I think it may relate to how local dev react with render components twice: https://stackoverflow.com/questions/48846289/why-is-my-react-component-is-rendering-twice.

**Comment by Vadim121197** [comment]
this is due to what we added yesterday! When I delete new function, everything is ok

**Comment by zpoken** [comment]
reactStrictMode: false, doesn't help

**Comment by zpoken** [comment]
https://github.com/penumbra-zone/web/blob/73-connected-sites/packages/router/src/root-router.ts#L26 this solution works

**Comment by Vadim121197** [comment]
@grod220 what do you think?

**Comment by grod220** [comment]
Yes it's fine. Think I'm getting confused with this thread, it's easier to discuss in-line with code-review comments.

**Comment by zpoken** [comment]
@grod220 I added option to `enabled` to `useQuery` (https://github.com/penumbra-zone/web/blob/73-connected-sites/apps/webapp/hooks/wallet-id.ts#L17)!  here are still questions about queries that are not implemented through `useQuery` (`useBalances` for example - https://github.com/penumbra-zone/web/blob/73-connected-sites/apps/webapp/hooks/balances.ts#L23)! how can we not run the `useCollectedStream` function if the user is not connected?

**Comment by grod220** [comment]
That likewise needs `enabled` support

**Comment by zpoken** [comment]
like there - https://github.com/penumbra-zone/web/blob/73-connected-sites/packages/transport/src/hooks.ts#L21?

**Comment by grod220** [comment]
Yes

**Comment by grod220** [comment]
Can start again. Should make a new PR and only copy over the UI work from the old PR.

**Comment by turbocrime** [comment]
part of #475
