### ISSUE TITLE
eliminate `@penumbra-zone/storage`

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#732]
this should reside within the extension app package.

other packages that need anything from storage should be provided data on call or on init.

**Comment by grod220** [comment]
We anticipate one day exposing the router package for extensions that want a turn key solution for being able to handle penumbra frontend requests. That means they'll either need to provide their own storage interface implementation or most likely just use this one. Going to close this issue as we want to keep optionality for it.

**Comment by turbocrime** [comment]
> We anticipate one day exposing the router package for extensions that want a turn key solution for being able to handle penumbra frontend requests. That means they'll either need to provide their own storage interface implementation or most likely just use this one.

the storage package as it stands is incredibly prax-specific. if we expect other consumers to fulfil it, the prax-specific parts should be removed.
