### ISSUE TITLE
Improve external deps import paths

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#736]
_(Given https://github.com/penumbra-zone/web/pull/672 is merged)_

Removing barrel files makes imports look like this:

```typescript
import { shorten } from '@penumbra-zone/types/src/string';
```

External apps that import our package from NPM could do this:

```typescript
import { shorten } from '@penumbra-zone/types/string';

// package.json
 "exports": {
    "./string": "./dist/string.js"
  },
```

Internal packages that would want the same thing would have to do this:

```typescript
import { shorten } from '@penumbra-zone/types/string';

// package.json
 "exports": {
    "./string": "./src/string.ts"
  },
```

We cannot do them for both. In the current best case scenario would be doing this:
```typescript
 "exports": {
    "./string": "./dist/string.js" // for external packages
    "./src/string": "./dist/string.js" // for internal packages
  },
```

However, given our effort to remove barrel imports, having two export paths for every export gets unwieldy very fast (see types package).

This issue is for doing research on how to improve this situation that is the most maintainable possible. Idea: perhaps at build time for external packages, the package.json fields can be overwritten programatically.

**Comment by turbocrime** [comment]
the conventional way to achieve this is an `exports` block in `publishConfig` https://docs.npmjs.com/cli/v10/configuring-npm/package-json#publishconfig

**Comment by TalDerei** [comment]
we've had a bunch of changes with package exports and publishing, is this still relevant?
