### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#74]
Not entirely sure what this section in the popup settings are for. Think we can kill this.

**Comment by Valentine1898** [comment]
We originally intended this as an **advanced** customization for interacting with the `dApp`. 
This would allow the user to customize which requests `dApp` has access to and which ones it does not. 
For example, the user can disclose his balance to the `dApp`, but not be allowed to view the notes so as not to lose privacy in case of data leakage

**Comment by Valentine1898** [comment]
Right now I think it's hard, it makes sense to put it away and come back in the future if needed

**Comment by grod220** [comment]
I agree, let's kill this for now and revisit later
