### ISSUE TITLE
Convert from CJS to ESM

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#749]
We should move all CommonJS (CJS) usages to ECMAScript Modules (ESM). Should allow us to better take advantage of tree shaking 🌳  given ESM is more statically analyzable compared to CJS. This means potentially smaller bundles. Also, CJS is slowly phasing out in the javascript ecosystem.

Todo:
- update the Webpack configuration to output ESM modules
- refactor require/module.exports to import/export statements

**Comment by turbocrime** [comment]
i think our only cjs modules are actually eslint and tailwind

**Comment by turbocrime** [comment]
is this still relevant if we are publishing ts packages

**Comment by turbocrime** [comment]
completed by https://github.com/penumbra-zone/web/pull/1460
