### ISSUE TITLE
Networks

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#75]
User should be able to add/remove RPCs (e.g. https://grpc.testnet.penumbra.zone) from the popup settings.

Consequently, the popup homepage should be able to show and select network options. After selecting a new network, the popup should start syncing on that new network.

**Comment by zpoken** [comment]
@grod220 whether we will check whether we have entered a valid RPCs, that means the user does not enter invalid values (e.g., https://www.google.com/)

**Comment by zpoken** [comment]
<img width="370" alt="Знімок екрана 2023-10-17 о 10 16 16" src="https://github.com/penumbra-zone/web/assets/82594516/1d96ea69-6779-4df6-a2f0-b26f86c804a5">

metamask as example

**Comment by zpoken** [comment]
is there function which return all chain?

**Comment by grod220** [comment]
Networks should only add/select the RPC url (e.g. https://rpc.testnet.penumbra.zone/). The user should not be able to select chain id. The chain ID comes from the node.

**Comment by Vadim121197** [comment]
will we always have 1 chain?

**Comment by Vadim121197** [comment]
Is Add/select right?We have only 1 input where user can only change grpc

**Comment by grod220** [comment]
We need a way for users to select their RPC urls. From that URL, the chain id can be derived. I suppose we don't need more than one. So perhaps just editing that url link is fine. This should be the flow:

- User clicks "Networks" in settings. Maybe we should rename this to RPC? 🤔 
- User sees the URL and has the ability to change it.
- Below the URL should be some chain parameters so users know what chain that rpc is connecting to.

I understand if this does not fit the current design perfectly. Please change to model this user flow though.

**Comment by zpoken** [comment]
how can we check is rpc valid?
so that the user cannot enter any value

**Comment by grod220** [comment]
By requesting chain id, if that query fails, then it's not a valid RPC link. Just like that screenshot in metamask.
