### ISSUE TITLE
Transaction fails to build with "Cannot use 'in' operator to search for 'error' in undefined"

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#751]
https://discord.com/channels/824484045370818580/915710988312002610/1217560532144492546

![image](https://github.com/penumbra-zone/web/assets/134443988/5330740e-ca7d-4d65-aa19-607b8660f7aa)

there are at least two issues here

1. approval popup is failing to stand up properly. may be a zustand or ser/de or getter issue
2. the actual failure's error is failing to propagate properly. much of that flow has changed since the last release but we can still tighten that up

**Comment by grod220** [comment]
Think this is done?

**Comment by TalDerei** [comment]
what's the status of this issue?

**Comment by TalDerei** [comment]
closing as we haven't encountered this issue in a long time and it seems resolved
