### ISSUE TITLE
Dropping the /src/ 

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#762]
In https://github.com/penumbra-zone/web/pull/672 we removed a number of barrel files. While this is more performant, we are now appending `/src/` to a bunch of imports:

```typescript
import { createChannelTransport } from '@penumbra-zone/transport-dom/src/create';
```

It would be nice to be able to drop this and have: 

```typescript
import { createChannelTransport } from '@penumbra-zone/transport-dom/create';
```

Also, this is largely not an issue with external code imports as they can do:

```typescript
    "exports": {
      ".": "./dist/prax.js",
      "./global": "./dist/global.js",
      "./get-port": "./dist/get-port.js"
    }
```

However, doing like so with internal code renders a type error
```typescript
    "exports": {
      ".": "./src/prax.ts",
      "./global": "./src/global.ts",
      "./get-port": "./src/get-port.ts"
    }
```

**Comment by turbocrime** [comment]
this can be handled by publishConfig

**Comment by turbocrime** [comment]
there's actually a couple of these left, have some local work on it
