### ISSUE TITLE
bech32 package does not validate properly

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#778]
during reorganization of bech32 utilities into their own package, i discovered they improperly handle length, and in some cases may be improperly truncating data.

edit:

bech32m format described here https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki

splitting out bech32 package, i strove to organize but maintain exact functionality. some of the functionality was acknowledged incorrect.

previously, we were using only a couple functions for calculating/checking/encoding, with `LIMIT` parameters that did not necessarily match the actual data we were handling. notably, a generically named function was used in many places. while incorrect, it was functioning, so i maintained the exact behavior when splitting out the package, while providing clearer names.

https://github.com/penumbra-zone/web/blob/1e4476eb0d4d1ba13c483bc0686179794b6ce68c/packages/types/src/address.ts#L17-L20

it looks like some work has since been done to expand some of that in https://github.com/penumbra-zone/web/pull/846. specifically, lengths for most things are now present.

https://github.com/penumbra-zone/web/blob/69e02d5810ede7ad39bcb218235669fd6e067d3b/packages/bech32/src/penumbra-bech32.ts#L1-L12

the bech32 package we depend on contains a hard-coded default `LIMIT` parameter of 90 characters total. this is appropriate for bitcoin segwit: a human-readable part of 'bc', separator, data containing 20 bytes, checksum suffix is well below 90.

https://github.com/bitcoinjs/bech32/blob/fd92fdfba8cf7a7de6cab5cec683d5576d5bb2f1/src/index.ts#L103-L105

many of our encoded lengths are longer. ignoring the 90-char maximum in spec, the appropriate string length for any given prefix and data works out to

```ts
const bech32Length = (prefix: string, data: Uint8Array) =>
  prefix.length +
  1 + // separator
  Math.ceil((8 / 5) * data.length) +
  6; // checksum
```

not all of the lengths defined in the exports conform to this, and the lengths are not consistently used to confirm appropriate input/output size.

also, as the package is intended for string manipulation and not messaging, we should not import buf packages. the types do not provide any type safety in this package - every type imported describes a trivial `{ inner: Uint8Array }`. ideally, this should be a utility package that anyone wanting validation or basic conversion could import with minimal dependency graph. buf packages are available in the workspace but not present in `package.json`, so as currently published it is broken.

objectives

1. possibly rename everything. we're using bech32m, not bech32. also the to/from utility names are very similar
2. confirm length for every bech32 string by verifying byte sizes in core repo
3. use an explicit calculation or document each length where exported
4. utility functions should correctly enforce lengths
8. write tests to confirm utility fns are not corrupting data
7. only handle bare string and uint8array input/output, not pb types
8. export byte length constants
9. export regexes like
```ts
export const PENUMBRA_BECH32_ADDRESS_REGEX = /^penumbra1[02-9ac-hj-np-z]{128}$/;
```
9. export template literals like
```ts
export type PENUMBRA_BECH32_ADDRESS = `${typeof PENUMBRA_BECH32_ADDRESS_PREFIX}1${string}`
```

**Comment by grod220** [comment]
Discussed in meeting: @turbocrime to add more detail to this issue

**Comment by turbocrime** [comment]
[some tests in the correct direction](https://github.com/penumbra-zone/web/tree/turbocrime/bech32-tests)
