### ISSUE TITLE
explore externally_connectable

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#785]
externally_connectable supports `https://*` permission, which might be preferable to the DOM channel session and forwarding we currently implement

**Comment by grod220** [comment]
From meeting:

- Add to the manifest
- Have a very small use of it in the codebase
- Submit for approval (with reasons in the chrome dev dashboard)

**Comment by grod220** [comment]
Reference docs: https://developer.chrome.com/docs/extensions/reference/manifest/externally-connectable

It does not appear that `externally_connectable` allows for `<all_urls>` match pattern. Think this may be a blocker for us.

**Comment by turbocrime** [comment]
the documentation is outdated, it has been patched to support TLD wildcards

**Comment by turbocrime** [comment]
permission added by #1144 and work for v2 in #1145
