### ISSUE TITLE
ci compile wasm-pack intermittent failure

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#786]
https://github.com/penumbra-zone/web/actions/runs/8330249542/job/22794456883

<img width="974" alt="Screenshot 2024-03-18 at 09 57 42" src="https://github.com/penumbra-zone/web/assets/134443988/f9929e10-8839-4f4a-b95f-04bc241f0e9e">

**Comment by TalDerei** [comment]
Is this issue still relevant?

**Comment by turbocrime** [comment]
i think this was due to oom or something. havent seen any problems in a while.
