### ISSUE TITLE
IBC in widget helpers

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#79]
We need a way for users to be able to IBC into penumbra from other cosmos chains. Two ways users can do this:

1. In Keplr directly, IBC using their interface
2. In our interface, have buttons for `<Deposit from Keplr>` and `<Deposit from Leap>` that connect with a user's wallet and provide the IBC message automatically.

We should implement #2 on our receive page. Think we can take inspiration from: https://app.osmosis.zone/assets

====

Update:

Example code in https://github.com/skip-mev/ibc-dot-fun and https://github.com/skip-mev/skip-router-sdk for composing the right IBC-in paths.

**Comment by grod220** [comment]
To take over with this issue: https://github.com/penumbra-zone/web/pull/808

**Comment by turbocrime** [comment]
relevant to #806
