### ISSUE TITLE
Implement rounding on IBC-timeouts

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#812]
Reference https://github.com/penumbra-zone/penumbra/issues/4064

At the moment, the web code implements milliseconds. Turns out, it actually needs nanoseconds to work properly. However, this is a potential privacy leak. After core code implements rounding, implement a mirror implementation to `pcli withdraw` in the web code: 

https://github.com/penumbra-zone/web/blob/main/apps/minifront/src/state/ibc.ts#L97-L98

**Comment by hdevalence** [comment]
Reopening since #814 only does the ns handling, not the rounding -- the exact rounding requirements are still to be determined

**Comment by jessepinho** [comment]
Looks like this is already done. See https://github.com/penumbra-zone/web/pull/814/files#diff-94aed5922764847745c6bb8a662a45633114dd038950d343e41ecad08a4b5687R98-R100

**Comment by jessepinho** [comment]
(@turbocrime , please confirm that I'm correct in closing this)

**Comment by turbocrime** [comment]
the code you linked does perform rounding, but it is incorrect. the details of the appropriate rounding were not specified until more recently. the issue needs to be updated with the intended resolution and interval
