### ISSUE TITLE
Extension "trusted testers" publish workflow

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#819]
Currently, after we have a release in the repo, [extension-publish.yml](https://github.com/penumbra-zone/web/blob/main/.github/workflows/extension-publish.yml) runs. It adds the extension to the review queue, which upon approval, immediately publishes the new version publicly.

In the attempt to build a more robust beta-testing setup, we want to change this up a bit. It looks like this:

- We are ready to release a new extension version
- We create a repo release which runs `extension-publish.yml`
- It adds to review queue and sets the [publish-target](https://github.com/mnao305/chrome-extension-upload/blob/cbba77bc133c3cdc6e0e4248abb5f093ec7e3bd1/action.yml#L31) to `trustedTesters`
- We inform the tester group to review the new update
- When they've deemed it all good, we click publish in the developer dashboard, which immediately makes it public

We should sync with Park about securing the gmail's of this particular group of volunteers from discord + likely a dedicated channel for feedback. Their emails need to be manually added within the developer dashboard.

**Comment by TalDerei** [comment]
https://github.com/penumbra-zone/web/issues/138 for visibility
