### ISSUE TITLE
Bug: White border on popup

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#82]
<img width="284" alt="Screenshot 2023-10-06 at 4 48 39 PM" src="https://github.com/penumbra-zone/web/assets/16624263/88329523-553b-4906-b46e-2ebee8f9c24e">

Think this may have been introduced within the last week or so.

**Comment by grod220** [comment]
Any ideas about this one @Vadim121197?

**Comment by zpoken** [comment]
i`ll fix it! i don't have any ideas

**Comment by grod220** [comment]
Starting to realize that all chrome extensions have this border. It's only visible when you have a dark screen behind the extension and it's noticeable. Don't think we can do anything about this.
