### ISSUE TITLE
Documentation refactor

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#822]
Before mainnet, we should clean up and better structure our web documentation / readmes. We should also maybe consider publishing them (see https://guide.penumbra.zone/main/index.html and https://protocol.penumbra.zone/main/index.html), and link relevant blog posts (https://penumbra.zone/blog) in our docs. 

Currently, they feel like a random collection of disconnected components that make onboarding potentially more challenging.

**Comment by grod220** [comment]
Definitely open about improving [the web repo's docs page](https://github.com/penumbra-zone/web/blob/main/docs/README.md). However, these seem quite different than the Penumbra guide. That guide is published in an externally friendly way given it has a number of consumers (validators, market makers, devs, etc).

In our case, the only people that would be interested in the web repo docs would be developers on the web repo itself. And in that case, a github readme seems appropriate. 

As far as our externally published packages (like `packages/client`), those readme's should be pretty robust and descriptive on how third-parties can use it. We have some definite docs-debt to be paid in that area.
