### ISSUE TITLE
More stateful error message for swap approvals with foreign claim addresses

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#831]
References discussion in https://github.com/penumbra-zone/web/pull/821. Currently, an invalid foreign claim address will display the `"Transaction canceled"` toast, rather than showing the error message about the website stealing your funds. That's because it throws a `ConnectError` with `Code.PermissionDenied`, which minifront catches and displays as "Transaction canceled." 

We may want to consider displaying a more stateful error message describing why the swap transaction was canceled down the line.

**Comment by hdevalence** [comment]
I don't think we need to do anything here — the extension should give the page the exact same response as if the user hit the reject button themselves. Frontends should never do this anyways, so I'm not sure there's anything to show to the user either.

**Comment by grod220** [comment]
>  the extension should give the page the exact same response as if the user hit the reject button themselves

I think we can just put the error message into the toast instead of overriding it in minifront. However, this sounds like you're saying the extension should obfuscate our errors and hand back something generic. I'm not sure this is a good thing.

**Comment by jessepinho** [comment]
Copying over my comment from #821:

> Here's the issue: minifront will never try to steal the user's funds, so we never need to show this message to minifront users.
> 
> We _should_ show this message to users on other sites who try to steal the user's funds, but obviously, a malicious website isn't going to proactively show this error to people. But if they're trying to steal people's funds, they'll presumably test the stealing-people's-funds functionality first, and they'll realize that this error shows up, at which point they'll either A) give up, or B) at least suppress this error.
> 
> So I'm not actually sure how useful this error is?
> 
> The only way it could be useful is if we could show this error _in the transaction approval popup_, which the malicious website has no control over. Not sure if this is possible, though, since this error is thrown inside an RPC method implementation.

I'll add to this that the extension _does_ throw this error! It's not being "suppressed" at all, except in Minifront — which, again, will never try to steal the user's funds. So I think this issue can be closed.
