### ISSUE TITLE
Wasm errors are not displayed anywhere 

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#84]
We need to log errors that occur during block scans or other wasm calls. 
At the moment we just call the function
```typescript
async autoRetrySync()
``` 
and synchronization is automatically resumed. 
I've temporarily added console.error here to test the new wasm, but there is probably a better solution. 
```typescript
  async autoRetrySync() {
    try {
      await backOff(() => this.syncAndStore(), {
        maxDelay: 30_000, // 30 seconds
        numOfAttempts: Infinity,
        retry: async error => {
          console.error(error); // <---------------
          await this.viewServer.resetTreeToStored();
          return !isAbortSignal(error);
        },
      });
    } catch (e) {
      // Was signaled to abort, can swallow this error
    }
  }
```

**Comment by grod220** [comment]
Yeah, I agree. In general, we should think through places where errors are not being seen and logging those.
