### ISSUE TITLE
Move block processing into wasm

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#843]
### Context
- Currently the longest running task in compact block processing is due to [json serialization](https://discord.com/channels/824484045370818580/1044457038886998137/1219744879786328095) ([relevant line](https://github.com/penumbra-zone/web/blob/e889b9a1780e6efaf5627baccc1f81077805736b/packages/wasm/src/view-server.ts#L53)). 
- It is required to do so as our [rust code](https://github.com/penumbra-zone/web/blob/main/packages/wasm/crate/src/build.rs#L30-L31) deserializes from json. So we are passing it like so: 

```
js class -> json -> | wasm boundary | -> rust struct
```

- Attempts to [serialize through binary](https://discord.com/channels/824484045370818580/1044457038886998137/1220303149307265134) have not added any performance gains
```
js class -> binary -> | wasm boundary | -> rust struct
```

- [An idea](https://github.com/penumbra-zone/web/pull/820) arose to move more decryption logic into typescript to put less load on serialization requirements. However, it did not have any performance gains.

### To do

Given wasm is quite performant, the idea is to move block processing into wasm entirely. This prevents the back-and-forth serialization overhead. It may even simply logic if it only exists in one domain.

== Consideration ==
We are querying from typescript [HERE](https://github.com/penumbra-zone/web/blob/main/packages/query/src/block-processor.ts#L158-L162). By default, `connectRPC` is taking the bytes from the query response and [parses them](https://github.com/connectrpc/connect-es/blob/06234f16d9e06a140f953e0115952a7324878897/packages/connect-web/src/grpc-web-transport.ts#L292). So our current flow actually looks like this:

```
bytes -> js class -> json -> | wasm boundary | -> rust struct
```

We should attempt to simplify this to:
```
bytes -> | wasm boundary | -> rust struct
```

This would mean copying over parts of code that allow us to not parse, but pass the UnitArray on. Suggestions:
https://bufbuild.slack.com/archives/CRZ680FUH/p1711072213138009

From bufbuild team:

```
function toHex(uint8Array) {
    return uint8Array.length === 0 ? '' : '0x' + Array.from(uint8Array).map(i => ('0' + i.toString(16)).slice(-2)).join(', 0x');
}
fetch("https://demo.connectrpc.com/connectrpc.eliza.v1.ElizaService/Say", {
    method: 'POST',
    headers: {
        "Content-Type": "application/grpc-web",
    },
    body: new Uint8Array(5), // Valid zero-length request message in gRPC Web
}).then(async (response) => {
    const header = new Uint8Array(5);
    let headerPos = 0;
    let payload = new Uint8Array(0);
    let payloadRemaining = 0;
    for await (const chunk of response.body) {
        for (let pos = 0; pos < chunk.length;) {
            if (headerPos < 5) {
                while(headerPos < 5 && pos < chunk.length) {
                    header[headerPos++] = chunk[pos++];
                }
                if (headerPos === 5) {
                    payloadRemaining = new DataView(header.buffer).getUint32(1, false);
                }
                console.log(`Header read pos: ${headerPos}`);
            }
            if (payloadRemaining > 0) {
                const chunkLen = Math.min(chunk.length - pos, payloadRemaining);
                const newMessage = new Uint8Array(payload.length + chunkLen);
                newMessage.set(payload);
                newMessage.set(chunk.subarray(pos, pos + chunkLen), payload.length);
                payload = newMessage;
                pos += chunkLen;
                payloadRemaining -= chunkLen;
                if (payloadRemaining === 0) {
                    // Got an entire message.
                    if (header[0]&0x80) {
                        // Trailers frame
                        console.log(`gRPC Web Trailer: flags=${header[0]} payload:\n${new TextDecoder().decode(payload)}`);
                    } else {
                        // Message
                        console.log(`gRPC Web Message: flags=${header[0]} payload=${toHex(payload)}`);
                    }
                    headerPos = 0;
                    payload = new Uint8Array();
                }
                console.log(`Remaining message bytes: ${payloadRemaining}`);
            }
        }
    }
});
```

Though, we may be able to skip typescript fetching entirely and simplify this to:
```
bytes -> rust struct
```

Which would only be possible if we query for blocks directly from Rust using a wasm-compatible grpc client like [tonic-web-wasm-client](https://github.com/devashishdxt/tonic-web-wasm-client).

Tasks:
- [x] Validate speed of block processing with performance tracing of a smallish subset of block syncing
- [ ] Create new rust fetch_and_sync method
- [ ] Migrate all typescript logic to this new method

**Comment by grod220** [comment]
> if we query for blocks directly from Rust using a wasm-compatible grpc client

This is possible in theory, but the rabbit hole may be too deep for now (?). We need the [rpc feature](https://github.com/penumbra-zone/penumbra/blob/main/crates/proto/Cargo.toml#L10) enabled to get the query clients needed for `tonic-web-wasm-client`. We also need the proto-compiler's [tonic-build dep](https://github.com/penumbra-zone/penumbra/blob/6897901b37f5c72d4b5c593167f0e0b933dd2eb5/tools/proto-compiler/Cargo.toml#L18) to exclude the tonic transport impls and re-compiled. Something like:

```toml
tonic-build = { version = "0.10.0", default-features = false, features = ["cleanup-markdown"] }
# then run ./deployments/scripts/protobuf-codegen 
```

And then finally, we need to have `penumbra-proto` package be wasm compatible:

```
cargo build --lib --release --target wasm32-unknown-unknown
```

At the moment, we are greeted by an assortment of compile issues relating to required "js" features and exclusion of randomness libs.

**Comment by TalDerei** [comment]
we should close this as not planned

**Comment by turbocrime** [comment]
the underlying motivation is raw performance, but the primary goal has been identified as parallelization. in fact the compute-heavy tasks of the block processor are already performed in wasm.

at best this issue needs refinement, but i think ultimately it does not represent current understanding of the objectives.

given the present consensus and planning effort, to be issued in the next few days, i'm closing this issue.
