### ISSUE TITLE
replaceable use of JsValue in wasm crate

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#845]
parameter

- [ ] https://github.com/penumbra-zone/web/blob/f9035963fd32663d5f10c9f8391493c82cc2c04f/packages/wasm/crate/src/keys.rs#L90
- [ ] https://github.com/penumbra-zone/web/blob/f9035963fd32663d5f10c9f8391493c82cc2c04f/packages/wasm/crate/src/keys.rs#L103
- [ ] https://github.com/penumbra-zone/web/blob/f9035963fd32663d5f10c9f8391493c82cc2c04f/packages/wasm/crate/src/keys.rs#L120
- [ ] https://github.com/penumbra-zone/web/blob/f9035963fd32663d5f10c9f8391493c82cc2c04f/packages/wasm/crate/src/keys.rs#L136
- [ ] https://github.com/penumbra-zone/web/blob/f9035963fd32663d5f10c9f8391493c82cc2c04f/packages/wasm/crate/src/keys.rs#L154
- [ ] https://github.com/penumbra-zone/web/blob/f9035963fd32663d5f10c9f8391493c82cc2c04f/packages/wasm/crate/src/dex.rs#L26
- [ ] https://github.com/penumbra-zone/web/blob/f9035963fd32663d5f10c9f8391493c82cc2c04f/packages/wasm/crate/src/view_server.rs#L82-L87

return

- [ ] https://github.com/penumbra-zone/web/blob/d7d46634faae608928fb696c6ae276e06dc1aa09/packages/wasm/crate/src/dex.rs#L13
- [ ] https://github.com/penumbra-zone/web/blob/f9035963fd32663d5f10c9f8391493c82cc2c04f/packages/wasm/crate/src/view_server.rs#L298

**Comment by grod220** [comment]
- `get_wallet_id` will be covered in https://github.com/penumbra-zone/web/pull/846
- `get_address_by_index` ✅
- `get_ephemeral_address` ✅ 
- `is_controlled_address` ❌ not in codebase anymore
- `get_short_address_by_index` ✅ 
- `get_lpnft_asset` ✅ 
- `view_server` ❌ stored tree & constants are not pb types with vec encoding abilities
- `compute_position_id` ✅ 
- `get_sct_root` ✅
