### ISSUE TITLE
Add notes table to indexed db

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#85]
https://github.com/penumbra-zone/web/blob/fd9d82057f69d2d333b8dcd6982095733a768360/packages/storage/src/indexed-db/index.ts#L38

We must add the notes table to the indexed db for wasm working correctly 
```typescript
        db.createObjectStore('notes');
``` 
There is also a `notes` table in `sqllite` structure of `pcli`. It is needed so that during block scanning we can save advices for future swap claims

**Comment by grod220** [comment]
Is that something different than `spendable_notes`? Won't this be resolved on the next chain upgrade and the web updates to the lastest wasm?

**Comment by Valentine1898** [comment]
No, to simplify, when we swap we have a `NoteRecord` (`notes` table) that cannot be spent yet 
When we do swap claim, we can take the `NoteRecord` we saved earlier, add nullifier to it, and get a `SpendableNoteRecord` (`spendable_notes` table) that can already be spent. 
`NoteRecord` is a part of `SpendableNoteRecord`

**Comment by Valentine1898** [comment]
I additionally tested the swap claim handling during sync, everything works correctly
