### ISSUE TITLE
Update the privacy policy link in the chrome store 

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#859]
In the Confidentiality section there is a link to the zpoken privacy policy page https://privacy.penumbra.zpoken.io
Need to replace it with penumbra.zone privacy policy
![image](https://github.com/penumbra-zone/web/assets/25391690/1fddae68-45e7-473e-8f4d-a8c0c441bef8)

**Comment by grod220** [comment]
@hdevalence where should Prax's privacy policy live? Should we deploy a new domain only for Prax to host this?

**Comment by hdevalence** [comment]
DM'd

**Comment by jessepinho** [comment]
I assume this can only be done by the Chrome web store admins, right?

**Comment by grod220** [comment]
Yes, after we migrate, I can swap it out. Will require Chrome review too.

**Comment by grod220** [comment]
Managed on Labs internal board now
