### ISSUE TITLE
Web extension has SCT divergence on my testnet wallet

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#879]
xref #878 

My testnet wallet can't make any transactions on the testnet because of an SCT divergence, which should not happen. This issue tracks identification and resolution of that bug.

**Comment by grod220** [comment]
Can you check again with the new console checker? (PR: https://github.com/penumbra-zone/web/pull/882)

I wonder if the bug fix in there may have helped on your end.

**Comment by hdevalence** [comment]
I reran sync with that code and it works!
