### ISSUE TITLE
qualify and explain "This software runs entirely on your device."

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#884]
https://github.com/penumbra-zone/web/blob/69e02d5810ede7ad39bcb218235669fd6e067d3b/apps/minifront/src/components/footer/index.tsx#L11

**Comment by hdevalence** [comment]
Not sure we need to add a lot of detail here, it's a footer intended to give the user the understanding that the hash router is meaningful vs. other frontends that have a backend server.
