### ISSUE TITLE
Extension makes a lot of requests during sync

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#887]
While attempting to sync on a slow network, I opened the network inspector on the popup to see how it was making progress. I noticed two surprises:

- There were dozens to hundreds of `AssetMetadataById` requests at the outset. Looking at them, they seemed mostly requesting info on delegation tokens. Could these be coalesced into a single request?
- During sync, there were hundreds of `AppParameters` requests. I'm not sure why these are required during sync?

**Comment by hdevalence** [comment]
On the second point, it looks like the culprit is in `handleEpochTransition`:
```
    const { sctParams } = await this.querier.app.appParams();
```
This should be using the local data rather than making a network request.

**Comment by hdevalence** [comment]
https://github.com/penumbra-zone/penumbra/issues/4162

**Comment by jessepinho** [comment]
> There were dozens to hundreds of AssetMetadataById requests at the outset. Looking at them, they seemed mostly requesting info on delegation tokens. Could these be coalesced into a single request?

Looks like this is blocked by https://github.com/penumbra-zone/penumbra/issues/4162. Once that's done, this ticket will be ready to pull in.

> During sync, there were hundreds of AppParameters requests. I'm not sure why these are required during sync?

@Valentine1898 just [fixed this](https://github.com/penumbra-zone/web/pull/909#pullrequestreview-1988813949).

**Comment by hdevalence** [comment]
@Valentine1898 Nice!!
