### ISSUE TITLE
Improve swap view rendering

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#889]
Improvements to rendering for swap / swap claim views:

- [x] Instead of "Fee", both Swap and SwapClaim views should refer to it as "Prepaid Claim Fee" to distinguish it from the transaction fee.

~~The "public view" of Swap and SwapClaim is extremely misleading, to the point of lying to users (though this isn't our intent).~~ (EDIT: this was fixed between when I last pulled code and when I filed the issue, amazing!)

- [x] The swap inputs and outputs need to be shown in the public view for a `Swap`. The inputs are public because they are in the clear. The outputs are also known because they can be computed by anyone with the BSOD.
- [x] The prepaid claim fee should be shown only in the user's view and not the public view, because it is not publicly revealed in the Swap.
- [x] The swap inputs and outputs should _not_ be shown in the public view for a `SwapClaim`. The output notes are minted privately and the claim doesn't reveal which swap commitment it claimed.
- [x] The prepaid claim fee should be shown in the public view for a `SwapClaim`. This is because it is revealed publicly (and this is the reason it is _not_ revealed in the Swap).

**Comment by TalDerei** [comment]
Tracked by https://github.com/penumbra-zone/web/issues/875
