### ISSUE TITLE
Remove horizontal scrollbar at bottom of dashboard page

### ISSUE THREAD

**Issue by jessepinho** [penumbra-zone/web#899]
![Image](https://github.com/penumbra-zone/web/assets/1121544/3cf84737-002a-4c08-9d5b-f9958de8b837)

There's currently a scrollbar at the bottom of the dashboard page. This should be removed.

**Comment by jessepinho** [comment]
@grod220 adding this to `mainnet` since it seems like it should be fixed pre-launch

**Comment by grod220** [comment]
Hmm, not sure how this snuck in, we should prioritize this before next week's release. Pulling to todo.
