### ISSUE TITLE
[Right before launch] Update `GRPC_ENDPOINTS` constant with mainnet RPC endpoints

### ISSUE THREAD

**Issue by jessepinho** [penumbra-zone/web#900]
Currently, we have a [`GRPC_ENDPOINTS` constant](https://github.com/penumbra-zone/web/blob/a1e576d/packages/constants/src/grpc-endpoints.ts) that contains a single gRPC endpoint — the Penumbra testnet RPC.

Before we launch to mainnet, we should:
1. remove the testnet RPC node.
2. add some number of RPC nodes for mainnet.

**Comment by jessepinho** [comment]
@grod220 just wanted to confirm that point 1 above is correct — we don't want to show a testnet node as an option once we're in mainnet, right? (Users can always manually enter the testnet endpoint if they want to, of course.)

Re: point 2: how will we get this list?

**Comment by grod220** [comment]
Before we launch, we'll need to have two build configurations. One for testnet and one for mainnet. They'll pull from their respective asset, chain, and rpc registry.

So the task is figuring out how to change webpack such that it points to the right configs.

**Comment by grod220** [comment]
This is a bit out of date since killing the constants package. Going to create a new pre-launch ticket that references new registry.
