### ISSUE TITLE
Deduplicate asset regex between TypeScript and core?

### ISSUE THREAD

**Issue by jessepinho** [penumbra-zone/web#905]
Right now, our [asset patterns](https://github.com/penumbra-zone/web/blob/8933117/packages/constants/src/assets.ts) are duplicates of Regex patterns from core ([example](https://github.com/penumbra-zone/penumbra/blob/de135e8/crates/core/component/stake/src/unbonding_token.rs#L71)). If they change in core, frontend code may get out of sync, and our Regexes won't work correctly.

This is further complicated by the fact that our WASM crate code [modifies](https://github.com/penumbra-zone/web/blob/92d5a9e/packages/wasm/crate/src/metadata.rs#L9) the Regex slightly to include an `id` match for the unbonding token, which is not present in the core repo.

This ticket is to investigate a way to unify these Regexes. It may not be possible, since there may not be a good/desirable way to get WASM code into `minifront`. But if it is, here's what we want to accomplish:
- Unify the various regexes so that they all use the same match groups (i.e., the "id" field in the unbonding token in the web crate).
- Export the regex string from the WASM crate.
- Import that from minifront.

**Comment by jessepinho** [comment]
cc @grod220 since we just discussed this

**Comment by hdevalence** [comment]
The denom patterns can't change, since that would break all users' token holdings, they'll be as they are forever.

**Comment by jessepinho** [comment]
@hdevalence if we're only _adding_ a match group to the Regex, not changing any existing ones, would that still break functionality?

**Comment by hdevalence** [comment]
The regex is a client-side concern, the data it's matching against won't change. I'm not sure what the benefit of adding extra coupling is here. Why should the web code need to be concerned with whether or not Rust code added extra capture groups?

**Comment by jessepinho** [comment]
@hdevalence well, the thing that prompted this ticket was actually the fact that we're currently duplicating core regex in our web crate [here](https://github.com/penumbra-zone/web/blob/92d5a9e/packages/wasm/crate/src/metadata.rs#L9). We're only doing this because A) that Regex isn't exported from core, and B) even if it were, it's missing the `id` match group.

So, for starters, I wanted to at least export that Regex from core so I can use it in the web crate, and add the `id` match group.

If that would break something, though, I can just make a sub-regex that matches against the original regex's `validator` match group. 

But does adding a match group break the existing regex?

**Comment by hdevalence** [comment]
Right, what I'm wondering is, given that the data won't change without losing user funds, it seems like it would be simpler to not make these changes now, and also simpler in the future, because it means we won't have to tightly couple the different parts of the code together.

**Comment by jessepinho** [comment]
OK, fair enough — it does indeed seem to be a web-specific use case to extract the `id` from a delegation token or unbonding token. I'll close this ticket 👍🏻
