### ISSUE TITLE
unhandled context error 

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#936]
@turbocrime following #926, maybe we should display a more user-friendly error message without [HTTP 412](https://github.com/penumbra-zone/web/blob/6577184a0c4406293e8594d10b24069438578903/apps/minifront/src/state/swap.ts#L132-L137).

Additionally, I noticed that for smaller swap amounts that exceed the user's funds for executing the swap, it still calculates the price impact when estimating the swap. For larger swap amounts that exceed the user's funds, it throws an 412 error. Notice the amount differences between these two screenshots. Is this behavior expected?
<img width="1033" alt="Screenshot 2024-04-13 at 6 52 52 AM" src="https://github.com/penumbra-zone/web/assets/70081547/36439712-10de-4c8b-885c-5996be660e38">

<img width="381" alt="Screenshot 2024-04-13 at 6 52 37 AM" src="https://github.com/penumbra-zone/web/assets/70081547/21fe8dc5-b43f-45f7-aa28-631fc0534a10">

**Comment by grod220** [comment]
> maybe we should display a more user-friendly error message

I get a feeling the full error is not bubbling up? Not sure. If this is the full error coming back from the server, we are stuck with it, if not, we should make sure the whole error gets to the client.

>  I noticed that for smaller swap amounts that exceed the user's funds for executing the swap, it still calculates the price impact

This is probably ok. I don't see a reason to prevent folks from estimating swaps if it doesn't match their wallet balance. The important thing is to prevent them from making a swap, so the swap button disables.

**Comment by turbocrime** [comment]
this issue needs refinement. unhandled context is unrelated to propagation or any actual failure
