### ISSUE TITLE
Extension UI should allow configuring the frontend

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#941]
Recently the extension added a frontend link ("Manage Portfolio"). This is great. However, we should allow users to configure their default frontend along with their RPC settings.

**Comment by grod220** [comment]
In the connected sites settings page, there is a ⭐ that can be used to do that. But maybe this isn't super clear. Hmm...

<img width="383" alt="Screenshot 2024-04-15 at 8 32 22 PM" src="https://github.com/penumbra-zone/web/assets/16624263/7c2524a1-2619-4d08-90f1-3e8f2bd9f20f">

**Comment by hdevalence** [comment]
Ahh, I see. I think that's probably reasonable.
