### ISSUE TITLE
Prax support for gradual Dutch auctions

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#943]
**Prax M0**
- [x] prax: pull in new protos
- [ ] prax: define react views for each auction actions:
    - [x] `ActionDutchAuctionSchedule`
    - [ ] `ActionDutchAuctionEnd`
    - [ ] `ActionDutchAuctionWithdraw`

**Comment by jessepinho** [comment]
Going to close this and create tickets for the two remaining auction action types
