### ISSUE TITLE
Navigation: live data

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#95]
<img width="463" alt="Screenshot 2023-10-12 at 2 50 13 PM" src="https://github.com/penumbra-zone/web/assets/16624263/83906318-bf64-45d3-883e-4809b91dc722">

- Chain id: https://github.com/penumbra-zone/web/pull/93
- Wallet id: 
  - New RPC method: https://github.com/penumbra-zone/penumbra/pull/3186
  - Extension+Dapp support: https://github.com/penumbra-zone/web/pull/109
- Notification block syncing: https://github.com/penumbra-zone/web/pull/94

**Comment by conorsch** [comment]
We needed a ViewService method for calling wallet_id. That exists now! https://github.com/penumbra-zone/penumbra/pull/3186 The wallet id is the last remaining mocked data, so this'll be finished soon.
