### ISSUE TITLE
Convert keys script to typescript or rust

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#961]
We currently have a keys package with a [shell script](https://github.com/penumbra-zone/web/blob/main/packages/keys/download-keys) to manage downloading proving keys and managing our local download cache.

The issue is that a shell script beyond quite basic commands quickly becomes unmaintainable. Transitioning this logic to rust or typescript will improve readability and allow others to more easily contribute or edit this.

**Comment by turbocrime** [comment]
i previously wrote a typescript downloader, but switched to a shell script to simplify. i think the shell script is simple enough to understand.

honestly if it is too complex, we should just remove features.

**Comment by turbocrime** [comment]
the ideal solution here is for core repo to publish a release artifact containing keys, so we can just download that and unpack it, and not script anything.

**Comment by turbocrime** [comment]
0.73.0 publishes a tar.gz including key files

**Comment by turbocrime** [comment]
closing in favor of #1205
