### ISSUE TITLE
Unavailable page links to app, not node status page

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#962]
If our extension is unavailable, [we encourage](https://github.com/penumbra-zone/web/blob/bfb101310e5695274d151b36ea1b31fb43dd8df3/apps/minifront/src/components/extension-unavailable.tsx#L18-L25) users to visit the node status page.

However, [this link](https://github.com/penumbra-zone/web/blob/bfb101310e5695274d151b36ea1b31fb43dd8df3/apps/minifront/src/components/extension-unavailable.tsx#L4-L5) points to the app page (https://app.testnet.penumbra.zone) and not node page (https://grpc.testnet.penumbra.zone). 

We should change this to link to the node status page (link retrieved from their set grpc endpoint in the network slice).

**Comment by Valentine1898** [comment]
The grpc endpoint is only defined for extension and we have no way to pass it to minifront, do we? 

Also, the grpc endpoint may not even have a status page

**Comment by grod220** [comment]
Yes, good point 🤔 . Web apps don't have the ability to interact with Prax outside of GRPC requests. I've suggested this before, but it doesn't seem that hard to write an protobuf ExtensionService which would handle requests like this.

> Also, the grpc endpoint may not even have a status page

All nodes should have this out of the box

**Comment by turbocrime** [comment]
i think node configuration is private and it should not be available to the dapp

**Comment by grod220** [comment]
The easiest solution is to replace the text saying to say something like:
```
Please check the status page of the rpc provider in your extension
```

But @turbocrime, what privacy concerns do you have with exposing the rpc provider to the frontend? That this gives them information that could potentially spy on the user of the web app?
