### ISSUE TITLE
Re-thinking react state patterns

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#965]
The [GrpcEndpointForm](https://github.com/penumbra-zone/web/blob/3ecc7a3ac0e4e1cbc2b1c7955187ff7f34285e92/apps/extension/src/shared/components/grpc-endpoint-form/index.tsx#L14) is a perfect testbed for re-thinking some of our data+state management patterns. It dips into many areas:
- async data fetching with react-query
- async event handler via grpc client (with local state for errors)
- custom hook usage
- local state via Zustand
- derived state via selectors
- 6x useState hooks
- 2x useEffects for reactions

The problem is that the cognitive load of understanding all of these side effects is high. It makes the likeliness of a bug slipping in to be higher, and debugging a slog. Sadly, the default tools of react are insufficient of managing this problem sanely. 

As this grows in requirements, every additional react hook grows the mental complexity by even more. For example, [here is run-of-the-mill hook](https://github.com/osmosis-labs/osmosis-frontend/blob/354481a6ca57339567b878dae1e2eb5cb8dd168c/packages/web/hooks/input/use-amount-input.ts) in the osmosis codebase. The effort required to understand the exact relationships between all of its effects are quite high.

### Ideas

- What if we considered using finite state machines as a model for laying out these relationships? ([shameless plug for my talk](https://www.youtube.com/watch?v=NG-fP_nR7Lk)). We could map out all of the states beforehand in an enum and define the events that go between them. Perhaps a class per state? 🤔 . There are also libraries like xstate that could help with something like this.
- Perhaps we should create our own query store within zustand so we don't have to merge zustand+react-hook state in awkward ways.
- Perhaps another state manager (like mobx) could make it easier to map out side effects and derived state (we'd still have to write a custom query store though).

**Comment by jessepinho** [comment]
@grod220 and I discussed on a separate call the possibility of essentially porting some of the key features of [React Query](https://tanstack.com/query/latest) to Zustand, so that, instead of React Query holding its own state separately from Zustand like it does now, _all_ of our state could live inside Zustand.

I'm proposing doing a spike on a solution to this. I was starting to research what a solution would look like, but then realized that's what a spike would be for.

Here's the requirements of a `ZQuery` (Zustand Query) implementation:
1. Easy way to add it to the store:
    ```
    interface MySlice {
      metadata: ZQuery<Metadata>;
    }

    const mySlice = createMySliceSlice((set, get) => ({
      metadata: zQuery(),
    }))
    ```
2. Easy, React Query-like way to use it in a component:
    ```
    const MyComponent = () => {
      const metadata = useZQuery(store => store.mySlice.metadata);
      return (
        <div>
          {metadata.loading && <>Loading</>}
          {metadata.error && <>Error</>}
          {metadata.data && <>Display denom: {metadata.data.display}</>}
        </div>
      )
    }
    ```
3. Integration with React lifecycle hooks.
    - For example, in the code sample above, `useZQuery()` would call `useEffect()` under the hood, automatically fetching the data when the component first mounts.

**Comment by jessepinho** [comment]
Let's discuss at planning on Thursday!

**Comment by jessepinho** [comment]
to explore:
1. Can reach into React Query and get their vanilla JS status of requests
2. Explore using `get propName() {}` syntax to auto-fetch on get

**Comment by jessepinho** [comment]
Inspo from RTK Query: https://redux-toolkit.js.org/rtk-query/overview
