### ISSUE TITLE
Transactions can be viewed on dapp

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#99]
We have the frontend components in the dapp, but it's filled with dummy data. Transactions table + notifications dropdown:

<img width="898" alt="Screenshot 2023-10-13 at 7 32 20 PM" src="https://github.com/penumbra-zone/web/assets/16624263/003f9c01-63c8-48ff-ab10-a109d0e065f9">

<img width="456" alt="Screenshot 2023-10-13 at 7 32 24 PM" src="https://github.com/penumbra-zone/web/assets/16624263/85f5d0da-c118-40e7-9447-bf7191a631ed">

**Comment by conorsch** [comment]
ViewService foundations are in place now. Se progress in parent issue.
