### ISSUE TITLE
Onboarding improvement: return the user to the grpc selection step if he skipped it 

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#993]
If a user interrupts onboarding at the RPC selection stage and comes back after some time, instead of continuing onboarding he gets a broken extension for which `grpcEndpoint` is not set

UPD: 
After #994 it no longer breaks extension, see comments below

**Comment by turbocrime** [comment]
probably we need to add an "onboarding complete" key to storage

**Comment by turbocrime** [comment]
is this still an issue

**Comment by Valentine1898** [comment]
> is this still an issue

If you stop onboarding to select grpcEndpoint, it no longer results in a broken extension. This is fixed in https://github.com/penumbra-zone/web/pull/994 by setting the default `grpcEndpoint`. 
But we can still improve the user experience, and instead of setting the default, return the user to the onboarding step with the grpcEndpoint selection

**Comment by Valentine1898** [comment]
https://github.com/prax-wallet/web/pull/66 solved it
